### ISSUE TITLE
Document contract selection for analysis

### ISSUE THREAD

**Issue by yxliang01** [ConsenSys/mythril#1009]
## Description

In one smart contract source code file, there might be multiple contracts. Mythril should provide an option to specify which ones to process instead of processing all of them.

## Background

Some smart contract definitions might be placed in the same file for their interfaces, or maybe simply it's a design decision to put all the smart contracts for a system in the same file. The user might only want to process only one of them.

## Tests

Input a `.sol` file to Mythril with a contract name specified by some argument, check whether only the specified contract was processed.

**Comment by norhh** [comment]
Currently, such a feature exists try `myth -x file_name:ContractName` that gives it.

**Comment by yxliang01** [comment]
@norhh Right thanks! This is confirmed working. However, this doesn't appear in `--help` usage information? I think this should be added.
