### ISSUE TITLE
docs: no documentation for --transaction-count

### ISSUE THREAD

**Issue by yxliang01** [ConsenSys/mythril#1021]
I've read through the `--help` message and the documentation. However, I couldn't find any explanation of what it really means to set the transaction count. Would be great if it can be explained here, and add to documentation and `--help` message as a documentation improvement.

Thanks

**Comment by norhh** [comment]
@yxliang01 we can't talk about everything in the --help, so checking out read the docs might be better https://mythril-classic.readthedocs.io/en/develop/ .

**Comment by yxliang01** [comment]
@norhh Thanks for replying. However, as suggested in the original post, I didn't see any explanation in the documentation (aka the link you posted). Would you like to point it out if I overlooked?

**Comment by norhh** [comment]
Oh! That's bad, Transaction count is the number of transactions mythril executes. If transaction count is set to x, then mythril can detect vulnerabilities which requires x transactions or less.

**Comment by yxliang01** [comment]
@norhh To be more specific, do you mean the x number of "internal transactions" that are originated from a transaction? I am asking because as far as I know, Mythril doesn't support seeded environment. In this case, the initial blockchain environment is not constrained and vulnerabilities detected may already be ones that require certain blockchain state that multiple transactions are required to achieve such state.

On the other hand, looks like when invoking external contracts, it could be dynamic symbolic execution in the sense that the invoked smart contract code can be concretely retrieved from blockchain with its storage. In this case, the blockchain environment is not wholly unconstrained. If so, I can understand that changing the transaction count can affect the vulnerabilities being detected. Is it so?

**Comment by norhh** [comment]
x is the number of external transactions. First Mythril creates the contract with the constructor, then symbolically executes transactions. Like one example is https://github.com/ConsenSys/mythril-classic/blob/develop/solidity_examples/WalletLibrary.sol , which requires two transactions to kill the contract, one to `initMultiowned` and other to `kill` which will then kill the contract, if transaction count is set to 1 then this issue won't get detected.

**Comment by yxliang01** [comment]
@norhh I see. Indeed, designing the symbolic execution engine in this way can avoid many false positives. However, is there a way to simply generate transaction that run with a completely symbolic state without constraints imposed by the constructor? I think, in such way, only one transaction is enough to uncover all the vulnerabilities with the price of false positive results of vulnerabilities that are not feasible due to the fact that state required to triggered them is in fact possible to reach. This would allow huge speedup of the detection with the price of having more false positives. (Correct me if wrong)

**Comment by norhh** [comment]
Thats how mythril prior `v0.18.5` was, It had lots of false positives, and we couldn't extract a transaction sequence from it.

**Comment by yxliang01** [comment]
@norhh So you meant there's no option for re-enable this behavior currently, right? If so, would you like to point out PR that changed this?

**Comment by b-mueller** [comment]
@yxliang01 I'm not entirely sure but I think what you want is accomplished by the ` --bin-runtime` flag. If you add this, Mythril takes runtime bytecode as input directly, in that case all variables are initially symbolic. The disadvantage is that this only works in conjunction with the `-c <bytecode>` input option.

Another interesting feature you may not know about is that while there's no way to seed the initial state, Mythril will load state (at least storage) dynamically from the blockchain when using `-a <address>`. You can set the initial state you want using Ganache.

**Comment by norhh** [comment]
`I'm not entirely sure but I think what you want is accomplished by the --bin-runtime flag`, In a way yes, but it still considers storage as concrete at the moment. @yxliang01 try using --bin-runtime flag + develop branch + PR https://github.com/ConsenSys/mythril-classic/pull/1039, that would give symbolic state execution.

**Comment by yxliang01** [comment]
Nice @b-mueller @norhh ! Will try sometime later :) Upvote for PR #1039 . To be honest, I think it's just a tradeoff that the old method gives more false positive together with more true positive and higher speed. So, both the old and the new transaction based symbolic execution should be available concurrently I think.
