### ISSUE TITLE
Rewrite integer overflow module to use solver selectively (for discussion)

### ISSUE THREAD

**Issue by b-mueller** [ConsenSys/mythril#1036]
## Description

Revert the logic of the integer module: Instead of solving ahead of time and tracking the overflowed variables to STOPs, use the solver selectively when a STOP instruction is reached. This could be done in several ways, e.g.:

1. Keep track of arithmetic operations, e.g. by building a list in a state annotation (save type, offset & constraints)
2. Taint list entries that get used in SSTORE or JUMPI (mark for overflow check)
3. When STOP is reached, use the solver to check overflows on any tainted arithmetic operations that were tainted (perhaps use some additional logic to reduce the list).

## Rationale

Hopefully this should significantly reduce the time spent on solving.

**Comment by JoranHonig** [comment]
Yes that could definately work, and shouldn't be too big of a change to the module. Great idea!
