### ISSUE TITLE
Mythril is slow while executing proxy.sol

### ISSUE THREAD

**Issue by norhh** [ConsenSys/mythril#1048]
## Description
As @b-mueller mentioned in #1042 mythril is slow while executing proxy.sol which is a very small contract.

**Comment by b-mueller** [comment]
It seems like we're entering a loop where the calldata is copied byte-per-byte until max-depth is reached. For reference here is the function:

```
  function forward(address callee, bytes _data) public {
    require(callee.delegatecall(_data));
  }
```

**Comment by norhh** [comment]
@b-mueller we can close this right? Now it takes around 13s to finish

**Comment by b-mueller** [comment]
Yep, can close long ago!
