### ISSUE TITLE
Create a loop pruning search strategy

### ISSUE THREAD

**Issue by b-mueller** [ConsenSys/mythril#1050]
## Description

Add a search strategy that adds sensible bounds on loops so that laser doesn't get caught up in executing them. See also #1048.

**Comment by norhh** [comment]
If we have a CFG, then we can have this as a loop pruning plugin right?(can be used for any strategy) As CFG would also be useful for TOD.

**Comment by b-mueller** [comment]
> If we have a CFG, then we can have this as a loop pruning plugin right?(can be used for any strategy) As CFG would also be useful for TOD.

We do have a CFG, but I implementing proper loop pruning based on analysis of the CFG is not that trivial... for now I'd say we go with the simplest possible solution?

**Comment by norhh** [comment]
`We do have a CFG` what we have is more like a symbolic execution graph than a CFG
