### ISSUE TITLE
What is 'exception in tactic canceled' ? 

### ISSUE THREAD

**Issue by SunBeomSo** [ConsenSys/mythril#1051]
## Description
While testing the contract in:
https://etherscan.io/address/0x0fe086d9c14c47cdbced9f0c6648b706fe3b2527#code

I encountered message below. Did Mythril really complete the analysis successfully? What is 'exception in tactic canceled' ?

```
exception in tactic canceled
exception in tactic canceled
exception in tactic canceled
exception in tactic canceled
exception in tactic canceled
exception in tactic canceled
exception in tactic canceled
exception in tactic canceled
exception in tactic canceled
exception in tactic canceled
exception in tactic canceled
exception in tactic canceled
exception in tactic canceled
exception in tactic canceled
exception in tactic canceled
The analysis was completed successfully. No issues were detected.
```

## Environment

- Mythril version: output from  0.20.4
- Solidity compiler and version: 0.4.25
- Python version: Python 3.6.7
- OS and Version: Ubuntu 18.04.2

**Comment by norhh** [comment]
Hi @SunBeomSo , was the timeout set too low? Yes the analysis was completed successfully, those are the internal Z3 error messages, Z3 is an SMT solver which mythril uses.

**Comment by SunBeomSo** [comment]
@norhh sorry for the missing information.

My timeout was 30 minutes (i.e., 1800s):
```
docker exec -it DOCKERIMAGEID myth --execution-timeout 1800 -x /home/test.sol:HashnodeTestCoin -m integer,exceptions
```

But I found that using default option (which I don't know how long is the default timeout) also produces the same message.
```
myth -x test.sol
```
(I have just tried the command above inside the docker)

**Comment by norhh** [comment]
There are some internal Z3 messages which can be safely ignored, so it should be fine.

**Comment by SunBeomSo** [comment]
@norhh thanks for the answer. I close the issue.
