### ISSUE TITLE
Failure to detect MUL overflow in BECToken with EFFECTS_CHECK enabled

### ISSUE THREAD

**Issue by b-mueller** [ConsenSys/mythril#1069]
## Description

The `MUL` overflow in BECToken is not detect when `EFFECTS_CHECK` is enabled in the integer overflow module.

## How to Reproduce

- Check out #1067  
- Run Mythril on [BECToken](https://github.com/SmartContractSecurity/SWC-registry/tree/master/test_cases/solidity/real_world_samples/BECToken)

The false negative is caused by the end state not being solvable. It appears to boil down to the code in line 263:

`balances[_receivers[i]] = balances[_receivers[i]].add(_value);`

Mythril reports the overflow when this line is commented out:

```
  function batchTransfer(address[] _receivers, uint256 _value) public whenNotPaused returns (bool) {
    uint cnt = _receivers.length;
    uint256 amount = uint256(cnt) * _value;
    require(cnt > 0 && cnt <= 20);
    require(_value > 0 && balances[msg.sender] >= amount);

    balances[msg.sender] = balances[msg.sender].sub(amount);
    
    for (uint i = 0; i < cnt; i++) {

        // balances[_receivers[i]] = balances[_receivers[i]].add(_value);
        Transfer(msg.sender, _receivers[i], _value);
    }

    return true;
  }
}
```

## Expected behavior

Mythril should report exactly 1 MUL overflow. 

## Environment

- Mythril version:  #1067
- Solidity compiler and version: 0.4.25

**Comment by b-mueller** [comment]
Additional info:

Full bytecode of BECToken:

https://gist.github.com/b-mueller/626d853cec54df944aa09b4c42e39417

Bytecode of BECToken w/ line 263 commented out:

https://gist.github.com/b-mueller/0acd9de7aaa6c978662a60a670794311

**Comment by norhh** [comment]
One problem is the symbolic calldata size for calldatacopy, we are just adding 1 variable for it, which might create problems if we are expecting an array in calldata, I just hardcoded 200 as the size(8 bits, so it's reasonable), atleast it doesn't point to 0 but there is another problem which should be figured out :disappointed:
