### ISSUE TITLE
Enable configurable `solc --allow-paths` to accomodate non-standard imports

### ISSUE THREAD

**Issue by maurelian** [ConsenSys/mythril#107]
The `--truffle` mode is unpleasant to work with, as it creates a huge amount of output. Source mappings are currently also much better when first applied to solidity files. 

A more flexible option would be to create a config file like `.mythrilrc`, which would allow me to specify path mappings, similar to `solc --allow-paths`.

**Comment by b-mueller** [comment]
As a workaround, you can use the `--solc-args` argument to pass additional arguments to solc.

**Comment by maurelian** [comment]
oh nice.

**Comment by maurelian** [comment]
How would  I structure the command if I need to remap two paths?

ie. in my env I've set two path re-mappings named `ZEPPELIN` and `TF`. 

Solc handles this fine: `$ solc $ZEPPELIN $TF Sale.sol`

But if I need to import two path re-mappings, this gives `Input file not found`: 
`myth -x --solc-args $ZEPPELIN $TF Sale.sol`

**Comment by b-mueller** [comment]
Does it work if you quote the solc-args? 

```
myth -x --solc-args "$ZEPPELIN $TF" Sale.sol
```

**Comment by maurelian** [comment]
Yes it does. 🌮

**Comment by maurelian** [comment]
Assuming there is still interest in this being used as part of the dev process, rather than just auditing, I think a config file would be much better. That would simplify IDE integrations, and align with tools like linters, truffle, and scripting via NPM.

**Comment by b-mueller** [comment]
For developers, mythril-cli will be superseded by mythjs, so I'll make this part of the mythjs specs.
