### ISSUE TITLE
Unchecked send bug

### ISSUE THREAD

**Issue by MiaZmy1221** [ConsenSys/mythril#1075]
I was trying to execute unchecked send module on some smart contracts, but this error happended  when I did this. 

* Command: myth -m unchecked_retval -x -f 0x27af9309f68a2499b21b5d9428b6ee6f42e9a539.txt --verbose-report

* Smart contract address: 0x27af9309f68a2499b21b5d9428b6ee6f42e9a539 

* Output: b'The analysis was completed successfully. No issues were detected.\n\n' Wrong: b'mythril.mythril.mythril_analyzer [CRITICAL]: Exception occurred, aborting analysis. Please report this issue to the Mythril GitHub page.\nTraceback (most recent call last):\n  File "/home/zhang.834/myth-env/lib/python3.6/site-packages/mythril/mythril/mythril_analyzer.py", line 147, in fire_lasers\n    enable_iprof=self.enable_iprof,\n  File "/home/zhang.834/myth-env/lib/python3.6/site-packages/mythril/analysis/symbolic.py", line 120, in __init__\n    self.laser.sym_exec(world_state=world_state, target_address=address.value)\n  File "/home/zhang.834/myth-env/lib/python3.6/site-packages/mythril/laser/ethereum/svm.py", line 139, in sym_exec\n    self._execute_transactions(symbol_factory.BitVecVal(target_address, 256))\n  File "/home/zhang.834/myth-env/lib/python3.6/site-packages/mythril/laser/ethereum/svm.py", line 191, in _execute_transactions\n    execute_message_call(self, address)\n  File "/home/zhang.834/myth-env/lib/python3.6/site-packages/mythril/laser/ethereum/transaction/symbolic.py", line 67, in execute_message_call\n    laser_evm.exec()\n  File "/home/zhang.834/myth-env/lib/python3.6/site-packages/mythril/laser/ethereum/svm.py", line 221, in exec\n    new_states, op_code = self.execute_state(global_state)\n  File "/home/zhang.834/myth-env/lib/python3.6/site-packages/mythril/laser/ethereum/svm.py", line 260, in execute_state\n    hook(global_state)\n  File "/home/zhang.834/myth-env/lib/python3.6/site-packages/mythril/laser/ethereum/plugins/implementations/coverage/coverage_plugin.py", line 66, in execute_state_hook\n    self.coverage[code][1][global_state.mstate.pc] = True\nIndexError: list assignment index out of range\n\n'

Thank you.

**Comment by norhh** [comment]
@MiaZmy1221 thanks for the report, we will look into it.

**Comment by norhh** [comment]
The smart contract is self destructed, its code is non existent,  thats the reason

**Comment by MiaZmy1221** [comment]
Thank you so much. Add I also encounters another problem. 
Its bytecode is 0x7f6004600c60003960046000f3600035ff00000000000000000000000000000000600052602060006000f061280060008073c72c3ebd888ac1970a8712fef74a1f9b9beecad33c60285b80516c0100000000000000000000000090047366726f6d7368616e67686169776974686c6f7665901860005260008060208180866006f1506014015a60901061004957.

Problem:
Hash: 0xc8076631de834e83bc487bfa7ab642b810955d55 Time: 0.6911792755126953 Output: b'The analysis was completed successfully. No issues were detected.\n\n' Wrong: b'mythril.mythril.mythril_analyzer [CRITICAL]: Exception occurred, aborting analysis. Please report this issue to the Mythril GitHub page.\nTraceback (most recent call last):\n  File "/home/zhang.834/myth-env/lib/python3.6/site-packages/mythril/mythril/mythril_analyzer.py", line 147, in fire_lasers\n    enable_iprof=self.enable_iprof,\n  File "/home/zhang.834/myth-env/lib/python3.6/site-packages/mythril/analysis/symbolic.py", line 108, in __init__\n    creation_code=contract.creation_code, contract_name=contract.name\n  File "/home/zhang.834/myth-env/lib/python3.6/site-packages/mythril/laser/ethereum/svm.py", line 144, in sym_exec\n    self, creation_code, contract_name\n  File "/home/zhang.834/myth-env/lib/python3.6/site-packages/mythril/laser/ethereum/transaction/symbolic.py", line 113, in execute_contract_creation\n    laser_evm.exec(True)\n  File "/home/zhang.834/myth-env/lib/python3.6/site-packages/mythril/laser/ethereum/svm.py", line 230, in exec\n    self.manage_cfg(op_code, new_states)\n  File "/home/zhang.834/myth-env/lib/python3.6/site-packages/mythril/laser/ethereum/svm.py", line 389, in manage_cfg\n    state, JumpType.CONDITIONAL, state.mstate.constraints[-1]\n  File "/home/zhang.834/myth-env/lib/python3.6/site-packages/mythril/laser/ethereum/svm.py", line 435, in _new_node_state\n    address = state.environment.code.instruction_list[state.mstate.pc]["address"]\nIndexError: list index out of range\n\n'

Thank you so much.

**Comment by norhh** [comment]
This issue should be fixed now.
