### ISSUE TITLE
--init-db will hang around the 1000 contract mark

### ISSUE THREAD

**Issue by gaasedelen** [ConsenSys/mythril#110]
## Overview

Within the past few releases, the `--init-db` command will hang / fail to progress around the ~1000 unique contract mark.  

Expected behavior: Mythril will continue to scan and build the contract database to completion.
Actual Result: Mythril begins to slow before hanging, around ~1000 unique contracts.

## Remarks 

This only seems to happen when generating a new database / from scratch. It also seems to be a recent regression, possibly a deadlock with the recent addition of threading. I was able to build a database prior to the multiprocessing work.

Re-running `--init-db` with an already fully built database does not seem to reproduce this issue. 

I use a local, fully sync'd ETH node (geth 1.8.3).

## Repro

1. Delete any existitng mythril database, eg `rm -rf ~/.mythril/`
2. Run mythril and try to enumerate the database. `myth --init-db --rpc localhost:8545`
3. mythril should hang around the ~1000 unique contract mark. Probably coincidence, but it seems consistent.

Platform: Ubuntu 16.04 server, 8 cores, 8gb RAM + 8gb Swap

**Comment by b-mueller** [comment]
Should be resolved in Mythril 0.16.1.

**Comment by gaasedelen** [comment]
Confirming that this issue appears to be resolved. Thanks!
