### ISSUE TITLE
Print initial state as part of the transaction sequence

### ISSUE THREAD

**Issue by nbanmp** [ConsenSys/mythril#1158]
Update the jinja template to print the initial state with the transaction sequence. (`transaction_sequence.initialState`)

This should probably include the addresses of the creator/attacker/other accounts, and their starting values and nonces.

If it is too verbose, perhaps we could check the log level or add another flag.

**Comment by e-ngo** [comment]
https://github.com/ConsenSys/mythril/pull/1173
