### ISSUE TITLE
CircleCI build fails

### ISSUE THREAD

**Issue by b-mueller** [ConsenSys/mythril#116]
CircleCI build fails after merging #114 from @JoranHonig, which fixed a bug in `report_test.py` (`output_expected` had been compared to `output_expected` instead of `output_current`).

The failure is likely due a difference in to the `solc` version installed in the CircleCI image, which causes bytecode generated from Solidity files to differ slightly. It is likely that updating `solc` to 0.4.21 fixes the issue.

@birdofpreyru, as I'm not sure how to update the image, can you please look into that?

**Comment by birdofpreyru** [comment]
@b-mueller I have re-generated the image, it now includes `solc:amd64 v0.4.21`, but it does not fix the failing tests.

**Comment by b-mueller** [comment]
That was quick, thanks. I'll look into it.

**Comment by birdofpreyru** [comment]
@b-mueller as I understand from the log, these tests are kind of snapshot tests, that compare operation output to the expected one. There is instruction in https://github.com/ConsenSys/mythril/blob/master/README_DEV.md on how to update the expected outputs, so, I guess, you just have to manually check, whether the output difference make sense to you, and update them; or look for related bugs, otherwise.

**Comment by b-mueller** [comment]
Yes, that's how it's supposed to work, however some of the tests weren't working as expected before (the expected output was compared with itself). I'll try to reproduce this manually and check the outputs.

**Comment by birdofpreyru** [comment]
Hmm... but two failing tests are fixed now, I see. Probably, you still missed some outputs to update?

**Comment by b-mueller** [comment]
Hmm just checked again, but it seems all outputs are updated (and all tests pass locally now).

**Comment by birdofpreyru** [comment]
Still failing in Circle CI? Do these test depend on some specific number of blocks in the database? Right now the test Docker image does full sync for 10 minutes during the build, thus it has only initial blocks on board, which can fail tests that depend on blocks with higher numbers.

**Comment by b-mueller** [comment]
> Do these test depend on some specific number of blocks in the database?

No, that shouldn't be an issue.There's differences in the disassembly and call graphs generated from source. I still suspect that the problem is `solc` creating slightly different byte-code (even if it's the same compiler version but a different build) so that some PC addresses in the output differ.

**Comment by b-mueller** [comment]
I'm currently preparing a new refactoring & bug fixing package for TopCoder, does it make sense to include this issue?

**Comment by birdofpreyru** [comment]
Sure! Do you know that in addition to running a regular challenge, where we ask a competitor to fix all issues included into the scope, we can also run a Bug Bash kind of challenge? It works great, if we have a code repo(s) with a bunch of smaller issues, not much related to each other. Then we can assign some small payment to each of the issues, and allow community members to pick-up and resolve individual issues for the proposed prize.

**Comment by b-mueller** [comment]
That's cool, any type of challenge is fine for me. I'll list the tasks and leave the decision to you if that's OK?

**Comment by birdofpreyru** [comment]
Great!
