### ISSUE TITLE
Dynamic loader does not retrieve map items

### ISSUE THREAD

**Issue by b-mueller** [ConsenSys/mythril#1176]
## Description

Mythril on-chain analysis is unable to dynamically retrieve the content of map items from the blockchain, resulting in false positives.

## How to Reproduce

Run Mythril on an instance of [Ethernaut Fallback](https://ethernaut.openzeppelin.com/level/0x234094aac85628444a82dae0396c680974260be7).

```console
$ myth analyze --rpc infura-ropsten -a 0x2ffc88679871e212aacbd7222900023315299b54
==== Unprotected Ether Withdrawal ====
SWC ID: 105
Severity: High
Contract: 0x2ffc88679871e212aacbd7222900023315299b54
Function name: fallback
PC address: 475
Estimated Gas Usage: 1467 - 2408
Anyone can withdraw ETH from the contract account.
Arbitrary senders other than the contract creator can withdraw ETH from the contract account without previously having sent an equivalent amount of ETH to it. This is likely to be a vulnerability.
--------------------
Transaction Sequence:

Caller: [ATTACKER], function: contribute(), txdata: 0xd7bb99ba, value: 0x1
Caller: [ATTACKER], function: withdraw(), txdata: 0x3ccfd60b, value: 0x0
```

This should return an issue reachable in 3 transactions but not in 2. Apparently, Mythril does not consider that `contributions[msg.sender] = 1000 * (1 ether)`.

## Expected behavior

Should return no results with -t2 and the correct result with -t3 e.g.

```
Transaction Sequence:

Caller: [ATTACKER], function: contribute(), txdata: 0xd7bb99ba, value: 0x1
Caller: [ATTACKER], function: fallback, txdata: , value: 0x0
Caller: [ATTACKER], function: withdraw(), txdata: 0x3ccfd60b, value: 0x0
```

**Comment by palkeo** [comment]
Haha, I actually stumbled independently on that same bug.

I have a "fix", but as my understanding of the storage is pretty limited, it likely will break other things.

Leaving it here just in case: in account.py, class Storage, method __getitem__, in the condition, replace "value.value == 0" by "not value.value".

**Comment by palkeo** [comment]
Actually maybe my fix is correct. PR opened.

**Comment by b-mueller** [comment]
The false positive was fixed with  #1178. Unfortunately we're not detecting the issues at all now:

```
$ $MYTH analyze -mether_thief --rpc localhost:8545 -a 0x169fa8d8a900f32d956f7599abbfde72b015dd46 -t3
The analysis was completed successfully. No issues were detected.

```

I confirmed that the owner address is now loaded from storage, but the `ether_thief` module never gets called for some reason (and it's not caused by the dependency pruning module).

**Comment by b-mueller** [comment]
@nbanmp do you have time to have a look at this as well? It might be solved by #1172 or at least related to it. And I need to get it working ahead of DEFCON 😅

**Comment by palkeo** [comment]
Beware: my fix is apparently to broad, and after writing to storage (for a simple key, not for a map, though), the next time you read it it will be overwritten by another read from the dynamic loader. I'll try to come up with a better fix.

**Comment by palkeo** [comment]
I feel like the way it knows whether to retrieve storage is wrong. If I understand correctly here it would retrieve the storage again if it was reset to 0, no ? (for normal storage, not map items).

I think the correct solution would be to track what storage keys have been initialized (either retrieved from the blockchain or set previously). If we are reading a storage key that is not initialized we retrieve it and mark it as initialized.
Maybe I will try to come up with a PR to implement that.

**Comment by b-mueller** [comment]
Can be closed, thanks @palkeo!
