### ISSUE TITLE
Unable to register mythx account

### ISSUE THREAD

**Issue by xf97** [ConsenSys/mythril#1206]
Hello, I am a researcher from China. I want to analyze some smart contracts through mythril. Unfortunately, I couldn't register for a mythx account. I entered the correct mailbox and subscribed to the update message, but the registration function was never available. When I use Amazon Cloud, the registration interface always prompts "There was a error, please retry". How can I register my mythx account? I noticed that many functions of mythril depend on this account. I look forward to your reply.

**Comment by norhh** [comment]
Hi @xf97, I think mythril doesn’t need registration to run, if you have problems with MythX registration post the query on discord, it will be resolved quickly.

**Comment by nbanmp** [comment]
Closing, as the question is unrelated to Mythril itself.
