### ISSUE TITLE
Batch Operation: Analyze Contracts

### ISSUE THREAD

**Issue by jaylagorio** [ConsenSys/mythril#121]
In the *Blockchain Exploration* section, it states "Mythril builds its own contract database to enable fast search operations. This enables operations like those described in the legendary "Mitch Brenner" blog post in seconds minutes instead of days."

I'd like to do batch analysis on the contracts contained in the database, generating output on each contract analyzed for later review. Does this functionality exist for use once the database is built?

**Comment by b-mueller** [comment]
It does. To initialize a search, you run:

```
contract_storage.search(args.search, searchCallback)
```

`searchCallback` is a callback function executed for every contract found, so you should be able to use that for batch operations (check the [myth](https://github.com/ConsenSys/mythril/blob/master/myth) source code for an example).

Unfortunately there are currently some issues with the db sync. We're also adding a feature for accessing the state trie of a local go-ethereum node directly, eliminating the need to sync. Hopefully this will all be sorted out in the coming weeks.

**Comment by jaylagorio** [comment]
@JoranHonig @b-mueller You're both right. I do want to pull all the contracts down, and subsequently, I want to run an analysis on all (or a subset) of those contracts and have them stored in a DB or an output file or whatever. I know it'll be time-consuming no matter which way it gets implemented but I'm OK with that.

I'll revisit later when your db sync stuff is worked out, thanks for this awesome project!

**Comment by b-mueller** [comment]
>  thanks for this awesome project!
Thanks for calling it "awesome"!

The db stuff should be worked out in v0.16.1, so you --init-db should now successfully build the contract database. You can run then use the search callback as mentions to run analysis, or simply iterate over the contracts in the database:

```
import os
from mythril.ether.contractstorage import get_persistent_storage

mythril_dir = os.path.join(os.path.expanduser('~'), ".mythril")

contract_storage, _ = get_persistent_storage(mythril_dir)
contracts = contract_storage.contracts

keys = list(contracts)

for k in keys:

   contract = contracts[k]

   # Do some analysis and save the results

```

There is no feature for saving results to a database though, so'd you'd have to implement that yourself.

**Comment by b-mueller** [comment]
Hi @jaylagorio, I assume that this issue is resolved with the latest updates to db sync, so I'm closing it (feel free to comment you still experience any issues).

**Comment by jaylagorio** [comment]
I think it is, thank you!
