### ISSUE TITLE
Confused with solc version

### ISSUE THREAD

**Issue by MountainTrap** [ConsenSys/mythril#1217]
**I want to use mythirl to test a given contract with any solidity version.**
I look at the doc and found that  --solv can change the specified solidity complier version，but then I find --solv is using py-solc which only can install following version to /root/.py-solc:
``` v0.4.1, v0.4.11, v0.4.12, v0.4.13, v0.4.14, v0.4.15, v0.4.16, v0.4.17, v0.4.18, v0.4.19, v0.4.2, v0.4.20, v0.4.21, v0.4.22, v0.4.23, v0.4.24, v0.4.25, v0.4.6, v0.4.7, v0.4.8, v0.4.9```
and the py-solc looks like not maintained.
So How do I use myth with specified solidity compiler，if I use myth directly
```
myth a call.sol
```
it will use the solc in system right?
So I need to check the contract version in the first line and change my system solc everytime(and I need to install all the version), is it the rightway or is there is a better practice. is there a easy way to chang my system solc(I found a package crytic/solc-select)?

I am very confused， thanks for your help!!

**Comment by norhh** [comment]
Hi @MountainTrap , I didn't check solc-select, but one way would be to have the latest version of solc installed and for analysis just change the pragma by adding a ^(don't forget to revert it after the analysis is done if it wasn't intended), In nearly all cases the analysis results wouldn't change with that difference at the moment. This only works for versions >= 0.5.0 , in other cases you can just use --solc arg,
Another easier way is to try out mythx truffle plugin https://docs.mythx.io/en/latest/tools/truffle/ , it detects more vulnerabilities than mythril(it also uses mythril) and doesn't have this problem.

**Comment by nbanmp** [comment]
This has been resolved, the `--solc` argument will now also work with compiler versions greater than 0.5.0.
