### ISSUE TITLE
Implement transaction order dependence

### ISSUE THREAD

**Issue by JoranHonig** [ConsenSys/mythril#122]
Transaction order independence has been described [here](https://consensys.github.io/smart-contract-best-practices/known_attacks/#transaction-ordering-dependence-tod-front-running). 

Making Smart Contracts Smarter - Loi Luu et al. describes a way to detect this. It would be cool if mythril could detect these vulnerabilities.

**Comment by b-mueller** [comment]
It seems likely that as a prerequisite, we need to be able to model multiple transactions first?

Which section in the paper are you referring too? Browsing it quickly I saw references to transaction order issues and guarded transactions for preventing them, but no detection methods.

**Comment by JoranHonig** [comment]
@b-mueller Section 5.2 near the end. 

Regarding modeling multiple transactions. I don't think so, you need to check all money flows and see if this can be influenced by the state of the contract (either the direction of the flow, or the amount). 

So the implementation of this issue would need to determine all possible money flows, and I don't think you need to model multiple transactions for that

**Comment by JoranHonig** [comment]
I'll probably pick this up somewhere next week

**Comment by JoranHonig** [comment]
I currently have a working version: https://github.com/JoranHonig/mythril/blob/features/tod/mythril/analysis/modules/transaction_order_independence.py
It correctly finds a TOD bug in calls.sol:
```
==== Transaction order dependence ====
Type: Warning
Contract: Caller
Function name: callstoredaddress()
PC address: 779
A possible transaction order independence vulnerability exists in function callstoredaddress(). The value or direction of the call statement is determined from a tainted storage location
--------------------
In file: /home/walker/dev/mythril/tests/testdata/input_contracts/calls.sol:29

stored_address.call()

--------------------
```

**Comment by JoranHonig** [comment]
This method is not sound but should be complete. 
To get it to have less false positives we would need to develop a system which is able to assert the reachability of constraints given multiple consecutive runs of a contract.

**Comment by b-mueller** [comment]
Thanks Joran, I'll review this tomorrow!
