### ISSUE TITLE
Templating for report graph

### ISSUE THREAD

**Issue by joshuata** [ConsenSys/mythril#123]
In `mythril/analysis/callgraph.py:252` it states that you would be interested in using a templating system. I would be interested in quickly converting it to use jinja. Would that be an acceptable dependency to add to the program in your view?

**Comment by b-mueller** [comment]
For sure! I don't see a reason not to add it.

**Comment by joshuata** [comment]
Great! I'm about halfway through an initial implementation. I've been seeing some issues with rendering the final graph that I will open if I can reproduce them.

**Comment by b-mueller** [comment]
Cool! Don't forget to include some awesome default templates :)
