### ISSUE TITLE
Feature request: please use https://github.com/vinayps/cs205_project instead of pysha3!

### ISSUE THREAD

**Issue by ytrezq** [ConsenSys/mythril#1259]
Not only this would be faster, but this would be the last step to have mythril compatible with pypy because pysha3 is incompatible with pypy.

Both are unmaintained though.

**Comment by norhh** [comment]
I don’t think pysha3 is extensively being used, it’s better to use hashlib over these

**Comment by ytrezq** [comment]
@norhh ported Pysha3 to pypy along vectorizing it with avx512 support. And guess what? mythx run 7 to 20 times faster.

**Comment by ytrezq** [comment]
Ok. Whatsover, I used the official latest binary (7.2.0) of PyPy, so the only libraries required are the ones for running the official PyPy binaries.
The remaining works standalone.

The target cpu has pretty much all latest avx512 features enabled so this won’t run old cores.

Just extract [this archive](http://ytrezq.sdfeu.org/binaries/pypy3.6-v7.2.0-linux64.tar.xz) to `/usr/lib64` (though paths aren’t static) it also contains the patched version of sha3 .(the provided binary doesn’t use the loop at all). For the purpose of benchmarking, `vmprof` is also included in the archive.
then run `myth` using pypy3 where both file are in the `/bin` directory within the archive.

**Comment by norhh** [comment]
The current version on Mythril significantly spends time in solver calls(>95%), so this can be closed.
