### ISSUE TITLE
Myth anaylise crash in the z3 solver when using this contract.

### ISSUE THREAD

**Issue by ytrezq** [ConsenSys/mythril#1262]
I don’t know why but the latest mythril version available on pip running on the official Python implementation crash when using this command.

    myth -v 4 analyze --rpc infura-mainnet --enable-coverage-strategy -a 0xd1d5e97d8baadd3b383442ba6f2903ca1349f89a -l --max-depth 160

**Comment by norhh** [comment]
Can you put in the stack trace of the error?

**Comment by ytrezq** [comment]
@norhh not the full stack trace. But it’s a pure python error.

If you launch the command, you should get the stack trance in about 10 minutes maximum.

**Comment by ytrezq** [comment]
@norhh Cpython 3.7 (the official package of CentOS 7)

**Comment by ytrezq** [comment]
Ok, I updated mythril from last week and it’s gone. Sorry.
