### ISSUE TITLE
Add detailed per-OS installation instructions

### ISSUE THREAD

**Issue by paulkeogh** [ConsenSys/mythril#129]
I had to install libssl-dev on ubuntu 16.04.3 LTS (Xenial Xerus);

sudo apt-get install libssl-dev

before I could successfully execute;

pip3 install mythril

I think this should be added to the README

**Comment by b-mueller** [comment]
Thanks @paulkeogh! That's good to know, I'm just worried about cluttering the README.md to much if we include per-OS in installation instructions (also, looking at the [Dockerfile](https://github.com/ConsenSys/mythril/blob/master/Dockerfile) it seems you need install various other packages as well).

I'm thinking about setting up a INSTALL.md for this, would you like to contribute?

**Comment by paulkeogh** [comment]
Yes, of course.

**Comment by b-mueller** [comment]
Awesome :)

I'll leave this issue open until we have detailed installation instructions.

**Comment by joshuata** [comment]
I think leveraging the Pipfile work I have been doing in #132 might help make sure that versions are locked correctly. This is not related to system packages directly, but it should clean up some of the small inconsistencies between builds, especially with docker.

**Comment by JoranHonig** [comment]
The github wiki feature is also a good place for this. It won't be included in the repository, but it would provide an easily structurable and extendable place for information like installation instructions.

**Comment by b-mueller** [comment]
You're right, the Wiki would be better place for documentation.
