### ISSUE TITLE
Update documentation (vulnerabilities)

### ISSUE THREAD

**Issue by Danc2050** [ConsenSys/mythril#1291]
## Description
Update the [Vulnerabilities wiki](https://github.com/ConsenSys/mythril/wiki/Vulnerabilities) and [readthedocs](hhttps://mythril-classic.readthedocs.io/en/master/analysis-modules.html/) to account for two new vulnerabilites:
1. Write to an arbitrary storage slot
2. Use of callcode

These are the only new vulnerabilities I've noticed mythril has added -- there may be more.

**Edit/Note**
If one has their cache not cleared, the old page will show, not the updated one.

**Comment by norhh** [comment]
Thanks for the info, The wiki is actually Deprecated. I have updated them in https://mythril-classic.readthedocs.io/en/master
