### ISSUE TITLE
imprecise line indicator

### ISSUE THREAD

**Issue by SunBeomSo** [ConsenSys/mythril#1299]
## Description

Line information in analysis results is imprecise.

For example, for ``mythril/solidity_examples/suicide.sol``, Mythril reports line 5 is vulnerable,  but the problematic line is 7. 

## How to Reproduce
Assuming Mythril's Docker container is running and the file to be analyzed is in `/tmp/`` directory of the container, my command was:
```
sudo docker exec CONTAINER_NAME myth analyze /tmp/suicide.sol
```

## Environment
I tested using the latest version of Docker image (v.0.21.20).
- Mythril version: v.0.21.20 
- OS and Version: Ubuntu 18.04.2 (Host)

**Comment by norhh** [comment]
@SunBeomSo It seems to work fine for me, can you check whether your file was altered any way. Also can you mention whether you are using the docker-dev container or the standard one?

**Comment by SunBeomSo** [comment]
@norhh 
I am really sorry for my mistake. I tested the code after removing top two lines (blanks).

However, I sometimes encounter imprecise line information when analyzing other contracts using Mythril.

Here is a concrete example contract:
https://etherscan.io/address/0x13873a43694f039d18107afeac917aff6bc4fa96#code

My command was:
```
sudo docker exec CONTAINER_NAME myth analyze /tmp/FILE_NAME.sol:ERC20_ICO --execution-timeout 600 --solv 0.4.24
```

then Mythril outputs a following alarm (similarly, I removed top four blanks in the contract for testing).  However, as you can see, ``address[] public investorlist`` is not an ``assert`` statement. 

```
==== Exception State ====
SWC ID: 110
Severity: Low
Contract: ERC20_ICO
Function name: investorlist(uint256)
PC address: 3725
Estimated Gas Usage: 944 - 1039
A reachable exception has been detected.
It is possible to trigger an exception (opcode 0xfe). Exceptions can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. Note that explicit `assert()` should only be used to check invariants. Use `require()` for regular input checking.
--------------------
In file: /tmp/2018-13536.sol:244

address[] public investorlist

--------------------
Initial State:

Account: [CREATOR], balance: 0x1, nonce:0, storage:{}
Account: [ATTACKER], balance: 0x0, nonce:0, storage:{}
Account: [SOMEGUY], balance: 0x0, nonce:0, storage:{}

Transaction Sequence:

Caller: [CREATOR], data: [CONTRACT_CREATION], value: 0x0
Caller: [CREATOR], function: investorlist(uint256), txdata: 0xc6f7b7eb, value: 0x0
```



 > Also can you mention whether you are using the docker-dev container or the standard one?

I am not sure what the docker-dev container is. I obtained image via ``docker pull mythril/myth`` command.

**Comment by norhh** [comment]
Actually it's possible to access a public array of a smart contract, in that case a call with an out of bounds index would cause an assertion failure, It's just a false positive.

**Comment by SunBeomSo** [comment]
@norhh  If my understanding is correct, I think Mythril should have pinpointed the following statement:
```
investorlist.push(receiver) -1 // line 274 in the link above
```
because this statement is the only one that accesses elements of the array ``investorlist``.

``address[] public investorlist`` is just a declaration statement.

**Comment by norhh** [comment]
It is true positive in the sense of triggering an exception. By false positive I mean it is not a security vulnerability and nothing is wrong anywhere.

**Comment by SunBeomSo** [comment]
Thanks, I close the issue.
