### ISSUE TITLE
Flaky Test

### ISSUE THREAD

**Issue by JoranHonig** [ConsenSys/mythril#130]
# Description
Reports_test.py performs analysis on a set of contracts.
Some of the tests fail sometimes on the following contract: rubixy.sol

The following Issue is often not found:
```
        {
            "title": "Ether send",
            "description": "In the function `'_function_0xb4022950'` a non-zero amount of Ether is sent to an address taken from storage slot 5.\nThere is a check on storage index 5. This storage slot can be written to by calling the function '_function_0x67f809e9'.\n\nThere is a check on storage index 5. This storage slot can be written to by calling the function '_function_0x67f809e9'.\nThere is a check on storage index 1. This storage slot can be written to by calling the function 'fallback'.\nThere is a check on storage index 1. This storage slot can be written to by calling the function 'fallback'.",
            "function": "_function_0xb4022950",
            "type": "Warning",
            "address": 2582,
            "debug": "<DEBUG-DATA>"
        }
```

# Reproduction
If you want to reproduce the issue then you can either run the tests locally for a while. Or use circleci cli (command is ran from the project root, note that you also need to edit the config a little bit):
```
circleci build --job test -c .circleci/config.yml
```

**Comment by b-mueller** [comment]
I have experienced a similar issue with Rubixi where the PC address shown in the report differed for different runs. Are you sure that the issue is not found at all, or could it be that the issue output is different?

**Comment by JoranHonig** [comment]
The problem is that it sometimes does not report this issue at all.

**Comment by JoranHonig** [comment]
This is probably caused by mythril.analysis.solver.get_model(constraints), due to the timeout. I'll play around with this
