### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Danc2050** [ConsenSys/mythril#1300]
**The problem**
The contract `0x8717105257cd617d5DD73265cfe17771eEbE1fBb` returns an IndexError in mythril.

**To reproduce**
`docker run --rm mythril/myth -v4 analyze -1 -a 0x8717105257cd617d5DD73265cfe17771eEbE1fBb --execution-timeout 3600`

**Comment by norhh** [comment]
I put in a PR for this fix with something else, It's still in review. Will just patch this up for now.

**Comment by MCPCapital** [comment]
Just want to say I am still seeing this error on a number of contracts.
