### ISSUE TITLE
False positive input

### ISSUE THREAD

**Issue by SunBeomSo** [ConsenSys/mythril#1316]
## Description
Mythril seems to produce a false positive input.

## How to Reproduce
Testing file:
```
contract Test{
  uint n;

  constructor (uint _n) public {
    require (_n==1);
    n = _n;
  }

  function test (uint8 a, uint[] memory b) public {
    require (a==10);
    n--;
  }
}
```

Command:
```
sudo docker exec CONTAINER_NAME myth analyze /tmp/test.sol --solv 0.5.12 -m integer,exceptions -o json
```

Output:
```
{'error': None,
 'issues': [{'address': 274,
             'code': 'n--',
             'contract': 'Test',
             'description': 'The binary subtraction can underflow.\n'
                            'The operands of the subtraction operation are not '
                            'sufficiently constrained. The subtraction could '
                            'therefore result in an integer underflow. Prevent '
                            'the underflow by checking inputs or ensure sure '
                            'that the underflow is caught by an assertion.',
             'filename': '/tmp/test.sol',
             'function': 'test(uint8,uint256[])',
             'lineno': 11,
             'max_gas_used': 28829,
             'min_gas_used': 6052,
             'severity': 'High',
             'sourceMap': ':3',
             'swc-id': '101',
             'title': 'Integer Underflow',
             'tx_sequence': {'initialState': {'accounts': {'0x901d12ebe1b195e5aa8748e62bd7734ae19b51f': {'balance': '0x100000000000',
                                                                                                         'code': '608060405234801561001057600080fd5b506004361061002b5760003560e01c806382668f2014610030575b600080fd5b6100f36004803603604081101561004657600080fd5b81019080803560ff1690602001909291908035906020019064010000000081111561007057600080fd5b82018360208201111561008257600080fd5b803590602001918460208302840111640100000000831117156100a457600080fd5b919080806020026020016040519081016040528093929190818152602001838360200280828437600081840152601f19601f8201169050808301925050505050505091929192905050506100f5565b005b600a8260ff161461010557600080fd5b600080815480929190600190039190505550505056fea265627a7a72315820bb01cda6ba4124fde44870a05970c0990509bdf9da47ca0bc0a3f8d8be43907c64736f6c634300050c0032',
                                                                                                         'nonce': 0,
                                                                                                         'storage': '{}'},
                                                           '0xaffeaffeaffeaffeaffeaffeaffeaffeaffeaffe': {'balance': '0x40080000080009',
                                                                                                          'code': '',
                                                                                                          'nonce': 0,
                                                                                                          'storage': '{}'},
                                                           '0xdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef': {'balance': '0x0',
                                                                                                          'code': '',
                                                                                                          'nonce': 0,
                                                                                                          'storage': '{}'}}},
                             'steps': [{'address': '',
                                        'calldata': '00000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
                                        'input': '0x608060405234801561001057600080fd5b506040516101b83803806101b88339818101604052602081101561003357600080fd5b81019080805190602001909291905050506001811461005157600080fd5b8060008190555050610150806100686000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c806382668f2014610030575b600080fd5b6100f36004803603604081101561004657600080fd5b81019080803560ff1690602001909291908035906020019064010000000081111561007057600080fd5b82018360208201111561008257600080fd5b803590602001918460208302840111640100000000831117156100a457600080fd5b919080806020026020016040519081016040528093929190818152602001838360200280828437600081840152601f19601f8201169050808301925050505050505091929192905050506100f5565b005b600a8260ff161461010557600080fd5b600080815480929190600190039190505550505056fea265627a7a72315820bb01cda6ba4124fde44870a05970c0990509bdf9da47ca0bc0a3f8d8be43907c64736f6c634300050c003200000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
                                        'name': 'unknown',
                                        'origin': '0xaffeaffeaffeaffeaffeaffeaffeaffeaffeaffe',
                                        'value': '0x0'},
                                       {'address': '0x901d12ebe1b195e5aa8748e62bd7734ae19b51f',
                                        'calldata': '0x82668f20000000000000000000000000000000000000000000000000000000000000000a00000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000000',
                                        'input': '0x82668f20000000000000000000000000000000000000000000000000000000000000000a00000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000000',
                                        'name': 'test(uint8,uint256[])',
                                        'origin': '0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
                                        'value': '0x0'},
                                       {'address': '0x901d12ebe1b195e5aa8748e62bd7734ae19b51f',
                                        'calldata': '0x82668f20000000000000000000000000000000000000000000000000000000000000000a00000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000000',
                                        'input': '0x82668f20000000000000000000000000000000000000000000000000000000000000000a00000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000000',
                                        'name': 'test(uint8,uint256[])',
                                        'origin': '0xaffeaffeaffeaffeaffeaffeaffeaffeaffeaffe',
                                        'value': '0x0'}]}}],
 'success': True}
```

## Expected behavior
As you can see, the argument of the constructor must be ``1`` to be deployed. However, the decoded constructor argument value in Mythril's output is ``0``. Clearly, the contract cannot be deployed with this argument value.

I used the abi decoder in here: https://github.com/miguelmota/ethereum-input-data-decoder

Could you check if the generated input  is false positive (i.e., the input cannot reproduce underflow behavior)?

## Environment

- Mythril version: v 0.21.21 (from docker image)
- Solidity compiler and version:  0.5.12
- Python version: 3.6.9 (the one installed in the docker container)
- OS and Version: Ubuntu 18.04 (Host OS)

**Comment by SunBeomSo** [comment]
In addition, I wonder the difference between ``address`` and ``origin`` in the report.

**Comment by norhh** [comment]
There should be some changes in the output method of Mythril.
for creation transaction the call data field is pointless, as the execution is EVM style  which means input = `creation_bytecode + constructor args` so the arguments are appended to the `input` field, we can see the `n_ = 1` there.

**Comment by norhh** [comment]
origin means the person who initiated the transaction. If someone executes a contract which calls another contract then the caller for this other contract transaction is the first contract, but the origin is the address of the guy who executed the 1st contract

**Comment by SunBeomSo** [comment]
@norhh 

Thanks for your quick answers.

> for creation transaction the call data field is pointless, as the execution is EVM style which means input = creation_bytecode + constructor args so the arguments are appended to the input field,

Where is the ``creation_bytecode`` in the report?

> we can see the n_ = 1 there.

Is it possible to find out ``n_ = 1`` by looking at the report above?

**Comment by norhh** [comment]
The input field for the first transaction.
`input=0x608060405234801561001057600080fd5b506040516101b83803806101b88339818101604052602081101561003357600080fd5b81019080805190602001909291905050506001811461005157600080fd5b8060008190555050610150806100686000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c806382668f2014610030575b600080fd5b6100f36004803603604081101561004657600080fd5b81019080803560ff1690602001909291908035906020019064010000000081111561007057600080fd5b82018360208201111561008257600080fd5b803590602001918460208302840111640100000000831117156100a457600080fd5b919080806020026020016040519081016040528093929190818152602001838360200280828437600081840152601f19601f8201169050808301925050505050505091929192905050506100f5565b005b600a8260ff161461010557600080fd5b600080815480929190600190039190505550505056fea265627a7a72315820bb01cda6ba4124fde44870a05970c0990509bdf9da47ca0bc0a3f8d8be43907c64736f6c634300050c003200000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000`
which is str(bytecode) + str(calldata)

**Comment by SunBeomSo** [comment]
@norhh 

> origin means the person who initiated the transaction. 

Thank you for explaining that.

Then what does ``address`` field mean?

I also wonder if I can know the addresses of the deployed contract (i.e., the address of ``this``) and the transaction message sender (i.e., the addresses of ``msg.sender``).

**Comment by norhh** [comment]
`address` is the address of the contract on which the tx is executed
`I also wonder if I can know the addresses of the deployed contract (i.e., the address of this) and the transaction message sender (i.e., the addresses of msg.sender).` For that the analysis should be run on an address. But mythril would emulate a msg.sender while trying to analyze a deployed contract.

**Comment by SunBeomSo** [comment]
@norhh 

Sorry for bothering you, but it is still hard for me to understand the analysis result. 

> But mythril would emulate a msg.sender while trying to analyze a deployed contract.

What do you mean by ``emulate a msg.sender``?


===============================================

> address is the address of the contract on which the tx is executed

Then isn't ``address`` simply the address of ``this``? 
In the report, the address ``0x901d12ebe1b195e5aa8748e62bd7734ae19b51f`` has the non-empty ``code`` value, so I guess that means ``address`` is the ``this``.

**Comment by norhh** [comment]
`Then isn't address simply the address of this?` Yes.
`What do you mean by emulate a msg.sender?` Probably I misunderstood your question, so nevermind that comment.
`Sorry for bothering you, but it is still hard for me to understand the analysis result.` Remove the `-o json` option and you will see a more human-readable output.(The creation code is removed from the input there)
the input field for creation tx is `creation_bytecode + constructor args`, as that's how EVM takes.

**Comment by SunBeomSo** [comment]
@norhh 

> Remove the -o json option and you will see a more human-readable output.(The creation code is removed from the input there)

Now I got 
```
00000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
```
where lots of 0s are padded after 1. But the example contract above has only one input parameter. Is it an valid input?

**Comment by norhh** [comment]
From the bytecode execution perspective, it's valid. As the EVM code just asks for the needed args so whatever the rest is, it's not ignored while execution.

**Comment by SunBeomSo** [comment]
@norhh It seems I need to investigate more, thank you very much!
