### ISSUE TITLE
Produces errors for --solv 0.4.16, 0.4.17

### ISSUE THREAD

**Issue by SunBeomSo** [ConsenSys/mythril#1318]
## Description

Mythril produces errors with options ``--solv 0.4.16`` or ``--solv 0.4.17``.
But I checked that Mythril successfully analyze the contract with ``--solv 0.4.25``  for the same contract (please refer to below). 

## How to Reproduce
Testing contract which can be compiled with solc 0.4.17 (or 0.4.16) :
```
pragma solidity ^0.4.17; // or 0.4.16

contract Test{
  uint n;

  function Test (uint _n) public {
    require (_n==1);
    n = _n;
  }

  function test (uint8 a, uint[] memory b) public {
    require (a==10);
    n--;
  }
}
```

Command :
```
sudo docker exec CONTAINER_NAME myth analyze /tmp/test.sol --execution-timeout 300 -o test --solv 0.4.17 -m integer,exceptions
```

Error message from Mythril:
```
mythril.interfaces.cli [ERROR]: Solc experienced a fatal error.

Cannot import url ("/tmp/test.sol"): File outside of allowed directories. 
```

However, if I replace 0.4.17 by 0.4.25 in the command, Mythril successfully analyze the contract.

## Expected behavior
Mythril should not produce error messages, because the original contract can be compiled with solc 0.4.17.

## Environment

- Mythril version: v 0.21.21 (from docker image)
- Solidity compiler and version:  0.5.12
- Python version: 3.6.9 (the one installed in the docker container)
- OS and Version: Ubuntu 18.04 (Host OS)

**Comment by norhh** [comment]
It's a problem with `py-solc` which is out of our hand.

**Comment by SunBeomSo** [comment]
Thanks for the answer.
