### ISSUE TITLE
Infura IPC / RPC error: 403

### ISSUE THREAD

**Issue by Danc2050** [ConsenSys/mythril#1333]
Whenever I run Myth currently, in Docker or through the CLI, I get this error: `mythril.interfaces.cli [ERROR]: IPC / RPC error: 403`.

Could Mythril's Open Source API key hit its maximum limit for the month/quarter?

**Comment by b-mueller** [comment]
Mythril doesn't even have an API key. The code is still from when read-only calls to Infura were unrestricted 🙃

**Comment by b-mueller** [comment]
Not that this doesn't need a fix... we'll have to add an option for users to configure an Infura account at some point. What's your solution, are you running your own node?

**Comment by Danc2050** [comment]
A solution would be great, but I'm not in desperate need of a solution ATM as my project with Mythril is in limbo as I finish up school/finals.

I was just using the read-only mode, which is a bummer that Infura made that decision. I wonder if my project influenced their decision in any way :sweat_smile:. A line in `~/.mythril/config.ini` or another implementation to make use of Infura's 100,000 requests per day would be nice.

If its not fixed and I'm really hurting for Mythril results, I could try and setup the configuration to match with my free key. I also have short-term access to a GETH node via Google Cloud that I could maybe hookup to Mythril with the potential to maybe also make a query to that machine remotely if I opened up a port and worked out the programming logic :man_shrugging:.

**Comment by b-mueller** [comment]
> I wonder if my project influenced their decision in any way 😅

Probably not, Infura becoming more restrictive was a long time coming 🙂

If you figure out a good way to re-enable Infura we're also happy about a pull request. We'll probably look into it ourselves at some point currently on-chain analysis is not a top priority..

**Comment by b-mueller** [comment]
The PR is reviewed but unfortunately our CI pipeline is currently not working. It might take some time until this makes it into a release.

**Comment by Danc2050** [comment]
Super cool though! I'll just download the `develop` branch and recompile Myth as a binary if necessary. Thank you for keeping me in the loop :pray: .

**Comment by Danc2050** [comment]
Sorry to resurrect this, but I have a small question.

is all Infura is used for, when calling out to an address at least, is getting the bytecode of an address? I am just wondering as setting up a GETH node and opening a port may be cheaper than signing up for an Infura account...even having a CDN on DigitalOcean that contained all the bytecodes from some address would be relatively simple to have and maintain.

**Comment by norhh** [comment]
Infura is used to bring out the code for address and also for accessing onchain storage(If you want to use onchain storage for analysis, by default it's on)

**Comment by enderphan94** [comment]
@norhh the projec-id is the infura-id, right? Thanks

**Comment by norhh** [comment]
@enderphan94 If you mean infura's key then it's used as `infura-id` by mythril.

**Comment by enderphan94** [comment]
@norhh , exactly. I'm looking for the id to work on. I got the same error though

**Comment by norhh** [comment]
@enderphan94 , You should get the infura-id through https://infura.io and use it. Since it is tedious to maintain a node to go through the blockchain mythril uses infura JSON rpc for its ease. You can also start your own node and use it's respective endpoint instead on infura but it's better to use infura over a node.

**Comment by enderphan94** [comment]
@norhh thanks, that's why I was asking if the project-id is the infura-id in this case. It does have project-id and secret-id, so I'm confused which one is the right one to put in.

**Comment by norhh** [comment]
@enderphan94 yes it should be the `project-id`
