### ISSUE TITLE
NoneType error: when analyzing a contract by address and no filename exists to concatenate

### ISSUE THREAD

**Issue by LoCorVin** [ConsenSys/mythril#134]
myth -xia 0x61edcdf5bb737adffe5043706e7c5bb1f1a56eea
Traceback (most recent call last):
  ...
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.15.8-py3.6.egg/mythril/analysis/report.py", line 95, in as_markdown
    text += "# Analysis results for " + issue.filename
TypeError: must be str, not None Type

**Comment by joshuata** [comment]
I can handle this since I have rewritten the report system to use the new templating system

**Comment by b-mueller** [comment]
Fixed on 0.16.31.
