### ISSUE TITLE
A math overflow is not reported 

### ISSUE THREAD

**Issue by askyst** [ConsenSys/mythril#1349]
## Description

When I use mythril to scan  HumanStandardToken.sol  (https://github.com/ConsenSys/Token-Factory/blob/master/contracts/StandardToken.sol), it seems an obvious overflow is not reported. The contract function is :

  function transfer(address _to, uint256 _value) returns (bool success) {
        //Default assumes totalSupply can't be over max (2^256 - 1).
        //If your token leaves out totalSupply and can issue more tokens as time goes on, you need to check if it doesn't wrap.
        //Replace the if with this one instead.
        //if (balances[msg.sender] >= _value && balances[_to] + _value > balances[_to]) {
        if (balances[msg.sender] >= _value && _value > 0) {
            balances[msg.sender] -= _value;
            balances[_to] += _value;   ////  here is the overflow
            Transfer(msg.sender, _to, _value);
            return true;
        } else { return false; }
    }

I have read several related issues (like [this one](https://github.com/ConsenSys/mythril/issues/931)). I'm not sure if it is mythril's problem since I wrote some little wrapper code to run mythril.  

So here is the question: Can above overflow be detected by mythril?

## How to Reproduce
just run the analysis:
$ myth a xxx.sol

## Expected behavior

there should be an overflow, I think...

## Environment

running mythril 0.21.21 on debian linux

**Comment by b-mueller** [comment]
Hi @askyst, an integer overflow can't happen here because the no to issue tokens and all balances are 0. Mythril should detect an overflow if you add a minting function and allow for more than max_int tokens to be minted (but you'll probably also need to add `-t4` or `-t5` because multiple steps would be needed to reach the overflow.

**Comment by askyst** [comment]
Thanks, I think I understand what you say.

**Comment by b-mueller** [comment]
Awesome 🙂
