### ISSUE TITLE
zsh: command not found myth

### ISSUE THREAD

**Issue by anhdungle93** [ConsenSys/mythril#1374]
I installed mythril with pip3 install mythril even the command pip3 show mythril showed that the package already exists
`Name: mythril

Version: 0.22.4

Summary: Security analysis tool for Ethereum smart contracts

Home-page: https://github.com/ConsenSys/mythril

Author: ConsenSys Dilligence

Author-email: None

License: MIT

Location: /Users/anhdungle/Library/Python/3.7/lib/python/site-packages

Requires: ethereum, plyvel, eth-account, transaction, persistent, ethereum-input-decoder, py-solc-x, mock, eth-rlp, z3-solver, eth-keys, eth-typing, matplotlib, py-flags, coloredlogs, semantic-version, rlp, py-evm, eth-keyfile, jinja2, requests, pythx, eth-tester, py-solc, eth-hash, configparser, coverage, eth-abi, py-ecc

Required-by:`

But running myth analyze <contract_name> gives:
zsh: command not found: myth
Thanks for helping

**Comment by norhh** [comment]
probably `myth` executable file isn't in the $PATH. Can you locate it and add it to the $PATH?

**Comment by anhdungle93** [comment]
Where can I find it? I tried to add </Users/anhdungle/Library/Python/3.7/lib/python/site-packages> to <$PATH> but to no avail.

**Comment by norhh** [comment]
@anhdungle93 it's a bit tricky to find, but anyway better way is to create a virtual environment and install mythril there, it shouldn't take more than a minute or two. https://packaging.python.org/guides/installing-using-pip-and-virtual-environments/

**Comment by anhdungle93** [comment]
thank you, I didn't use virtual environment but managed to run mythril in docker without problem instead.
