### ISSUE TITLE
Wiki Wrong

### ISSUE THREAD

**Issue by cclabsInc** [ConsenSys/mythril#1376]
Looks like the wiki for the most part is incorrect as the options don't exist anymore for stuff like creating graphs or command line options like -x or ether thief.. Might be nice to update that to reflect the current features. 
Please correct me if I am wrong.. but that has been the experience I am currently having where the wiki is not reflecting the current release usage.

**Comment by norhh** [comment]
We have migrated from wiki to readthedocs  https://mythril-classic.readthedocs.io/en/master/about.html . So we will be removing the wiki. Thanks for the info.
