### ISSUE TITLE
Mythril doesn't find errors in killbilly.sol

### ISSUE THREAD

**Issue by lukwue** [ConsenSys/mythril#1379]
Hello,

I have installed mythril and used it to test the killbilly.sol contract from the README example and somehow it didn't detect any errors.
```
myth analyze  --solv 0.5.7 killbilly.sol
solc, the solidity compiler commandline interface
Version: 0.5.7+commit.6da8b019.Linux.g++
The analysis was completed successfully. No issues were detected.
```

Installed versions:
`mythril`: v0.22.4
`solc`: 0.6.7+commit.b8d736ae.Linux.g++
`evm`: evm version 1.9.13-stable-cbc4ac26

**Comment by norhh** [comment]
Try using `-t 3` option as this requires 3 transactions.

**Comment by lukwue** [comment]
Thank you, that worked :)
