### ISSUE TITLE
obtain coverage data a contract in a solidity file having multiple contracts

### ISSUE THREAD

**Issue by Qiana0223** [ConsenSys/mythril#1383]
## Description

How to get the coverage data for a specified contract in a solidity file with multiple contracts

## Background

Mythril has a plugin which can provide coverage data. So, by using the command: myth -v4 analyze name.sol &> name.log,  the coverage data of contracts are captured in name.log.
The problem is that how to identify which contract the coverage data belong to. Is there any way to help identify or is there any other way to get the coverage data for a specified contract?

**Comment by Qiana0223** [comment]
Here is the solidity file, HoloToken.sol, from which I want to get the coverage data of contract HoloToken.  
In the log file, there are various places showing coverage data. But there is litle information to show which contract they belong to.
![image](https://user-images.githubusercontent.com/32651102/81889629-9d37b580-9569-11ea-85fa-e94a602afccd.png)
![image](https://user-images.githubusercontent.com/32651102/81889653-afb1ef00-9569-11ea-9ebb-98af9d960965.png)

attached are the relevant solidity file and the log file
[HoloToken.sol.txt](https://github.com/ConsenSys/mythril/files/4625923/HoloToken.sol.txt)
[HoloToken.log](https://github.com/ConsenSys/mythril/files/4625924/HoloToken.log)

**Comment by norhh** [comment]
Try something like `myth -v4 analyze name.sol:ContractName` for the contract coverage.

**Comment by JackHFeng** [comment]
@norhh Thank you so much for providing us with this information! Do you know how is the code coverage computed? Is it computed by dividing the total number of covered instructions with the total number of instructions in the runtime bytecode?

**Comment by norhh** [comment]
yes

**Comment by Qiana0223** [comment]
Thank you!
