### ISSUE TITLE
What is the input for the Analysis module?

### ISSUE THREAD

**Issue by JackHFeng** [ConsenSys/mythril#1384]
## Description
Hello, I am a PhD student working on fuzzing smart contracts. We were wondering if it is possible for us to reuse the detectors that are implemented in Mythril? 
What is the input for the detectors? Is it the debug trace of a transaction? If that is not enough, what else is needed?

**Comment by norhh** [comment]
I don't think it's possible to do as analysis modules assume that mythril's VM is being run.Analysis modules take a GlobalState as input which contains information like constraints, environment, EVM machine state, some custom annotations, ....

**Comment by JackHFeng** [comment]
Thank you!
