### ISSUE TITLE
Is generating graph still available?

### ISSUE THREAD

**Issue by JackHFeng** [ConsenSys/mythril#1385]
## Description
I tried to generate control flow graph of a contract using `myth -g ./graph.html ./contract.sol`
But was getting an error saying `invalid choice './graph.html'`
The `-h `option also does not list there's a `-g` option. Is generating a control flow graph still allowed? Or has it been removed?

**Comment by norhh** [comment]
It should be something like `myth a -g ./graph.html ./contract.sol`

**Comment by JackHFeng** [comment]
Thank you!
