### ISSUE TITLE
two types of error messages from mythril

### ISSUE THREAD

**Issue by Qiana0223** [ConsenSys/mythril#1386]
## Description
when running  mythril to analyze solidity files, there are **two type of error messages**:
**command format:** myth -v 4 analyze name.sol: contractName
**error message 1:**
![image](https://user-images.githubusercontent.com/32651102/82154984-423ae280-9837-11ea-84bf-12ba2ad6b90c.png)

**error message 2:**
![image](https://user-images.githubusercontent.com/32651102/82154988-46ff9680-9837-11ea-881d-3ba099012c22.png)

Could you explain what error messages mean? 
What factors cause these problems?
is there anyway to solve them?

Thanks

**Comment by norhh** [comment]
Thanks for the report. Are you running mythril in parallel? that may be the problem with the second error and also probably with the first error. If you are running it in parallel then run it using the docker container so there will be a separate signature.db file for each run.

**Comment by Qiana0223** [comment]
Thanks!

**Comment by Qiana0223** [comment]
Hi Norhh,

The second type of error still here!

I just use the command: myth analyze solidity_file_name. There is no parallel running.  this  second type of error still shows up. 
![image](https://user-images.githubusercontent.com/32651102/86387417-bf3fe100-bc58-11ea-9e2a-45b59a927c95.png)

Also, I run it in a docker container, it still has issue with 0 coverage. 

I guess, there maybe some other factors like compiler version?

Thanks!

**Comment by JoranHonig** [comment]
Seems like this is resolved, closing it 🙌
