### ISSUE TITLE
Read mapping elements

### ISSUE THREAD

**Issue by thec00n** [ConsenSys/mythril#139]
It be great if `mythril` could read mapping values. So read from `keccak256(k . p)` where `k` is the index and `p` is the storage slot.  Something like `myth --rpc infura-rinkeby  --storage mapping,0,"lol","rofl" -a 0x3e03e13bc8de9dfa5df8d9237cda582fbd0433f7 `

```
//0x3e03e13bc8de9dfa5df8d9237cda582fbd0433f7
contract Mapping{
    mapping (bytes32 => address) public apps;   

    function Mapping(){
        apps['lol'] = 0xd850636636e82a0e7ea6951650b69b8e3243dadb;
        apps['rofl'] = 0xd850636636e82a0e7ea6951650b69b8e3243dadc;

    }
}    
```

**Comment by adolia** [comment]
@b-mueller 
Hi!
Could you please clarify, so for now we have --storage INDEX,NUM_SLOTS,[array] option. So should we extend existed option with mapping argument in order to print mapped values?
Thanks in advance!

**Comment by thec00n** [comment]
It be great to have the following either added to Mythril or refactored:

Read statically-sized variables based on their storage slots:
`/myth --rpc infura-rinkeby --storage simple_type,postion,length -a <address>`

Read dynamic arrays based on their storage slot `p`  so  `array[keccak256(p)]`:
`./myth --rpc infura-rinkeby --storage array,postion,length -a <address>`

Read mappings based on their key `k` and storage slot `p` so `mapping[keccak256(k . p)]`
`./myth --rpc infura-rinkeby --storage mapping,postion,key -a <address>`

More info can be found here:
http://solidity.readthedocs.io/en/v0.4.21/miscellaneous.html#layout-of-state-variables-in-storage

**Comment by b-mueller** [comment]
@adolia, yes, exactly. 

Perhaps we could also simplify this by making it `a` and `m` instead of spelling out the whole word.

**Comment by N1k1tung** [comment]
@b-mueller I assume adding `./myth --rpc infura-rinkeby --storage mapping,INDEX,KEY1[,KEY2..] -a <address>` to be an available option along with current implementation (`./myth --rpc infura-rinkeby --storage INDEX,NUM_SLOTS,[array] -a <address>`) should be considered fine as this was the original scope of the ticket?

**Comment by b-mueller** [comment]
@N1k1tung yeah, something along those lines should be fine. I would say though for consistency, `arrray` and `mapping` should be at the start of the argument.

```
$ myth --rpc infura-rinkeby --storage mapping,INDEX,KEY1[,KEY2..]  -a <address>
$ myth --rpc infura-rinkeby --storage array,INDEX,NUM_SLOTS -a <address>
``

Or abbreviated:

```
$ myth --rpc infura-rinkeby --storage m,INDEX,KEY1[,KEY2..]  -a <address>
$ myth --rpc infura-rinkeby --storage a,INDEX,NUM_SLOTS -a <address>
```

**Comment by birdofpreyru** [comment]
Done in v0.16.26
