### ISSUE TITLE
What does EtherThief module actually detect?

### ISSUE THREAD

**Issue by anhdungle93** [ConsenSys/mythril#1395]
The following description is from here https://mythril-classic.readthedocs.io/en/master/_modules/mythril/analysis/modules/ether_thief.html#EtherThief.reset_module

```
Search for cases where Ether can be withdrawn to a user-specified address.

An issue is reported if:

- The transaction sender does not match contract creator;
- The sender address can be chosen arbitrarily;
- The receiver address is identical to the sender address;
- The sender can withdraw *more* than the total amount they sent over all transactions.
```
The third condition suggests that the EtherThief module would be triggered for every contract which lets users deposit and withdraw, which does not make much sense. Can someone explain more? Thanks.

**Comment by norhh** [comment]
It's a logical And of all the conditions. 
`And(sender != creator, sender==some_random_addr, receiver ==sender, total money sender gets > total amount he sends over all his previous transactions)`

**Comment by anhdungle93** [comment]
thank you.
