### ISSUE TITLE
Pip always reports Mythril v0.15.8 being installed

### ISSUE THREAD

**Issue by b-mueller** [ConsenSys/mythril#140]
While current versions of Mythril can be successfully installed with pip, the reported version is always 0.15.8. 

Ubuntu 16.04:

```
$ sudo -H pip3 uninstall -y laser-ethereum mythril; sudo -H pip3 install -U mythril==0.16.4
Uninstalling mythril-0.15.8:
  Successfully uninstalled mythril-0.15.8
Uninstalling laser-ethereum-0.16.0:
  Successfully uninstalled laser-ethereum-0.16.0
Collecting mythril==0.16.4
Requirement not upgraded as not directly required: eth-tester>=0.1.0b21 in /usr/local/lib/python3.5/dist-packages (from mythril==0.16.4) (0.1.0b23)
Requirement not upgraded as not directly required: eth-keyfile>=0.5.1 in /usr/local/lib/python3.5/dist-packages (from mythril==0.16.4) (0.5.1)
(...)
Installing collected packages: laser-ethereum, mythril
Successfully installed laser-ethereum-0.16.0 mythril-0.15.8
$ pip3 search mythril
mythril (0.16.4)  - Security analysis tool for Ethereum smart contracts
  INSTALLED: 0.15.8
  LATEST:    0.16.4
```

Mac OS High Sierra with Mythril 0.16.6 installed:

```
$ pip search mythril
mythril (0.16.6)  - Security analysis tool for Ethereum smart contracts
  INSTALLED: 0.15.8
  LATEST:    0.16.6
```

A likely cause of this is the version definiton in setup.py:

```
    version=os.getenv('CIRCLE_TAG', 'v0.15.8')[1:],
```

**Comment by chronaeon** [comment]
Reproducible on my Ubuntu 17.10 machine.

```
$ pip3 search mythril
mythril (0.16.6)  - Security analysis tool for Ethereum smart contracts
  INSTALLED: 0.15.8
  LATEST:    0.16.6
```

Changed the version in `setup.py` from `0.15.8` to `0.28.8` thinking I could force an error:
`version=os.getenv('CIRCLE_TAG', 'v0.28.8')[1:],`
and re-installed, but still shows `0.15.8` as installed.

**Comment by birdofpreyru** [comment]
@b-mueller my bad: getting version from Git tag, without asking to update it in `setup.py` was a wrong idea.

I have merged in the fix, and added deployment instructions into `README_DEV.md`. Now, to re-deploy it is necessary to update `VERSION` in `setup.py`, and then create and push a Git tag with the same name. In case of mismatch between `VERSION` and Git tag name the deployment is cancelled (failed).

The same update is merged into `laser-ethereum` repo.

**Comment by b-mueller** [comment]
Well it did seem like a good idea at the time, was nice not having to update setup.py.

Thanks for the fix.

**Comment by b-mueller** [comment]
Behaviour is normal again starting from v0.16.21.
