### ISSUE TITLE
'Arbitrary Storage Write' detector

### ISSUE THREAD

**Issue by SunBeomSo** [ConsenSys/mythril#1407]
**[1]** What kinds of bugs does ``Arbitrary Storage Write`` module aim to detect? 

Specifically, what constraints are checked by Mythril for this module? Some storage variables are allowed to be written by anyone.

**[2]** In addition, I wonder why Mythril does not raise an alarm for the below example. Is it an intended behavior?

```
contract Test {
  address  owner; 
  function test(address newOwner) public {
    owner = newOwner;
  }
}
```

My command was: 
```
docker run --rm -v /tmp:/tmp:ro mythril/myth:0.22.1 a /tmp/test.sol -m ArbitraryStorage
```

**Comment by norhh** [comment]
Arbitrary Storage in Mythril write detects whether the attacker has the ability to write to a random storage slot number(which might mean the attacker has the ability to write to many storage slots and can overwrite sensitive data). For more information you can look into the example here https://swcregistry.io/docs/SWC-124 .

**Comment by SunBeomSo** [comment]
@norhh Thanks for the response.

>  attacker has the ability to write to many storage slots and can overwrite sensitive data

=> What are "sensitive data" considered by Mythril?

Why is the the variable ``owner`` in my example (please see [2]) not considered to be "sensitive" by Mythril?

I have read the document in https://swcregistry.io/docs/SWC-124 . But still, the definition of "sensitive" is not clear for me. The term "sensitive" seems to be subjective one.

**Comment by norhh** [comment]
EVM has storage slots ranging from 0 to 2**256 -1, and all the variables are in these slots. Mythril checks whether an attacker can write to some random storage slot (like slot number `keccak_256(32487328687568585985645734867984376982376)`). If attacker can write to that slot then the attacker can write to most of the storage in the contract which is what mythril detects as SWC-124.
In your case the attacker can only write to the owner which is slot 0 but doesn't have the ability to write to any other slot, so it doesn't detect it as Arbitrary Storage Write
