### ISSUE TITLE
the uncertainty of the bytecode used in coverage-calculation by coverage_plugin.py 

### ISSUE THREAD

**Issue by Qiana0223** [ConsenSys/mythril#1408]
Hi developer,

How are you?

I want to get the mythril-coverage of a conract in terminal with command: **myth -v4 analyze solidity_file_name:contract_name**.

I assume that the **bytecode** used by coverage_plugin.py is the **runtime bytecode** of the specified contract.
But this assumption is **not always true**. 

There is a case: 
    the runtime bytecode  has 2490 opcodes
     but the byecode used by coveage_plugin.py to calculate  coverage  can have 3333 opcodes.
     [xDOT.txt](https://github.com/ConsenSys/mythril/files/4914263/xDOT.txt)
 so the coveage of the contract obtained by coverage_plugin.py seems to have sth I missed.

In some rare case, the bytecode used by coverage_plugin.py is neither creation_bytecode nor runtime_bytecode.
[SolidifiedDepositableFactory.txt](https://github.com/ConsenSys/mythril/files/4914274/SolidifiedDepositableFactory.txt)

Therefore, I am wondering what kind of bytecode is used by coverage_plugin.py? 

**Note**, I have changed the **extension** of solidity file from **sol** to **txt** since sol files are not allowed to be submitted here!

**Comment by norhh** [comment]
`In some rare case, the bytecode used by coverage_plugin.py is neither creation_bytecode nor runtime_bytecode.` In the example mythril showed three bytecodes, one was creation bytecode(constructor code + runtime code), other was runtime and the other was the parent contract bytecode.

The coverage plugin displays coverage of both the contract code and the runtime code. In some cases some `STOP`s or `STOP`s followed by `INVALID` might be appended to the end of the contract from solc when running on contract's parents.

**Comment by Qiana0223** [comment]
Thanks Norhh!

Since some STOP and INVALID opcodes would be added to runtime bytecode, does the added opcodes have much impact on the coverage data?

Also, I have checked the xDOT.sol.  I use Disassembly to disassemble the bytecode(with 3333 instructions) copied from terminal, there are only have 2 STOPs and 0 INVALIDs.  So, (3333-2490) instructions should have other instructions, right?

**Comment by norhh** [comment]
I ran it for the xDOT contract on solc 0.5.0 mythril's bytecode matches with that of solc --bin.

**Comment by Qiana0223** [comment]
Oh, I am clear now. the bytecode with 3333 instructions is not the runtime_bytecode, but the creation_bytecode. The terminal only produces the coverage for creation_bytecode in this case. 

Another question, when a contract A creates an instance of contract B,does the bytecode of contract A contains some bytecode of contract B?
Based on my observation, contract A does contains some from contract B, am I right?
If I am right, how I exactly get the coverage for one particular contract?

thanks!

**Comment by norhh** [comment]
`Based on my observation, contract A does contains some from contract B, am I right?` Mostly yes. It might depend on solidity version and other factors(like size). From what I observed if the bytecode is big then the solidity appends the code to some unreachable region so EVM can use codecopy to load it to memory

**Comment by norhh** [comment]
`If I am right, how I exactly get the coverage for one particular contract?` Mythril doesn't have the ability.
You can construct a graph with an opcode as a node and a directed edge between node i and node j if i isn't a terminating opcode and i precedes j or JUMP destination of i is j and some other such cases. The unreachable opcodes will be unreachable from the node 0(1st opcode) in this graph.

**Comment by Qiana0223** [comment]
Thank you!

In **one** case in which only coverage of creation_bytecode is shown, what does **no-runtime_byteocode-coverage** imply? 

In **another** case in which the coverage of **parent's or referenced contract's bytecode,let call x_bytecode** is produced, I have checked the x_bytecode is **neither** creation_bytecode **nor** runtime_bytecode of **parent's or referenced contract**.  what consists of the x_bytecode?

**Comment by norhh** [comment]
`In one case in which only coverage of creation_bytecode is shown, what does no-runtime_byteocode-coverage imply?` That would only happen when the constructor isn't fully executed. When I ran xDot it displayed both the constructor code and runtime bytecode.
`what consists of the x_bytecode?`, Such a case doesn't happen. Mostly it's a slightly mutated version of parent/referenced contract.

**Comment by Qiana0223** [comment]
Thank you!

**Comment by Qiana0223** [comment]
Hi Norhh,

Could you describe why sometimes constructor is not fully executed? or give cases in which constructor is not fully executed?

Bests,
Qiana

**Comment by norhh** [comment]
The creation-timeout may not be enough. You can increase it with command line args.

**Comment by Qiana0223** [comment]
I did that, it does not help.

**Comment by norhh** [comment]
Was an error message like `No contract was created during the execution of contract creation Increase the resources for creation execution ` logged in such cases?(it should be visible when using -v4 option)

**Comment by Qiana0223** [comment]
yes!
Here is what is printed out:
![image](https://user-images.githubusercontent.com/32651102/87691999-d69ac600-c750-11ea-99df-41825e38c77f.png)
![image](https://user-images.githubusercontent.com/32651102/87692038-e914ff80-c750-11ea-958d-99260aaa2bae.png)
.....
![image](https://user-images.githubusercontent.com/32651102/87692106-ffbb5680-c750-11ea-9fda-5c711a083687.png)

**Comment by Qiana0223** [comment]
Here is the *.sol file I used
[spank_chain_payment.txt](https://github.com/ConsenSys/mythril/files/4932772/spank_chain_payment.txt)

**Comment by Qiana0223** [comment]
this is caused by the default value of create-timeout (10 seconds). when it is set to another larger value, everything is ok.
Another question: except the create-timeout, based on your experience, is there any other case in which a constructor can not be fully executed?
Thanks.

**Comment by norhh** [comment]
The other case would be low max-depth, but the default value is quite high so it is rare.

**Comment by Qiana0223** [comment]
thank a lot!

For a specified contract:
I have noticed that often **# of instructions of** runtime_bytecode -1 = **# of elements of src_map**(split by ';'). 

But there is also a case: # of instructions =749, while # of elements =181.  In this case, src_map only maps to a part of source code.  

My question is that **the part which is not mappted** belongs to the **code of another contract** that is referenced by the specified contract?

**Comment by norhh** [comment]
`My question is that the part which is not mappted belongs to the code of another contract that is referenced by the specified contract?` src map usually mapped to the other contract in the cases I have seen. You may probably be comparing src map of runtime code with the creation bytecode.
