### ISSUE TITLE
runtime_bytecode coverage calculation misses a rare case

### ISSUE THREAD

**Issue by Qiana0223** [ConsenSys/mythril#1412]
## Description

There are two contracts in a solidity, let call them A and B. A does not inherit B and B also does not inherit A.
But  A creates an instance of  B in itself.
In this case, the runtime_bytecode of  A includes the creation_bytecode of B.
But in coverage calculation of runtime_bytecode of A, the covered code of B is not considered. Instead, the coverage of covered code of B is given separately based on the code of B and sometimes with a few extra opcodes added. 
As a result, there are 3 types of coverage shown.
![image](https://user-images.githubusercontent.com/32651102/87801418-4d00fc00-c815-11ea-941b-6f4da3c55d3d.png)

This can explain why when there are three types of coverage produced, the coverage of runtime_bytecode of a specified contract is rather low. 

![image](https://user-images.githubusercontent.com/32651102/87802449-dbc24880-c816-11ea-8f11-9909b0dc07c1.png)

Of course, if A inherits B, there is not such issue. Since A's code  contains B's code, and the covered code of B is considered in A's coveage calculation.

My assumption is that if B's code is included in A's code, then the covered code in B should also be considered in coverage calculation of B.

But if this assumption is not correct on Mythril, then, this is not a bug at all.

[SolidifiedDepositableFactory_05.txt](https://github.com/ConsenSys/mythril/files/4938587/SolidifiedDepositableFactory_05.txt)

**Comment by norhh** [comment]
Yes, thats how it works.
When A inherits B then A contains B's code and it is possible to touch the instructions using some calldata.
In case when A creates an instance of B then B's code in A is unreachable as it is bounded by STOP, it's something like 
```
A's code
....
....
....
STOP
INVALID
INVALID
B's code
```
The format  varies depending  on the solidity versions.
The B's code can't be reached from A by any means. This code is only used for being loaded into the memory by CODECOPY opcode and then executing CREATE.

**Comment by Qiana0223** [comment]
Thank you!
In a case of A having an instance of B, B's code is unreachable, **why is the code of B not removed from code of A**?  Does the code of B is included in A by **solc compiler or by Mythril**?

**Comment by norhh** [comment]
It's included by solc.

**Comment by Qiana0223** [comment]
Thanks!
