### ISSUE TITLE
Python 3.6 syntax breaks compatibility with older Python versions

### ISSUE THREAD

**Issue by b-mueller** [ConsenSys/mythril#142]
Recent commits have introduced Python 3.6 syntax elements.

We don't currently require 3.6 explicitly and I think we should maintain compatibility with at least Python 3.5. 

Example:

![error](https://user-images.githubusercontent.com/5194767/39255324-73c2ad2c-48d6-11e8-9c54-adaa499aae39.png)

**Comment by b-mueller** [comment]
@joshuata one of those changes relates to [this commit](https://github.com/ConsenSys/mythril/commit/367a185075c06063e66784cf38143eabf16b2df4#diff-6b2c7ed79bb1e34f183c6b910b64f607). Can we revert to backwards-compatible syntax here?

**Comment by joshuata** [comment]
Absolutely. I read in the README_DEV that python 3.6 was required, so I figured it was alright.

**Comment by joshuata** [comment]
Also, would you like me to set up Tox so that we can test against 3.5 and 3.6 and guarantee compatibility?

**Comment by b-mueller** [comment]
> I read in the README_DEV that python 3.6 was required, so I figured it was alright.

Maybe it's worth having that discussion now? Do you think that the new features are worth requiring 3.6?

**Comment by joshuata** [comment]
It might be worth testing back until python 3.4 since that would support almost every LTS linux distro. I don't see almost any distros that ship 3.5 as the python3 version. So if 3.4 is not possible I don't see any reason to support <= 3.6

Are there any dependencies that you can think of that would not be available on 3.4?

**Comment by b-mueller** [comment]
I don't know to be honest, but testing back until 3.4 sounds like a good idea.

**Comment by b-mueller** [comment]
As a quick fix, I replaced a few lines in `callgraph.py` with traditional format strings. This should fix the crash for now, although I don't have a Python 3.4 environment for testing.
