### ISSUE TITLE
Using with docker return an error - 'NoneType' object has no attribute 'eth_getCode' 

### ISSUE THREAD

**Issue by krasi-georgiev** [ConsenSys/mythril#1422]
Can you add an example of how to use through docker, I am trying with this and get the following error. 

```
docker run --rm -it  mythril/myth analyze -a 0xc2edad668740f1aa35e4d8f227fb8e17dca888cd
mythril.interfaces.cli [ERROR]: IPC / RPC error: 'NoneType' object has no attribute 'eth_getCode' 
```

**Comment by norhh** [comment]
You need to provide infura-id, as the code is loaded from infura.
`docker run --rm -it  mythril/myth analyze -a 0xc2edad668740f1aa35e4d8f227fb8e17dca888cd --infura-id=<infura-id>`
Also for progress you can add `-v4` before the `analyze` command.
This will result in an error when run normally, but doesn't display when run in docker, this should be fixed.

**Comment by krasi-georgiev** [comment]
yep that solved it, thanks
