### ISSUE TITLE
How to get (print) storage data?

### ISSUE THREAD

**Issue by Qiana0223** [ConsenSys/mythril#1423]
Hi developer,

I try to write code to get the detailed information about each instruction in order to understand Mythril much better.

I can get the constraints, values in stack and memory.

But I fail to find a way to get data in storage.

Could you give me hints on how to achieve that?

Thanks, 

Qiping

**Comment by norhh** [comment]
This class has storage data https://github.com/ConsenSys/mythril/blob/c6350150328001a7e2a785ae51d5a28786766e20/mythril/laser/ethereum/state/account.py#L27 . The storage is in the form of an SMT array.

**Comment by Qiana0223** [comment]
Is there any example code to show how to get readable value?

**Comment by norhh** [comment]
You can use self.printable_storage, but it isn't accurate, as store and load values are usually symbolic.

**Comment by Qiana0223** [comment]
Thanks a lot!
