### ISSUE TITLE
--solv throws various errors when not using the docker image, with fix

### ISSUE THREAD

**Issue by jimtje** [ConsenSys/mythril#1424]
## Description

Hey guys. I ran into some issues while using the --solv switch while running the analysis module. Good news is that I have a fix ready for a pull request whenever you guys see fit.

### Errors

The first is that when using --solv, py-solc-x then proceeds to compile, and on MacOS Catalina, if brew runs into any sort of error, it would throw exceptions that doesn't get picked up correctly through the shell scripts and the whole thing simply throws a generic error.

```
mythril.interfaces.cli [ERROR]: Traceback (most recent call last):
  File "/Users/jim/opt/anaconda3/lib/python3.7/site-packages/mythril/interfaces/cli.py", line 842, in parse_args_and_execute
    enable_online_lookup=query_signature,
  File "/Users/jim/opt/anaconda3/lib/python3.7/site-packages/mythril/mythril/mythril_disassembler.py", line 38, in __init__
    self.solc_binary = self._init_solc_binary(solc_version)
  File "/Users/jim/opt/anaconda3/lib/python3.7/site-packages/mythril/mythril/mythril_disassembler.py", line 83, in _init_solc_binary
    solcx.install_solc("v" + version)
  File "/Users/jim/opt/anaconda3/lib/python3.7/site-packages/solcx/install.py", line 204, in install_solc
    _install_solc_osx(version, allow_osx)
  File "/Users/jim/opt/anaconda3/lib/python3.7/site-packages/solcx/install.py", line 312, in _install_solc_osx
    message="Running dependency installation script `install_deps.sh` @ {}".format(temp_path)
  File "/Users/jim/opt/anaconda3/lib/python3.7/site-packages/solcx/install.py", line 232, in _check_subprocess_call
    **proc_kwargs
  File "/Users/jim/opt/anaconda3/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['sh', '/var/folders/db/pxs8v9056zs9sdcgs18wc9m80000gn/T/py-solc-x-tmp/solidity_0.6.10/scripts/install_deps.sh']' returned non-zero exit status 1.
```
I actually don't have a fix for this, mostly because the error is on py-solc-x's end (really it's on the part of the shell script for dependencies on solc's part), but it would be useful, I think, to at least throw it out here if anyone runs into the same problem. Because it's also not at all clear that the issue comes from this matroshka doll of nested installation scripts.

In the process of figuring that out I moved onto an Ubuntu VM and avoided the brew issue, obviously, but ran into this:

```
root@ubuntu:~# myth analyze Test.sol --solv 0.6.12
solc, the solidity compiler commandline interface
Version: 0.6.12+commit.27d51765.Linux.g++
mythril.interfaces.cli [ERROR]: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/mythril/interfaces/cli.py", line 842, in parse_args_and_execute
    enable_online_lookup=query_signature,
  File "/usr/local/lib/python3.6/dist-packages/mythril/mythril/mythril_disassembler.py", line 38, in __init__
    self.solc_binary = self._init_solc_binary(solc_version)
  File "/usr/local/lib/python3.6/dist-packages/mythril/mythril/mythril_disassembler.py", line 95, in _init_solc_binary
    raise solc.exceptions.SolcError()
TypeError: __init__() missing 5 required positional arguments: 'command', 'return_code', 'stdin_data', 'stdout_data', and 'stderr_data'

```

This was just the solc binary not getting picked up properly for some reason. After I fixed the brew issue this also came up on MacOS. 

### The problem

Let me explain: right now the --solv switch will invoke mythril/mythril_disassembler.py and then call the following:

```
   @staticmethod
    def _init_solc_binary(version: str) -> str:
        """
        Only proper versions are supported. No nightlies, commits etc (such as available in remix).
        :param version: Version of the solc binary required
        :return: The solc binary of the corresponding version
        """

        if not version:
            return os.environ.get("SOLC") or "solc"

        # tried converting input to semver, seemed not necessary so just slicing for now
        main_version = solc.main.get_solc_version_string()
        main_version_number = re.match(r"\d+.\d+.\d+", main_version)
        if main_version is None:
            raise CriticalError(
                "Could not extract solc version from string {}".format(main_version)
            )
        if version == main_version_number:
            log.info("Given version matches installed version")
            solc_binary = os.environ.get("SOLC") or "solc"
        else:
            solc_binary = util.solc_exists(version)
            if solc_binary and solc_binary != util.solc_exists(
                "default_ubuntu_version"
            ):
                log.info("Given version is already installed")
            else:
                if version.startswith("0.4"):
                    try:
                        solc.install_solc("v" + version)
                    except solc.exceptions.SolcError:
                        raise CriticalError(
                            "There was an error when trying to install the specified solc version"
                        )
                elif sys.version_info[1] >= 6:
                    # solcx supports python 3.6+
                    try:
                        solcx.install_solc("v" + version)
                    except solcx.exceptions.SolcError:
                        raise CriticalError(
                            "There was an error when trying to install the specified solc version"
                        )
                else:
                    raise CriticalError(
                        "Py-Solc doesn't support 0.5.*. You can switch to python 3.6 which uses solcx."
                    )

                solc_binary = util.solc_exists(version)
                if not solc_binary:
                    raise solc.exceptions.SolcError()

            log.info("Setting the compiler to %s", solc_binary)

        return solc_binary

```

The issue is that basically the scenarios where the proper solc binary will get picked up are:

* if os.environ.get("SOLC") gets the right path
* if no solc is installed on the system, and the code here will install the version required immediately and to the correct system default path
* if it can be picked up by util.solc_exists(version)
```
def solc_exists(version):
    """
    :param version:
    :return:
    """

    solc_binaries = []
    if version.startswith("0.4"):
        solc_binaries = [
            os.path.join(
                os.environ.get("HOME", str(Path.home())),
                ".py-solc/solc-v" + version,
                "bin/solc",
            )  # py-solc setup
        ]
        for solc_path in solc_binaries:
            if os.path.exists(solc_path):
                return solc_path
    elif sys.version_info[1] >= 6:
        # we are using solc-x for the the 0.5 and higher
        try:
            return solcx.install.get_executable(version)
        except SolcNotInstalled:
            pass

    # Last resort is to use the system installation
    default_binary = "/usr/bin/solc"
    if os.path.exists(default_binary):
        return default_binary
```
which would require either py-solc to install a version into the home directory listed, or if the correct path is /usr/bin/solc. That is why using the docker image, the error doesn't come up.

What won't get picked up is if you need multiple versions of solc versions 0.5/0.6/0.7 installed, whether you have installed via brew or if you can't installed to /usr/bin or you already have a version you don't want to use at /usr/bin/solc

Annoyingly py-solc-x doesn't install versions 0.4.2 to 0.4.9, and py-solc doesn't seem to be able to install any version that installs on Catalina (or anything above Sierra). Otherwise py-solc wouldn't be needed at all to install the new binaries. Alas, this covers a fairly large chunk of potential usage, I think.

### The fix

Anyway, in order to fix that, I've simply edited both of those the parts above with something like:

```
            if platform.system() == "Darwin":
                solcx.import_installed_solc()
            installed = solcx.get_installed_solc_versions()
            if "v" + version in installed:
                solcx.set_solc_version("v" + version)
                solc_binary = solcx.install.get_executable()
                return solc_binary
            else:
                available = solcx.get_available_solc_versions()
                if "v" + version in available:
                    solcx.install_solc("v" + version)
                    solcx.set_solc_version("v" + version)
                    solc_binary = solcx.install.get_executable()
                    return solc_binary
```

This way, the correct binary path should always get picked up, as long as it can actually be installed by py-solc-x. Also, bumped py-solc-x version required to 0.10.1 for the features and bugfixes that were introduced.

Tested on Python 3.6, 3.7, and 3.8 on Ubuntu and Catalina, all good. 

### Caveats

What won't work in this case, still is if the required solc version is between 0.4.2 and 0.4.9, and if py-solc doesn't install it to the default directories, or that the version required is between 0.4.2 and 0.4.25 and the version of python available is 3.5.

### Additional thoughts

Since now that solc version management can more or less be automated outside of the caveated areas, it may just make sense to get rid of the --solv switch and read version numbers automatically, handle the solc binary required, and run the analysis without the annoyance of having to specify which version. That would mean that a whole directory of .sol files can then be analyzed automatically without manual intervention. Not sure if that's what you guys had in mind generally or if there are use cases outside of those listed under caveats that wouldn't work though. Should be pretty trivial to put that feature in.

Anyway, hope that wasn't too much. Cheers.

**Comment by norhh** [comment]
Thanks for logging the error and providing the necessary solution. Can you put this in a PR if possible?

**Comment by jimtje** [comment]
Sure
