### ISSUE TITLE
Errors in analyzing a relatively complicated contract

### ISSUE THREAD

**Issue by JoeBlack220** [ConsenSys/mythril#1427]
## Description
Running mythril for a relatively complicated contract. After several hours, it exits because of exceptions. If I set `--execution-time` there will be some output, but it only detects issues with SWC-107 and SWC-113 which I think is not enough.

## How to Reproduce

`myth a SavingAccount.sol:SavingAccount > results/SavingAccountWhole.txt`

## Screenshots

![image](https://user-images.githubusercontent.com/18740962/93946041-1059f100-fced-11ea-8423-da2bebaba973.png)

## Environment
Ubuntu 18.04
solc 0.5.14

**Comment by norhh** [comment]
@JoeBlack220 , this should be fixed now, can you check it with Mythril v0.22.15?
