### ISSUE TITLE
How can I test a byte-code contract file with Mythril?

### ISSUE THREAD

**Issue by lukwue** [ConsenSys/mythril#1431]
Hello,

how can I test a byte-code contract file with Mythril? It should be possible since Mythril can directly analyse a contract from the blockchain. However, unfortunatelly the `README `only shows how to analyse a `.sol` file.

Thanks!

Lukas

**Comment by norhh** [comment]
Hi @lukwue, try `myth a -c <bytecode>`

**Comment by lukwue** [comment]
Thank you!
