### ISSUE TITLE
Mythril vulnerabilities detection

### ISSUE THREAD

**Issue by mstad** [ConsenSys/mythril#1435]
## Description

I am trying to analyze some 0.5.x smart contracts and I see that vulnerabilities detection seems very low, comparing to other tools; moreover, tests are really time-consuming.

## Tests

I used the command:
$ myth analyze filename.sol

It takes normally from 30 minutes to indefinitely (more than one day) for smart contracts that have from 200 to 3000 rows; Very often the reply is that no issue was found. Should I do something different? Could I reduce the scanning-time?
I am using the release 0.22.10.

## Implementation details
I installed Mythril with
pip3 install mythril

**Comment by norhh** [comment]
`vulnerabilities detection seems very low, comparing to other` mythril only detects vulnerabilities which aren't related to linting that most tools detect. It detects vulnerabilities like integer overflows, possibility of ether theft, attacker having capability to write to arbitrary storage location, ... etc these are time consuming to detect. You can reduce the scanning time but it may not be worth it, as symbolic execution is preferable to be run for a few days.

**Comment by mstad** [comment]
My request was made also to be sure that I use Mythril in the correct way and do not miss any important option (like some detectors).  
Thanks for the reply and clarification.
