### ISSUE TITLE
state equality check

### ISSUE THREAD

**Issue by Qiana0223** [ConsenSys/mythril#1441]
Hi developer,

I hope you are doing well!

I have some questions about how Mythril handles states. There is observation that mythril does symbolic transaction on the "same" states.

Here is a smart contract I use as an example.[Crowdsale.txt](https://github.com/ConsenSys/mythril/files/5478681/Crowdsale.txt)

Crowdsale.sol has five functions. among of them, **setOwner, setPhase, invest** can be covered when tranaction-count=1. while  **withdraw and refund** can not be covered because they require state variable phase=1 and 2 respectively.

(When transaction-count=2, **refund** is covered.When transaction-count=3, **withdraw** is covered.)

Based on the **call graph** produced when transaction-count=3, I draw a graph. Each node represents a function(and the state after analyzing the function), and each directed edge means trying to visit/cover the function pointed by the arrow. Green circle means that the function can be covered, while red means not be covered.
For simplicity, I ignore some unnecessary parts.  
![image](https://user-images.githubusercontent.com/32651102/97933349-20c3a980-1d38-11eb-9b4c-7b16703ac647.png)

Let **state A** represents the state produced after analyzing functions **setOwner and invest.**
Let **state B** represents the state produced after analyzing functions **invest and setOwner**.

From my opinion, **state A is equal to state B**.  This can also be proved by looking at the graph. When Mythril reasons  from both State A and State B, it will try to visit all five functions, and three of them are covered.

Suppose there is a mechanism to check the equality of state A and state B, then analyzing on one of these two states shuld be enough.  I think this is a way to reduce state space.

My questions (if there is indeed no state equality check):
     **why Mythril does not have state equality check?**
     **Is there any reason behind that prevents Mythril checking state equality, or would Mythril have some performance issue when checking state equality?**

Bests,
Qiana

**Comment by JoranHonig** [comment]
Hey Qiana,

Determining state equivalence is a non-trivial operation that can become quite expensive (complex SMT queries). 

Especially once you consider that equivalences occur between transaction boundaries as well. E.g. some state C after two transactions might be equal to some state D after four.
The amount of comparisons that you need to make grows very quickly with the amount of discovered states.  

In some cases it would be possible to determine statically that two states must be equal, but not in the general case. This coul provide some speadup though.

**Comment by Qiana0223** [comment]
thanks very much！
