### ISSUE TITLE
How to analyze solidity source code in mythril?

### ISSUE THREAD

**Issue by namrata690** [ConsenSys/mythril#1446]
I followed the guide at: https://mythril-classic.readthedocs.io/en/master/installation.html, to install mythril in my Ubuntu-18.04 system.
`pip3 install mythril`: installs rlp-0.6.0, but then running myth shows the error- cannot import name 'ALL_BYTES', then I updated the rlp using `pip3 install rlp`, which installs version 2.0.0

Now, running `myth analyze <soldity-file>` or `myth --version` always returns the help menu of mythril.

What am I doing wrong here?
Thanks.

**Comment by norhh** [comment]
It maybe that you installed an old version. because current mythril does not run with rlp<1.0.1. try installing the latest version with pip.

**Comment by namrata690** [comment]
does `pip3 install mythril` not install the latest version? How should I install then?

**Comment by norhh** [comment]
It usually installs the latest version unless some version is already installed.
you can do it with `pip3 install mythril==v0.22.14`

**Comment by namrata690** [comment]
Thanks @norhh
