### ISSUE TITLE
Using --solc-args returns  `error: argument command: invalid choice: `

### ISSUE THREAD

**Issue by krasi-georgiev** [ConsenSys/mythril#1452]
Tried all variations, but doesn't seem to accept the solc-arg anymore

```
Mythril version v0.22.8
myth --solc-args "usingtellor/contracts=/tmp/node_modules/usingtellor/contracts --allow-paths /tmp/node_modules/usingtellor/contracts" analyze --solv=0.7.3 contracts/Main.sol


usage: myth [-h] [-v LOG_LEVEL] {analyze,a,disassemble,d,pro,p,list-detectors,read-storage,leveldb-search,function-to-hash,hash-to-address,version,truffle,help} ...
myth: error: argument command: invalid choice: 'usingtellor/contracts=/home/krasi/src/github.com/tellor-io/chorus/node_modules/usingtellor/contracts --allow-paths /home/krasi/src/github.com/tellor-io/chorus/node_modules/usingtellor/contracts' (choose from 'analyze', 'a', 'disassemble', 'd', 'pro', 'p', 'list-detectors', 'read-storage', 'leveldb-search', 'function-to-hash', 'hash-to-address', 'version', 'truffle', 'help')


# With docker
Mythril version v0.22.15

 docker run --rm -v $(pwd):/tmp mythril/myth --solc-args "usingtellor/contracts=/tmp/node_modules/usingtellor/contracts --allow-paths /tmp/node_modules/usingtellor/contracts" analyze --solv=0.7.3  /tmp/contracts/Main.sol
usage: myth [-h] [-v LOG_LEVEL]
            {analyze,a,disassemble,d,pro,p,list-detectors,read-storage,leveldb-search,function-to-hash,hash-to-address,version,help}
            ...
myth: error: argument command: invalid choice: 'usingtellor/contracts=/tmp/node_modules/usingtellor/contracts --allow-paths /tmp/node_modules/usingtellor/contracts' (choose from 'analyze', 'a', 'disassemble', 'd', 'pro', 'p', 'list-detectors', 'read-storage', 'leveldb-search', 'function-to-hash', 'hash-to-address', 'version', 'help')
```

**Comment by norhh** [comment]
Hi @krasi-georgiev , solc-args does not work, you can send a the solc-json as an input using `solc-json`, you can look into the format here https://docs.soliditylang.org/en/v0.7.0/using-the-compiler.html#compiler-input-and-output-json-description

**Comment by krasi-georgiev** [comment]
Thanks for the update, Could you give an example with the re-mapings. I tried it but couldn't figure out the exact syntax

**Comment by norhh** [comment]
I think there is a solc command which extracts out the solc json file.

**Comment by krasi-georgiev** [comment]
ping @norhh

**Comment by norhh** [comment]
@krasi-georgiev , I do not have a clear idea on remappings, you can try asking it on solc github page since the documentation doesn't clearly seem to explain remappings.

**Comment by krasi-georgiev** [comment]
Will do. In the meanwhile would you consider adding support for `solc-args` ?

**Comment by jrocco2** [comment]
@krasi-georgiev I noticed you closed this. Did you manage to get a working solution? I'm having the same problem

**Comment by norhh** [comment]
@jrocco2 you can use the `solc-json`, for more information you can look into this test https://github.com/ConsenSys/mythril/blob/develop/tests/integration_tests/test_solc_settings.py , This is an example solc-json file with remapping https://github.com/ConsenSys/mythril/blob/develop/tests/testdata/json_test_dir/test_file.json . For more information regarding solc-json  you can refer to solc documentation.

**Comment by jrocco2** [comment]
Ah perfect! That example works well. Thank you!
