### ISSUE TITLE
Audit Smart Contract

### ISSUE THREAD

**Issue by M-Hammad-Ali** [ConsenSys/mythril#1453]
How to Audit Smart Contract
## Description

I have successfully download the Mythril package and try to audit a smart contract. My contract requires 0.5.0 solc so I use the following command for analysis:
$myth analyze --solv 0.5.0  contracts_ERC20.sol

But it takes more than 2 hours for this and remains in the execution state
![image](https://user-images.githubusercontent.com/55716079/103435622-15ef9d00-4c33-11eb-8925-503018064882.png)

After that, it gives an error sometimes or remains to execute. Maybe I am using the wrong command for that. Notify me or give me some instruction to do an analysis of the contract.

**Comment by norhh** [comment]
Hi @M-Hammad-Ali , can you post the error? You can use `--execution-timeout` option to specify a timeout. Also use `myth -v4 analyze <rest of the stuff>` to see the current progress

**Comment by M-Hammad-Ali** [comment]
> Hi @M-Hammad-Ali , can you post the error? You can use `--execution-timeout` option to specify a timeout. Also use `myth -v4 analyze <rest of the stuff>` to see the current progress

I tried to execute it but it remains running don't give error. I wait for more than 3 hours.

**Comment by norhh** [comment]
That's an expected behavior, try using a lower timeout, the default timeout is 24 hours.

**Comment by M-Hammad-Ali** [comment]
It works. After specifying -v4 before analyze it worked
