### ISSUE TITLE
Plyvel,  installation error on ubuntu

### ISSUE THREAD

**Issue by Hamza-101** [ConsenSys/mythril#1456]
pip3 install mythril
Collecting mythril
Requirement already satisfied: certifi>=2020.06.20 in /usr/local/lib/python3.6/dist-packages (from mythril)
Requirement already satisfied: eth-abi==1.3.0 in /usr/local/lib/python3.6/dist-packages (from mythril)
Requirement already satisfied: eth-keyfile>=0.5.1 in /usr/local/lib/python3.6/dist-packages (from mythril)
Requirement already satisfied: eth-keys<0.3.0,>=0.2.0b3 in /usr/local/lib/python3.6/dist-packages (from mythril)
Requirement already satisfied: numpy==1.19.0 in /usr/local/lib/python3.6/dist-packages (from mythril)
Requirement already satisfied: jinja2>=2.9 in /usr/lib/python3/dist-packages (from mythril)
Requirement already satisfied: persistent>=4.2.0 in /usr/local/lib/python3.6/dist-packages (from mythril)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.6/dist-packages (from mythril)
Requirement already satisfied: py-solc in /usr/local/lib/python3.6/dist-packages (from mythril)
Requirement already satisfied: semantic-version==2.8.5 in /usr/local/lib/python3.6/dist-packages (from mythril)
Requirement already satisfied: ethereum-input-decoder>=0.2.2 in /usr/local/lib/python3.6/dist-packages (from mythril)
Requirement already satisfied: eth-tester==0.1.0b32 in /usr/local/lib/python3.6/dist-packages (from mythril)
Collecting transaction>=2.2.1 (from mythril)
  Using cached https://files.pythonhosted.org/packages/9b/35/b5cca132f9b364066bea00cbf4ea466b7a15461a609ab9ba8e832e165452/transaction-3.0.1-py2.py3-none-any.whl
Requirement already satisfied: pythx in /usr/local/lib/python3.6/dist-packages (from mythril)
Requirement already satisfied: z3-solver>=4.8.8.0 in /usr/local/lib/python3.6/dist-packages (from mythril)
Requirement already satisfied: py-ecc==1.6.0 in /usr/local/lib/python3.6/dist-packages (from mythril)
Requirement already satisfied: eth-rlp>=0.1.0 in /usr/local/lib/python3.6/dist-packages (from mythril)
Requirement already satisfied: py-solc-x==1.0.0 in /usr/local/lib/python3.6/dist-packages (from mythril)
Requirement already satisfied: eth-typing>=2.0.0 in /usr/local/lib/python3.6/dist-packages (from mythril)
Requirement already satisfied: eth-hash>=0.1.0 in /usr/local/lib/python3.6/dist-packages (from mythril)
Requirement already satisfied: ethereum>=2.3.2 in /usr/local/lib/python3.6/dist-packages (from mythril)
Requirement already satisfied: py-flags in /usr/local/lib/python3.6/dist-packages (from mythril)
Requirement already satisfied: rlp<2.0.0,>=1.0.1 in /usr/local/lib/python3.6/dist-packages (from mythril)
Collecting plyvel (from mythril)
  Using cached https://files.pythonhosted.org/packages/bd/4d/14ed73d3bc0ac1d5f3c1b79ba2fe509d8222053cfc94014804129d52642e/plyvel-1.3.0.tar.gz
Requirement already satisfied: py-evm==0.3.0a13 in /usr/local/lib/python3.6/dist-packages (from mythril)
Requirement already satisfied: eth-account<=0.3.0,>=0.1.0a2 in /usr/local/lib/python3.6/dist-packages (from mythril)
Requirement already satisfied: mock in /usr/local/lib/python3.6/dist-packages (from mythril)
Requirement already satisfied: coloredlogs>=10.0 in /usr/local/lib/python3.6/dist-packages (from mythril)
Requirement already satisfied: coverage in /usr/local/lib/python3.6/dist-packages (from mythril)
Requirement already satisfied: requests==2.25.0 in /usr/local/lib/python3.6/dist-packages (from mythril)
Requirement already satisfied: configparser>=3.5.0 in /usr/local/lib/python3.6/dist-packages (from mythril)
Requirement already satisfied: eth-utils<2.0.0,>=1.2.0 in /usr/local/lib/python3.6/dist-packages (from eth-abi==1.3.0->mythril)
Requirement already satisfied: parsimonious<0.9.0,>=0.8.0 in /usr/local/lib/python3.6/dist-packages (from eth-abi==1.3.0->mythril)
Requirement already satisfied: pycryptodome<4.0.0,>=3.4.7 in /usr/local/lib/python3.6/dist-packages (from eth-keyfile>=0.5.1->mythril)
Requirement already satisfied: cytoolz<1.0.0,>=0.9.0 in /usr/local/lib/python3.6/dist-packages (from eth-keyfile>=0.5.1->mythril)
Requirement already satisfied: zope.interface in /usr/lib/python3/dist-packages (from persistent>=4.2.0->mythril)
Requirement already satisfied: cffi; platform_python_implementation == "CPython" in /usr/local/lib/python3.6/dist-packages (from persistent>=4.2.0->mythril)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in /usr/local/lib/python3.6/dist-packages (from matplotlib->mythril)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.6/dist-packages (from matplotlib->mythril)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib->mythril)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib->mythril)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.6/dist-packages (from matplotlib->mythril)
Requirement already satisfied: mythx-models==1.9.3 in /usr/local/lib/python3.6/dist-packages (from pythx->mythril)
Requirement already satisfied: PyJWT==1.7.1 in /usr/local/lib/python3.6/dist-packages (from pythx->mythril)
Requirement already satisfied: inflection==0.5.1 in /usr/local/lib/python3.6/dist-packages (from pythx->mythril)
Requirement already satisfied: mypy-extensions>=0.4.1 in /usr/local/lib/python3.6/dist-packages (from py-ecc==1.6.0->mythril)
Requirement already satisfied: hexbytes<1,>=0.1.0 in /usr/local/lib/python3.6/dist-packages (from eth-rlp>=0.1.0->mythril)
Requirement already satisfied: pbkdf2 in /usr/local/lib/python3.6/dist-packages (from ethereum>=2.3.2->mythril)
Requirement already satisfied: pyethash<1.0.0,>=0.1.27 in /usr/local/lib/python3.6/dist-packages (from ethereum>=2.3.2->mythril)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.6/dist-packages (from ethereum>=2.3.2->mythril)
Requirement already satisfied: scrypt in /usr/local/lib/python3.6/dist-packages (from ethereum>=2.3.2->mythril)
Requirement already satisfied: future in /usr/local/lib/python3.6/dist-packages (from ethereum>=2.3.2->mythril)
Requirement already satisfied: coincurve>=7.0.0 in /usr/local/lib/python3.6/dist-packages (from ethereum>=2.3.2->mythril)
Requirement already satisfied: pysha3>=1.0.1 in /usr/local/lib/python3.6/dist-packages (from ethereum>=2.3.2->mythril)
Requirement already satisfied: repoze.lru in /usr/local/lib/python3.6/dist-packages (from ethereum>=2.3.2->mythril)
Requirement already satisfied: dictionaries==0.0.2 in /usr/local/lib/python3.6/dist-packages (from py-flags->mythril)
Requirement already satisfied: trie<2.0.0,>=1.4.0 in /usr/local/lib/python3.6/dist-packages (from py-evm==0.3.0a13->mythril)
Requirement already satisfied: cached-property<2,>=1.5.1 in /usr/local/lib/python3.6/dist-packages (from py-evm==0.3.0a13->mythril)
Requirement already satisfied: blake2b-py<0.2,>=0.1.2 in /usr/local/lib/python3.6/dist-packages (from py-evm==0.3.0a13->mythril)
Requirement already satisfied: lru-dict>=1.1.6 in /usr/local/lib/python3.6/dist-packages (from py-evm==0.3.0a13->mythril)
Requirement already satisfied: eth-bloom<2.0.0,>=1.0.3 in /usr/local/lib/python3.6/dist-packages (from py-evm==0.3.0a13->mythril)
Requirement already satisfied: attrdict<3,>=2.0.0 in /usr/local/lib/python3.6/dist-packages (from eth-account<=0.3.0,>=0.1.0a2->mythril)
Requirement already satisfied: humanfriendly>=9.1 in /usr/local/lib/python3.6/dist-packages (from coloredlogs>=10.0->mythril)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3/dist-packages (from requests==2.25.0->mythril)
Requirement already satisfied: idna<3,>=2.5 in /usr/lib/python3/dist-packages (from requests==2.25.0->mythril)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/lib/python3/dist-packages (from requests==2.25.0->mythril)
Requirement already satisfied: six>=1.9.0 in /usr/lib/python3/dist-packages (from parsimonious<0.9.0,>=0.8.0->eth-abi==1.3.0->mythril)
Requirement already satisfied: toolz>=0.8.0 in /usr/local/lib/python3.6/dist-packages (from cytoolz<1.0.0,>=0.9.0->eth-keyfile>=0.5.1->mythril)
Requirement already satisfied: pycparser in /usr/local/lib/python3.6/dist-packages (from cffi; platform_python_implementation == "CPython"->persistent>=4.2.0->mythril)
Requirement already satisfied: pydantic==1.7.3 in /usr/local/lib/python3.6/dist-packages (from mythx-models==1.9.3->pythx->mythril)
Requirement already satisfied: jsonschema<4.0.0 in /usr/lib/python3/dist-packages (from mythx-models==1.9.3->pythx->mythril)
Requirement already satisfied: asn1crypto in /usr/lib/python3/dist-packages (from coincurve>=7.0.0->ethereum>=2.3.2->mythril)
Requirement already satisfied: dataclasses>=0.6; python_version < "3.7" in /usr/local/lib/python3.6/dist-packages (from pydantic==1.7.3->mythx-models==1.9.3->pythx->mythril)
Building wheels for collected packages: plyvel
  Running setup.py bdist_wheel for plyvel ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-p7ymwskx/plyvel/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpluhyc9sypip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/plyvel
  copying plyvel/_version.py -> build/lib.linux-x86_64-3.6/plyvel
  copying plyvel/__init__.py -> build/lib.linux-x86_64-3.6/plyvel
  running build_ext
  building 'plyvel._plyvel' extension
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/plyvel
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -c plyvel/_plyvel.cpp -o build/temp.linux-x86_64-3.6/plyvel/_plyvel.o -Wall -g -x c++ -std=c++11
  x86_64-linux-gnu-gcc: warning: ‘-x c++’ after last input file has no effect
  plyvel/_plyvel.cpp:632:10: fatal error: leveldb/db.h: No such file or directory
   #include "leveldb/db.h"
            ^~~~~~~~~~~~~~
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

  ----------------------------------------
  Failed building wheel for plyvel
  Running setup.py clean for plyvel
Failed to build plyvel
Installing collected packages: transaction, plyvel, mythril
  Running setup.py install for plyvel ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-p7ymwskx/plyvel/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-8ktf85nx-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/plyvel
    copying plyvel/_version.py -> build/lib.linux-x86_64-3.6/plyvel
    copying plyvel/__init__.py -> build/lib.linux-x86_64-3.6/plyvel
    running build_ext
    building 'plyvel._plyvel' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/plyvel
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -c plyvel/_plyvel.cpp -o build/temp.linux-x86_64-3.6/plyvel/_plyvel.o -Wall -g -x c++ -std=c++11
    x86_64-linux-gnu-gcc: warning: ‘-x c++’ after last input file has no effect
    plyvel/_plyvel.cpp:632:10: fatal error: leveldb/db.h: No such file or directory
     #include "leveldb/db.h"
              ^~~~~~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-p7ymwskx/plyvel/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-8ktf85nx-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-p7ymwskx/plyvel/

**Comment by Hamza-101** [comment]
While installing on subsystem on linux

**Comment by norhh** [comment]
Hi, mythril does not work with windows. You can use the docker container by pulling it from github.
```
docker pull mythril/myth
```

**Comment by norhh** [comment]
Can you try `apt get install libleveldb-dev`? You can also look into the Mythril Dockerfile to install missing dependencies https://github.com/ConsenSys/mythril/blob/develop/Dockerfile

**Comment by Hamza-101** [comment]
Got this error  after: 
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/usr/lib/python3/dist-packages/pip/index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 795, in get_page
    resp.raise_for_status()
  File "/usr/share/python-wheels/requests-2.18.4-py2.py3-none-any.whl/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://pypi.org/simple/mtythril/

**Comment by Hamza-101** [comment]
Issue resolved probably from following random guides in random order lol.
