### ISSUE TITLE
I just got a few quick questions about Mythril

### ISSUE THREAD

**Issue by JackHFeng** [ConsenSys/mythril#1457]
I have a few quick questions about Mythril, I was wondering if you could help me. 
1.	When running “myth analyze”, are all the detector modules enabled by default? 
2.	Is there going to be a difference when running Mythril with contract source code and bytecode? 
        Especially, in terms of vulnerability detection and coverage, will Mythril perform worse with only bytecode provided? 
3.	If all we care is analyzing and collect coverage on runtime bytecode, is there going to a difference between having Mythril analyzing creation bytecode and runtime bytecode? 
        a.	If Mythril is unable to execute a contract’s constructor, will Mythril continue to analyze the runtime bytecode?
        b.	When providing Mythril with only runtime bytecode, since constructor was never executed, will Mythril assign arbitrary values to state variables that was supposed to be set by constructor? 
4.	Is the default max call depth set to 3? 
        And is this max call depth referring to transaction sequences with length up to 3? 
        a.	If we set max call depth to e.g. 5, will the work completed up to depth 3 in this configuration the same as when the max depth was set to 3? 
        b.	What is the max depth we can set? Given that we want to let Mythril run indefinitely. 

Thank you so much for your time and help!

**Comment by JoranHonig** [comment]
1. Yes
2. No, mythril will compile the contract & then only look at the bytecode
3. We use the constructor to determine the possible "entry" states of a contract, without this we'd have tons of false positives
a. No, but it will tell you that the constructor didn't work
b. State variables would be symbolic
4. Yes, and no https://github.com/ConsenSys/mythril/blob/develop/mythril/interfaces/cli.py#L424
a. Yes. With calldepth 3 it would just not go further. 
b. There would technically be no limit except those from the available resources.

**Comment by JackHFeng** [comment]
@JoranHonig 
Thank you so much for your prompt reply!
So, for question number 4, the call depth is the depth that happens within a single transaction, e.g., calling between functions, of different contracts within a single transaction, like a reentrant scenario? 

Does `--transaction-count` mean the maximum tx sequence length mythril will explore? E.g., 3, on the symbolic state that was determined by the constructor, Mythril will try to symbolically execute all permtation of 3 functions in a order; and functions could appear more than once. 

The reason I'm asking is because Mythril seems to terminate quite quickly on some of the contracts and yielding a low coverage, and a particular contract among them doesn't call any other contract, meaning the call depth would never really go up, and there isn't any loops. However, some functions do depend on other functions executing before them to create states that would satisfy their require statements. I was thinking, maybe this is due to Mythril only exploring transaction sequences with length up to a very small number?

**Comment by norhh** [comment]
@JackHFeng
Regarding `--transaction-count` Mythril will try to symbolically execute three transactions. Each symbolic transaction assumes the function being executed to be any function in the list of all possible functions. So it covers all possible transaction permutations including calling the same function thrice.
`call-depth-limit` limits the depth of transaction. If the limit is 3, then it does not exceed 3 nested calls.

**Comment by JackHFeng** [comment]
Thank you!! @norhh
