### ISSUE TITLE
SWC 110 false positive?

### ISSUE THREAD

**Issue by hack3r-0m** [ConsenSys/mythril#1475]
I analyzed a contract and the output shows there is SWC 110 but I am not able to find any relevant info.

More details : [Ethereum StackExchange Post](https://ethereum.stackexchange.com/questions/96978/address-payable-public-causing-swc-110-and-execption-state)

Is it false positive?

- Tool should provide a more precise location of the statement
- It doesn't seem to medium severity

**Comment by norhh** [comment]
Hi, this is a false positive. An array is like a function which can be accessed by a call() in ethereum, so it's possible to raise an exception, so it is a false positive.
