### ISSUE TITLE
Error when running mythril to analyze on chain contract using rpc

### ISSUE THREAD

**Issue by HacKeD0x90** [ConsenSys/mythril#1476]
I get the below error when running mythril to analyze an on chain contract on ropsten network using the below command.
**myth analyze --rpc infura-ropsten -a 0xADDRESS-HERE**

ERROR
mythril.interfaces.cli [ERROR]: IPC / RPC error: 'NoneType' object has no attribute 'eth_getCode' 

Myth Version: Mythril version v0.22.19
Python Version: 3.6.9

I also tried running from docker but got same problem.

**Comment by norhh** [comment]
@HacKeD0x90 did you set the infura ID?

**Comment by HacKeD0x90** [comment]
No I don't think I did this, can you provide me a link to read about it?
I'm new to this, but as far as my understanding if i set the --rpc ifura-ropsten it will connect to the contract which exist in ropsten test blockchain with the address provided in the "-a" option.

**Comment by norhh** [comment]
You need to have an infura id(from https://infura.io/) to access ropsten. with `--infura-id INFURA_ID`

**Comment by HacKeD0x90** [comment]
Thanks  a lot, fixed now after following your recommendation.
