### ISSUE TITLE
ParserError: Source "@openzeppelin/contracts/access/Ownable.sol" not found: File not found.

### ISSUE THREAD

**Issue by aferreira44** [ConsenSys/mythril#1478]
Hi guys, I'm following the OpenZepellin tutorial wich works fine, but when I run the `mith analyze` I received that error:
`ParserError: Source "@openzeppelin/contracts/access/Ownable.sol" not found: File not found.`

Here's the code snippet of the smart contract:

```
pragma solidity ^0.8.0;

// Import Ownable from the OpenZeppelin Contracts library
import "@openzeppelin/contracts/access/Ownable.sol";

// Make Box inherit from the Ownable contract
contract Box is Ownable {
    uint private value;

    // Emitted  when the stored value changes
    event ValueChanged(uint256 newValue);

...
```

If a change my code to import the contract as below, it works!

`import "../node_modules/@openzeppelin/contracts/access/Ownable.sol";`

How can I use the import statement just using @ and not a relative path of the node_modules to the OpenZepellin contracts?

**Comment by norhh** [comment]
The solc binary does not know the location of @openzepplin, it's possible by using solc's `standard-json` input format to mythril, but it does not seem to be worth it in this case.

**Comment by norhh** [comment]
The solc binary does not know the location of @openzepplin, it's possible by using solc's `standard-json` input format to mythril by providing import list, but it does not seem to be worth it in this case.

**Comment by aferreira44** [comment]
Thank you @norhh!

**Comment by idirall22** [comment]
Hello @norhh
Can I use myth if I have @openzeppelin links? because currently, I got the same error

**Comment by norhh** [comment]
@idirall22 , you can either use `standard-json` format of solc or you can just add all the imports as code into a single contract.

**Comment by 0xfoobar** [comment]
@norhh How would I use the `standard-json` format?

**Comment by norhh** [comment]
@0xfoobar I should add some documentation regarding this, but this directory should contain a decent example https://github.com/ConsenSys/mythril/tree/develop/tests/testdata/json_test_dir . You can check how the remapping is in the json file is done for the directory. 
You just need to run `./myth a filename --standard-json <json_file>`
For more information you can look into how settings are constructed in solc [documentation](https://docs.soliditylang.org/en/v0.8.6/using-the-compiler.html?highlight=json%20input#input-description)

**Comment by solarsailorneo** [comment]
when I run `./myth a filename --standard-json <json_file>` I get this error:
`myth: error: unrecognized arguments: --standard-json testfile.json`. Is the `--standard-json` flag still available?

**Comment by solarsailorneo** [comment]
Figured it out. The `--solc-json` flag is working

**Comment by devScrooge** [comment]
I still dont get how I should execute `myth analyze`for it in order to recognize the OpenZeppelin contracts. Can someone tell me?

**Comment by vvxhid** [comment]
@devScrooge  add a json file to remap the path to node_modules folder: 

`{
    "remappings": [
        "@openzeppelin/contracts-upgradeable/utils/=../node_modules/@openzeppelin/contracts-upgradeable/utils/"
    ],
    "optimizer": {
        "enabled": true
    }
}`

run myth with `--solc-json` option: `myth analyze test.sol --solc-json remapping.json`

**Comment by javierdeveloping** [comment]
just to contribute:

```
{
  "remappings": [
    "@openzeppelin/contracts-upgradeable=../node_modules/@openzeppelin/contracts-upgradeable",
    "@openzeppelin/contracts=../node_modules/@openzeppelin/contracts",
    "@chainlink=../node_modules/@chainlink"
  ],
  "optimizer": { "enabled": true }
}
```

**Comment by studiov-dev** [comment]
Running myth analize from Docker:

myth-standard.json:
```
{
 "remappings": [
   "@openzeppelin/=/tmp/node_modules/@openzeppelin/"
 ],
  "optimizer": {
    "enabled": true
  }
}
```

Then run:
`sudo docker run -v $(pwd):/tmp mythril/myth analyze /tmp/contracts/MyContract.sol --solc-json /tmp/mythril-standard.json`

**Comment by Ovodo** [comment]
running this command solved it for me using foundry.
`forge remappings > remappings.txt`
