### ISSUE TITLE
When I used mythril's docker image to scan the specified contract address, an error occurred

### ISSUE THREAD

**Issue by Aloneposix** [ConsenSys/mythril#1479]
When I execute the following command in macOS, it shows this error message

Command Line: `docker run mythril/myth analyze -a 0xdac17f958d2ee523a2206206994597c13d831ec7`

**mythril.interfaces.cli [ERROR]: IPC / RPC error: 'NoneType' object has no attribute 'eth_getCode'**

`docker run mythril/myth version`

**_Mythril version v0.22.19_**

**Comment by norhh** [comment]
Hi, to access any data onchain, you need infura-id, which you can get from https://infura.io/ . You can use the arg `--infura-id <ID>` to pass the ID as cmd line argument.
