### ISSUE TITLE
infura key set

### ISSUE THREAD

**Issue by maxirodr** [ConsenSys/mythril#1485]
Hello there! I don't know how to set infura api key environment. I've created project_id and key but don't know how to set it. I've read the setup but it doesn't seem too much clarify:

![imagen](https://user-images.githubusercontent.com/25252671/122085734-4c952a80-ce03-11eb-9fc0-3b438d6d3f74.png)

https://mythril-classic.readthedocs.io/en/master/security-analysis.html

**Comment by norhh** [comment]
Hi, try  `--infura-id <INFURA_ID>` flag or you can add the line `infura_id = <INFURA_ID>` in the file `~/.mythril/config.ini`

**Comment by maxirodr** [comment]
working, thanks!
