### ISSUE TITLE
Analyze not happening

### ISSUE THREAD

**Issue by maxirodr** [ConsenSys/mythril#1486]
Hello, me again. 

The analyze is not working or i don't know what is happening:

![imagen](https://user-images.githubusercontent.com/25252671/122110894-5d539980-ce1f-11eb-8219-c67f8711e182.png)

![imagen](https://user-images.githubusercontent.com/25252671/122110910-63497a80-ce1f-11eb-9eba-8a82da6f3eff.png)

contract:
https://github.com/HogeFinance/token/blob/main/contract.sol
https://etherscan.io/address/0xfad45e47083e4607302aa43c65fb3106f1cd7607#code

infura ID is setup and working now.

**Comment by norhh** [comment]
It is working, it takes some time.
try running with `-v4` flag to see the status, 
like `myth -v4 a contract.sol --solv 0.6.12`

**Comment by maxirodr** [comment]
is here since 3-4hs:

![imagen](https://user-images.githubusercontent.com/25252671/122236453-cf2ef000-cebe-11eb-97c0-884405b5f9c7.png)


it seems not interacting with the network or what?

**Comment by norhh** [comment]
It's actually a pretty huge contract, you can try reducing the `solver-timeout` by using its respective flag.

**Comment by maxirodr** [comment]
@norhh  that's work fine. Thanks!
