### ISSUE TITLE
Incorrect txdata format in output

### ISSUE THREAD

**Issue by loki3451** [ConsenSys/mythril#1494]
## Description

When running mythril v0.22.22 on the following contract:
```solidity
pragma solidity ^0.4.20;

contract Freemoney {
    bool[4096] flags;

    function Freemoney() public payable
    {
        require(msg.value == 0.1 ether);
        flags[1234] = true;
    }

    function extractMoney(uint256 idx) public payable
    {
        require(flags[idx]);
        msg.sender.transfer(this.balance);
    }
}
```
via
```console
myth analyze --unconstrained-storage -m EtherThief --solv=0.4.20 array.sol
```
I receive the following output:
```
==== Unprotected Ether Withdrawal ====
SWC ID: 105
Severity: High
Contract: Freemoney
Function name: extractMoney(uint256)
PC address: 208
Estimated Gas Usage: 2567 - 37178
Any sender can withdraw Ether from the contract account.
Arbitrary senders other than the contract creator can profitably extract Ether from the contract account. Verify the business logic carefully and make sure that appropriate security controls are in place to prevent unexpected loss of funds.
--------------------
In file: array.sol:15

msg.sender.transfer(this.balance)

--------------------
Initial State:

Account: [CREATOR], balance: 0x21410c01400a0002, nonce:0, storage:{}
Account: [ATTACKER], balance: 0x42080080502040000, nonce:0, storage:{}
Account: [SOMEGUY], balance: 0x0, nonce:0, storage:{}

Transaction Sequence:

Caller: [CREATOR], calldata: , value: 0x16345785d8a0000
Caller: [ATTACKER], function: extractMoney(uint256), txdata: 0xab125858, value: 0x0
```
## Expected behavior

The expected output should contain the following txdata: ab12585800000000000000000000000000000000000000000000000000000000000004d2

## Environment

I am using 3.8.10 on Ubuntu 20.04.

**Comment by loki3451** [comment]
I would like to describe some similar instances of unexpected behavior / undetected (or incorrectly detected) vulnerabilities.

1. Similar output is produced when analyzing the same contract on-chain (e.g. via ganache). In particular the same "attack" with `txdata: 0xab125858` is detected. Notably, no `getStorage` requests are issued by mythril.
2. The same happens when replacing the hardcoded constant `1234` by a contract constructor parameter. I.e. when analyzing the contract on-chain, the array index value required to extract funds is not output by mythril and no `getStorage` requests are performed.
3. If we ditch querying an array in the contract storage and simply require guessing the value of some integer variable, i.e.
    ```solidity
    pragma solidity ^0.4.20;
    
    contract Freemoney {
        uint256 theVal;
    
        function Freemoney() public payable
        {
            require(msg.value == 0.1 ether);
            theVal = 1234;
        }
    
        function extractMoney(uint256 val) public payable
        {
            require(val == theVal);
            msg.sender.transfer(this.balance);
        }
    }
    ```
    The vulnerability is detected correctly when analyzing the solidity source directly, but once again the same incorrect output is produced when analyzing on-chain (and no `getStorage` queries happen).
4. When replacing `msg.sender.transfer(this.balance)` with `suicide(msg.sender)` in the contract code and `EtherThief` module with `AccidentallyKillable` in the mythril command line, analogous behavior is observed (with a different SWC).

Generally, I am wondering whether mythril is capable of consistently detecting vulnerabilities where the attacking transaction is dependent on some value in the contract storage (via contract code and on-chain). Is it expected to work at all? Can it be done by applying mythril in some different way?

**Comment by norhh** [comment]
Since you are using `un constrained storage` option which will assume the contract is already constructed with storage that can be anything, this results in the given tx data. You need to increase the solver timeout but there still seems to be some issue with transaction data.

**Comment by loki3451** [comment]
Hi. Thanks for your reply!

Could you please explain the `--unconstrained-storage` option in a bit more detail? I cannot find any documentation. Do you mean it allows contract storage to contain any values at the time of the attack transaction and ignores any previous assignments?

Anyway, I tried removing this option and setting a high `--solver-timeout`. This helped in the case of determining the value of a single storage variable (i.e. the second contract above). `getStorageAt` request happens and the correct argument to `extractMoney` is produced. Execution time actually does not exceed previous attempts. Great.

However in the array case (first contract), the results are unchanged, although execution now takes a long time. With `--solver-timeout 1000000` when analyzing the contract on-chain, analysis ran for ~85 minutes and the same incorrect txdata was produced and no `getStorageAt` requests occurred. The latter makes me doubt that simply further increasing timeout can help. By the way, for some reason, analyzing source code is ~5x faster (with the same result).

So the question remains whether mythril can correctly determine the problematic argument to `extractMoney` in the OP contract and if some bug is currently preventing this.

**Comment by norhh** [comment]
unconstrained storage will just assume the contract's storage can contain any value, it's mostly useful for running runtime-bytecodes. Since it assumes the storage to contain any value it leads to false positives since some storage states may not be possible to be achieved.

**Comment by norhh** [comment]
This issue is actually related to the one I am currently working on. There are issues with exponentiation since SMT solvers cannot directly support exponentiation without a significant slowdown due to the non-linear arithmetic. Boolean arrays are handled differently when compared to integer arrays, Instead of storing `true` at  some `offset + idx` in storage they  store `power(256, last_6_bits(idx))` at `offset + first_250_bits(idx)` which mythril cannot handle properly due to the non linear arithmetic. Just change the boolean array to uint256 and you will see the true value, and it should run quite fast.

**Comment by loki3451** [comment]
Thx for the explanation. After this change the array example indeed works as expected (when analyzing the source).

When analyzing on-chain, it still doesn't work (reports no attack at all). On-chain storage is not queried. Increasing timeout has no effect. However the vulnerability is detected when passing the contract creation tx input directly (via `-c`).

**Comment by norhh** [comment]
@loki3451 , are you analyzing it with an address?

**Comment by loki3451** [comment]
Yes, that is what I mean by "on-chain". With an address after deploying to ganache. Can you reproduce this behavior?

I've changed the contract to:
```solidity
pragma solidity ^0.4.20;

contract Freemoney {
    uint256[4096] flags;

    function Freemoney() public payable
    {
        require(msg.value == 0.1 ether);
	flags[1234] = 1;
    }

    function extractMoney(uint256 idx) public payable
    {
        require(flags[idx] != 0);
        msg.sender.transfer(this.balance);
    }
}
```
and run mythril as follows:
```console
myth -v5 analyze --solver-timeout 600000 -m EtherThief --rpc localhost:8546 -a 0x54f17eca4A38C71319F253374D4c91CD572ded9f
```
(running time is 2-3 seconds). Attaching log just in case.
[myth.array.int.onchain.2.log](https://github.com/ConsenSys/mythril/files/6830898/myth.array.int.onchain.2.log)

**Comment by norhh** [comment]
This is a different issue, Since the storage ranges from 0 to 2**256 -1, it's not possible for mythril to load up all the storage for the contract, Hence there will be some issues when a storage access happens with respect to some symbolic index.The issues with the bool arrays should be fixed now, so I am closing this issue, feel free to open it if it still persists.

**Comment by loki3451** [comment]
Appreciate your reply. Would be great if you could explain a bit further.

1) It seems that most of the 2**256 storage locations you mention can be safely ignored. Would it theoretically be feasible to load and further consider only _initialized_ storage locations for a given on-chain contract?

2) Why is storage loaded when working with a single `uint256` variable, but not with an array? Even if the array is of size 1 actually.

3) Does it make sense to open a new issue (or re-open this one) to further pursue this discussion? The question being: "can mythril (be enhanced to) detect vulnerabilities dependent on values of array elements in on-chain contract storage?"

**Comment by norhh** [comment]
1) Yes, but we do not know what storage locations to ignore as json rpc does not provide an easy endpoint for such information, The only access to storage that I know of is to give the index of the storage but we do not know what indices of storage are initialised this can probably be curbed by some heuristics but might be a bit expensive
2) arrays have accesses like `array[index]` where the `index` can range anywhere from `0` to `2**256-1`, when a variable is accessed its location in storage is fixed, so it does not have such an issue.
3) It would be easier to track if you can open a new issue to discuss this, I can try out some heuristics to handle arrays, but it would be hard to handle `mappings` efficiently due to the current json RPC.
