### ISSUE TITLE
Support optimizer during analyze

### ISSUE THREAD

**Issue by stephenctw** [ConsenSys/mythril#1496]
## Description

Please support optimizer option for solc during myth analyze.

## Background

I have a contract compiles fine with optimizer turned on. But when running myth analyze on it, I got this error.
```
"Solc experienced a fatal error.\n\nCompilerError: Stack too deep when compiling inline assembly: Variable headStart is 1 slot(s) too deep inside the stack.\n\n"
```

Seems the feature was there but being reverted here. https://github.com/ConsenSys/mythril/pull/1230

**Comment by norhh** [comment]
Currently mythril runs optimize on all the files, can you post an example where this crash happens?

**Comment by stephenctw** [comment]
Hi, this contract code should produce the error.
```

pragma solidity ^0.8.0;

contract TooDeep {

    function a(
        uint256 b,
        uint256 c,
        uint256 d,
        uint256 e,
        uint256 f,
        uint256 g,
        uint256 h,
        uint256 i,
        uint256 j,
        uint256 k,
        uint256 l,
        uint256 m
    ) public {    }
}
```
