### ISSUE TITLE
Enable handling dynamically addressed storage slots when analyzing on-chain contracts

### ISSUE THREAD

**Issue by loki3451** [ConsenSys/mythril#1500]
## Description

Creating this issue following @norhh's suggestion. My understanding of the details is likely not entirely correct. Hopefully others will provide a better description.

In #1494 it is discussed that mythril is currently unable to detect a vulnerability in an on-chain contract, when execution of the attack transaction depends on dynamically addressed storage values (i.e. their location in contract storage is not hardcoded but computed during execution). A simple example would be dependency on an array element where the index is passed in as a function argument.

It seems that complete support would require determining all initialized storage slots for a given contract and then loading them (via `getStorageAt()`). APIs for blockchain access currently do not provide an easy way to do the former, although workarounds have been suggested, see e.g. https://ethereum.stackexchange.com/a/40280

It may also be possible to devise simpler workarounds for specific cases, e.g. statically sized arrays.

**Comment by norhh** [comment]
This works to some extent now by loading and constraining storage for each on-site call.
