### ISSUE TITLE
`Input file not found` with `remappings` option on `0.22.24`

### ISSUE THREAD

**Issue by stephenctw** [ConsenSys/mythril#1505]
## Description

Error `Input file not found` when running analyze with `remappings` option on latest `0.22.24`
(`0.22.23` doesn't has this error)

## How to Reproduce

Have `contracts/A.sol` 

```contracts/A.sol
pragma solidity >=0.7.0 <0.9.0;

import "@3rd/B.sol";

contract A {

}
```
and `3rd/B.sol` files

```3rd/B.sol
pragma solidity >=0.7.0 <0.9.0;

library B {

}
```
Command to run:

```console
myth analyze contracts/A.sol --solc-json '{"remappings":["@3rd/=./3rd/"]}'
```

## Expected behavior

`The analysis was completed successfully. No issues were detected.`

## Environment

- Mythril version: 0.22.24
- Solidity compiler and version: 0.7.5-develop.2020.11.18+commit.1e08e4e0.Linux.g++
- Python version: Python 3.6.9
- OS and Version: WSL2 Ubuntu 18.04

**Comment by norhh** [comment]
Oops, this is an incorrect error. 
You should run it like this
`myth analyze contracts/A.sol --solc-json remap.json` 
where `remap.json` has the file mapping

**Comment by stephenctw** [comment]
> Oops, this is an incorrect error.
> You should run it like this
> `myth analyze contracts/A.sol --solc-json remap.json`
> where `remap.json` has the file mapping

Thanks!
