### ISSUE TITLE
Add support for arm64 images

### ISSUE THREAD

**Issue by saniales** [ConsenSys/mythril#1517]
## Description

It would be super cool if docker images are built supporting also arm64 architecture

## Background

I have a raspberry pi and I would love to run docker images on my rasp, however I get the error that Docker Hub does not have an arm64 image, instead only x64 is supported.

## Suggestion

It would be possible to perform multi build using [docker buildx](https://docs.docker.com/buildx/working-with-buildx/)

**Comment by norhh** [comment]
@saniales , it's worth it in supporting ARM64, but I am not sure if a raspberry pi would effectively be able to run Mythril unless your goal is running it on small contracts.

**Comment by MajdT51** [comment]
Hi @norhh , It would be great to have it now to make the image works without warning and maybe errors on MacOS M1 and M2. Thanks :)
