### ISSUE TITLE
clang fatal error during 'pip3 install mythril' step

### ISSUE THREAD

**Issue by dappsec** [ConsenSys/mythril#152]
Tried building from scratch [on macOS High Sierra 10.13.3, Python3 is 3.6.5 (although default python is 2.7.14), pip3 v10.0.1 from python 3.6]

Getting this error:

clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c plyvel/_plyvel.cpp -o build/temp.macosx-10.13-x86_64-3.6/plyvel/_plyvel.o -Wall -g -mmacosx-version-min=10.7 -stdlib=libc++
    plyvel/_plyvel.cpp:547:10: fatal error: 'leveldb/db.h' file not found
    #include "leveldb/db.h"
             ^~~~~~~~~~~~~~
    1 error generated.
    error: command 'clang' failed with exit status 1

**Comment by dappsec** [comment]
Ran 'brew install leveldb' based on https://stackoverflow.com/questions/26199376/how-to-install-leveldb-on-mac-os-x and got past that build step.

**Comment by b-mueller** [comment]
We're planning to write a more detailed installation guide soon, I'll make sure that this is included.

**Comment by b-mueller** [comment]
Installation instructions are now available in the Wiki.
