### ISSUE TITLE
Version 0.22.27 fails to run analysis on a file "outside of allowed directories"

### ISSUE THREAD

**Issue by hantuzun** [ConsenSys/mythril#1525]
## Description

Mythril `0.22.27` fails to run analysis on a file whereas `0.22.26` runs smoothly. The file is put in `/tmp` of the official Docker image. There is no documentation on which directories are allowed and the reasoning behind that.

## How to Reproduce

```bash
TMP_CONTRACT=/tmp/Contract.sol

MYTHRIL_TAG=0.22.27
docker pull mythril/myth:$MYTHRIL_TAG
docker run -v /tmp:/tmp mythril/myth:$MYTHRIL_TAG -v 5 analyze $TMP_CONTRACT
```

Outputs: 

```
0.22.27: Pulling from mythril/myth
Digest: sha256:048f6be7b8f760862db6b2d5687bfa886cac58f87e6b71ae368917244c8121f2
Status: Downloaded newer image for mythril/myth:0.22.27
docker.io/mythril/myth:0.22.27
mythril.mythril.mythril_config [INFO]: Creating mythril data directory
mythril.mythril.mythril_config [INFO]: No config file found. Creating default: /root/.mythril/config.ini
mythril.mythril.mythril_config [INFO]: Infura key not provided, so onchain access is disabled. Use --infura-id <INFURA_ID> or set it in the environment variable INFURA_ID or in the ~/.mythril/config.ini file
mythril.support.signatures [INFO]: Using signature database at /root/.mythril/signatures.db
mythril.interfaces.cli [ERROR]: Solc experienced a fatal error.

Cannot import url ("/tmp/Contract.sol"): File outside of allowed directories.
```

## Expected behavior

Running the analysis as with version `0.22.26`.

## Environment

Since I'm running Docker images of Mythril, this bug should be reproducible on any platform.

**Comment by vince0656** [comment]
I get this same issue on MacOS - will try older version

**Comment by vince0656** [comment]
`0.22.26` seems to work although it didn't like my use of solidity `0.8.9`

**Comment by bgaborg** [comment]
same issue here. on mac, and on an ubuntu server too.

**Comment by Silur** [comment]
same issue on arch linux x64

**Comment by norhh** [comment]
Hi, Now this issue should be fixed. There was an issue with mounted directory from docker due to a bug with solcx, this issue should be fixed now.
You can simply port your directory into the container using `-v <path_to_your_directory_with_file>:<some_absolute_path>` and use the absolute path during the mythril command `mythril/myth -v4 analyze <some_absolute_path>/contract.sol`
