### ISSUE TITLE
Issues when installing mythril via requirements.txt: py-ecc, rlp, blake2b, syntax warning

### ISSUE THREAD

**Issue by gsalzer** [ConsenSys/mythril#1536]
## Description

When installing `mythril` via `requirements.txt`, two version mismatches and a missing dependency occur, as well as a syntax warning when starting `mythril` the first time.

Suggestion:
- Add `blake2b-py` to `requirements.txt`

Question: How serious are the version mismatches
- `py-evm 0.5.0a1 has requirement py-ecc<5.0.0,>=1.4.7, but you'll have py-ecc 5.2.0`
- `py-evm 0.5.0a1 has requirement rlp<3,>=2, but you'll have rlp 1.2.0 `

## How to Reproduce

```console
$ git clone  https://github.com/ConsenSys/mythril.git
$ cd mythril
$ python3 -m venv venv
$ . venv/bin/activate
$ pip install -r requirements.txt
[...]
ERROR: py-evm 0.5.0a1 has requirement py-ecc<5.0.0,>=1.4.7, but you'll have py-ecc 5.2.0 which is incompatible.
ERROR: py-evm 0.5.0a1 has requirement rlp<3,>=2, but you'll have rlp 1.2.0 which is incompatible.
[...]
$ ./myth
[...]
ModuleNotFoundError: No module named 'blake2b'
$ pip install blake2b-py
$ ./myth
[...] mythril/mythril/laser/ethereum/instructions.py:2394: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  with_value = function_name is not "staticcall"

[ myth displays usage, no error except warning above]
```
The warning appears only the first time `myth` is called, apparently during compilation.

## Environment

- Mythril version: commit `82d2fa81964cebe7a97991dd5e1a6a2d9bba83ff`
- Python version: 3.8.10
- OS and Version: Ubuntu 20.04.3 LTS

**Comment by norhh** [comment]
py-evm requirement should be fixed now
