### ISSUE TITLE
EtherThief not detecting vulnerability when funds are acquired via remote contract 

### ISSUE THREAD

**Issue by loki3451** [ConsenSys/mythril#1539]
## Description

I have a pair of contracts (deployed via ganache) where the first (`Freemoney`) has some ether while the second (`Getmoney`) is able to extract it and pass on to anyone who calls a `extractMoney` function:

```solidity
pragma solidity ^0.4.20;
contract Freemoney {
    function Freemoney() public payable
    {
     	require(msg.value == 0.1 ether);
    }
    function extractMoney() public payable
    {
        msg.sender.transfer(address(this).balance);
    }
}
```

```solidity
pragma solidity ^0.4.20;
import "./freemoney.sol";
contract Getmoney {
    Freemoney constant public fm = Freemoney(<address of Freemoney>);
    function() external payable {}
    function extractMoney() public payable
    {
        fm.extractMoney();
        msg.sender.transfer(address(this).balance);
    }
}
```

I analyze `Getmoney` on-chain via mythril's `EtherThief` module and expect it to detect a vulnerability. However it reports no issues found.

## How to Reproduce

Deploy both above contracts (using 0.1ETH value when deploying the first and pasting it's address into the second contract before deploy) then run mythril  (I am on 579480b4) via
`myth -v5 analyze --solver-timeout 600000 -m EtherThief --rpc <node URI> -a <Getmoney address>`
I used solcx.compile_files with default arguments to compile the contracts.

## Expected behavior

I expected mythril to detect a vulnerability - a call to `extractMoney()`.

**Comment by loki3451** [comment]
Some additional info. As is, mythril reports ~1.15s solver time and 65% and 70% _coverage_ for two different bytecodes. However if I make the the balance of the Freemoney contract _symbolic_ by adding the following line to `DynLoader.read_balance`:
```python
        if address == "<Freemoney address>": raise Exception()
```
a vulnerability is actually detected when running the same command on the same contract. Solver time is now 2-3 minutes and coverage is 97.5% and 93%.

I only have a vague understanding of what I am talking about here but maybe this can be helpful in understanding the issue.

**Comment by norhh** [comment]
Thanks for the help, this seems to be an issue with extracting concrete balances for contracts from block chain.
