### ISSUE TITLE
-l is not recognized in myth

### ISSUE THREAD

**Issue by hoinamIddy** [ConsenSys/mythril#1552]
I tried this code and I got the error: myth: error: unrecognized arguments: -l
`docker run mythril/myth -v4 analyze -a 0x2FC26DccDA332d3a56Ba699712aD65B07206F1FC --rpc host.docker.internal:8545 -o jsonv2 -l `

Error:
`usage: myth [-h] [-v LOG_LEVEL]
            {safe-functions,analyze,a,disassemble,d,list-detectors,read-storage,leveldb-search,function-to-hash,hash-to-address,version,help}
            ...
myth: error: unrecognized arguments: -l`

Thanks for helping!

**Comment by norhh** [comment]
Hi @hoinamIddy, thanks for pointing it out. The `-l` option has been removed. This should be updated in the documentation.
