### ISSUE TITLE
Analysis misses integer overflow

### ISSUE THREAD

**Issue by b-mueller** [ConsenSys/mythril#156]
Mythril appears to miss the MUL overflow in [BECToken](https://etherscan.io/address/0xc5d105e63711398af9bbff092d4b6769c82f793d#code), a.k.a. batchOverflow. The overflows is located in the function `batchTransfer`, line 257. 

```
    uint256 amount = uint256(cnt) * _value;
```

Running the following fall to detect this issue:

```
$ myth -x BECToken.sol:BecToken
$ myth -x BECToken.sol:PausableToken
$ myth -x BECToken.sol:BecToken --max-depth 16
```

I also noticed that the runtime of the integer overflow tests increases heavily if --max-depth is increased. We might have to play with the `max_depth` setting of `search_children`.

@JoranHonig  can you look into this?

**Comment by JoranHonig** [comment]
I'll look at it right away

**Comment by JoranHonig** [comment]
Ok, so I found the problem. This is an example of the brittleness of the current taint checking approach.
The following is the expression derived from the statement:
calldata_PausableToken_4 + calldata_PausableToken_4*
calldata_PausableToken_32 + 4

The following is the expression where we should discover taint:
((UGT(calldata_PausableToken_32 + 4*
      calldata_PausableToken_4 + calldata_PausableToken_4,
      storage_keccac_1461501637330902918203684832716283019655932542975_&
1461501637330902918203684832716283019655932542975_&
caller) ==
  False) ==
 False) ==
False

You can see that somewhere z3 switched the values, and there are some spaces in the second line. This makes taint checking fail

**Comment by JoranHonig** [comment]
As I said in the pr, it might be beneficial to move to another way of taint checking that is less brittle.
But for now the pr should fix the problem. I get the following output:
```
/home/walker/dev/mythril/venv/bin/python /home/walker/dev/mythril/myth -x /home/walker/dev/mythril/BECToken.sol:PausableToken
==== Exception state ====
Type: Informational
Contract: PausableToken
Function name: transfer(address,uint256)
PC address: 4141
A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. 
--------------------
In file: /home/walker/dev/mythril/BECToken.sol:28

assert(c >= a)

--------------------

==== Integer Overflow  ====
Type: Warning
Contract: PausableToken
Function name: transfer(address,uint256)
PC address: 4128
A possible integer overflow exists in the function `transfer(address,uint256)`.
The addition or multiplication may result in a value higher than the maximum representable integer.
--------------------
In file: /home/walker/dev/mythril/BECToken.sol:27

a + b

--------------------

==== Integer Overflow  ====
Type: Warning
Contract: PausableToken
Function name: batchTransfer(address[],uint256)
PC address: 1499
A possible integer overflow exists in the function `batchTransfer(address[],uint256)`.
The addition or multiplication may result in a value higher than the maximum representable integer.
--------------------
In file: /home/walker/dev/mythril/BECToken.sol:257

uint256(cnt) * _value

```
