### ISSUE TITLE
[Feature request] Symbolic trace instruction arguments

### ISSUE THREAD

**Issue by JoranHonig** [ConsenSys/mythril#158]
While using the symbolic trace arguments I found it very useful to see the actual branch conditions.
One thing I was missing though is the symbolic input and output of instructions.

It would be super usefull if instead of just having:
ADD
There would be something like:
ADD calldata_4 + 3 -> [STACK HEAD]

At the moment, trying to reverse engineer a contract will mean a lot of manual keeping track of variables/expressions

**Comment by b-mueller** [comment]
@JoranHonig what feature are you referring to? The CFG export?

**Comment by JoranHonig** [comment]
Yep, I think this is already on the roadmap. So I'll close this
