### ISSUE TITLE
Please help me - Using Kali Linux 2021 and getting error message when trying to analyze .sol file.

### ISSUE THREAD

**Issue by jesseogomez** [ConsenSys/mythril#1588]
## Description

Getting error message in Kali Linux 2021 when trying to analyze a .sol file

## How to Reproduce
```console
└─$ myth analyze /home/oracle/Desktop/test/TERA.sol                                         1 ⨯
mythril.ethereum.util [ERROR]: Encountered a decode error, stdout:, stderr: b'snap-confine has elevated permissions and is not confined but should be. Refusing to continue to avoid permission escalation attacks\n'                                                                           
mythril.interfaces.cli [ERROR]: Traceback (most recent call last):
  File "/home/oracle/.local/lib/python3.9/site-packages/mythril/interfaces/cli.py", line 955, in parse_args_and_execute                                                                         
    address = load_code(disassembler, args)                                                     
  File "/home/oracle/.local/lib/python3.9/site-packages/mythril/interfaces/cli.py", line 698, in load_code                                                                                      
    address, _ = disassembler.load_from_solidity(                                               
  File "/home/oracle/.local/lib/python3.9/site-packages/mythril/mythril/mythril_disassembler.py", line 177, in load_from_solidity                                                               
    self.sigs.import_solidity_file(                                                             
  File "/home/oracle/.local/lib/python3.9/site-packages/mythril/support/signatures.py", line 242, in import_solidity_file                                                                       
    solc_json = get_solc_json(file_path, solc_binary, solc_settings_json)                       
  File "/home/oracle/.local/lib/python3.9/site-packages/mythril/ethereum/util.py", line 90, in get_solc_json                                                                                    
    raise e                                                                                     
  File "/home/oracle/.local/lib/python3.9/site-packages/mythril/ethereum/util.py", line 87, in get_solc_json                                                                                    
    result = json.loads(out)                                                                    
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads                                
    return _default_decoder.decode(s)                                                           
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode                                
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())                                           
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode                            
    raise JSONDecodeError("Expecting value", s, err.value) from None                            
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)               
```

## Expected behavior

I was expected to see any issues or vulnerabilities found on the .sol file.

**Comment by norhh** [comment]
Hi @jesseogomez , what version of mythril are you using?

**Comment by norhh** [comment]
Based on the first line `b'snap-confine has elevated permissions and is not confined but should be. Refusing to continue to avoid permission escalation attacks `

The error seems to be related to snap.
Can you try reinstalling snap.
Or these might be a better threads to checkout

https://stackoverflow.com/questions/70053614/snap-confine-has-elevated-permissions-and-is-not-confined-but-should-be-refusin

https://forum.snapcraft.io/t/solved-snap-application-not-launching-due-to-a-snap-confine-permissions-issue/14753/2

**Comment by jesseogomez** [comment]
Thanks for responding here is the version I have:

Mythril version v0.22.36

**Comment by jesseogomez** [comment]
I did that and now getting the following error:

┌──(oracle㉿oracle)-[~]
└─$ myth analyze /home/oracle/Desktop/test/TERA.sol
mythril.ethereum.util [ERROR]: Encountered a decode error, stdout:, stderr:
b'cannot change profile for the next exec call: No such file or
directory\nsnap-update-ns failed with code 1\n'


mythril.interfaces.cli [ERROR]: Traceback (most recent call last):
  File
"/home/oracle/.local/lib/python3.9/site-packages/mythril/interfaces/cli.py",
line 955, in parse_args_and_execute

    address = load_code(disassembler, args)


  File
"/home/oracle/.local/lib/python3.9/site-packages/mythril/interfaces/cli.py",
line 698, in load_code

    address, _ = disassembler.load_from_solidity(


  File
"/home/oracle/.local/lib/python3.9/site-packages/mythril/mythril/mythril_disassembler.py",
line 177, in load_from_solidity
    self.sigs.import_solidity_file(


  File
"/home/oracle/.local/lib/python3.9/site-packages/mythril/support/signatures.py",
line 242, in import_solidity_file

    solc_json = get_solc_json(file_path, solc_binary, solc_settings_json)


  File
"/home/oracle/.local/lib/python3.9/site-packages/mythril/ethereum/util.py",
line 90, in get_solc_json

    raise e


  File
"/home/oracle/.local/lib/python3.9/site-packages/mythril/ethereum/util.py",
line 87, in get_solc_json

    result = json.loads(out)


  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads


    return _default_decoder.decode(s)


  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode


    obj, end = self.raw_decode(s, idx=_w(s, 0).end())


  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode


    raise JSONDecodeError("Expecting value", s, err.value) from None


json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by norhh** [comment]
@jesseogomez , it seems this is a rabbit hole with snap, As path available to snap doesn't contain the given path.

Can you circumvent using snap?,  Or can you try using mythril's docker container? as these are faster ways to handle this error.

**Comment by jesseogomez** [comment]
I am using Kali Linux,
Do you know if this works on Kali Linux?
Or what’s the easiest way to get it to work on Kali Linux?

**Comment by norhh** [comment]
https://mythril-classic.readthedocs.io/en/master/installation.html#docker for more information

**Comment by jesseogomez** [comment]
Hello bud,
Thank you so much for your help. I have installed Docker and tried running
the following command but getting an error message:

┌──(oracle㉿oracle)-[~]
└─$ docker run mythril/myth --help

           1 ⨯
docker: Got permission denied while trying to connect to the Docker daemon
socket at unix:///var/run/docker.sock: Post
"http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/create":
dial unix /var/run/docker.sock: connect: permission denied.
See 'docker run --help'.

**Comment by jesseogomez** [comment]
Never mind,
I ran the following command to fix this issue: sudo chmod 666
/var/run/docker.sock

**Comment by jesseogomez** [comment]
However I tried running the following command to analyze a ethereum smart
contract and got the following error:

┌──(oracle㉿oracle)-[~]
└─$ docker run mythril/myth analyze /home/oracle/Desktop/test/TERA.sol
mythril.interfaces.cli [ERROR]: Solc experienced a fatal error.

Cannot import url ("/home/oracle/Desktop/test/TERA.sol"): File not found.

**Comment by norhh** [comment]
@jesseogomez you need to mount the docker to the directory of `TERA.sol`. something like `-v /home/oracle/Desktop/test/:/some_tmp`. Now the path will be `/some_tmp/TERA.sol` which will be used like `mythril/myth analyze /some_tmp/TERA.sol`. You can look up more info on `-v` or `--mount` argument of docker.

**Comment by jesseogomez** [comment]
I am really sorry bud, I feel like a newbie trying to do this. I am fairly
new to Kali Linux still learning some commands.

I tried this and it didn't work:

┌──(oracle㉿oracle)-[~]
└─$ docker run -v /home/oracle/Desktop/test/:/some_tmp

           1 ⨯
"docker run" requires at least 1 argument.
See 'docker run --help'.

Usage:  docker run [OPTIONS] IMAGE [COMMAND] [ARG...]

Run a command in a new container

**Comment by jesseogomez** [comment]
Thank you so much it seems to be working now. Do you recommend any
reference document to reference any findings when I scan contracts?

I appreciate you.

**Comment by norhh** [comment]
Hi @jesseogomez, mythril should provide the reason for any detected issue. 
If you need more information on smart contract security vulnerabilities you can use this as a reference https://swcregistry.io/

**Comment by jesseogomez** [comment]
Thank you so much,
Do you know why it takes so long to audit a file with docker? Is that
normal?

**Comment by norhh** [comment]
@jesseogomez , yes, but you can change the settings with `--execution-timeout`

**Comment by jesseogomez** [comment]
Thank you so much! I really appreciate you!

**Comment by jesseogomez** [comment]
Do you know if mythirl scans any version of Solidity ethereum contracts?
Like does it support the latest versions of Solidity or do I need to update
or install multiple solidity versions?

Thank you so much.

**Comment by jesseogomez** [comment]
And are you allowed to give me your Telegram if you have one?
I am actually learning Solidity on my own and would love to make
friendships with people like you.

**Comment by norhh** [comment]
@jesseogomez you don't need to install solidity. you can use the option `--solv <version>`, like `--solv v0.8.0` etc.

You can join MythX discord group, and add me to discord. Here's the link https://discord.com/invite/E3YrVtG

**Comment by jesseogomez** [comment]
Thank you so much for your help.
