### ISSUE TITLE
Inheritance bug in SWC105

### ISSUE THREAD

**Issue by BuggerBag** [ConsenSys/mythril#1592]
Hi, today i test the https://swcregistry.io/docs/SWC-105#multiowned_vulnerablesol
```solidity
pragma solidity ^0.4.23;

/**
 * @title MultiOwnable
 */
contract MultiOwnable {
  address public root;
  mapping (address => address) public owners; // owner => parent of owner
  
  /**
  * @dev The Ownable constructor sets the original `owner` of the contract to the sender
  * account.
  */
  constructor() public {
    root = msg.sender;
    owners[root] = root;
  }
  
  /**
  * @dev Throws if called by any account other than the owner.
  */
  modifier onlyOwner() {
    require(owners[msg.sender] != 0);
    _;
  }
  
  /**
  * @dev Adding new owners
  * Note that the "onlyOwner" modifier is missing here.
  */ 
  function newOwner(address _owner) external returns (bool) {
    require(_owner != 0);
    owners[_owner] = msg.sender;
    return true;
  }
  
  /**
    * @dev Deleting owners
    */
  function deleteOwner(address _owner) onlyOwner external returns (bool) {
    require(owners[_owner] == msg.sender || (owners[_owner] != 0 && msg.sender == root));
    owners[_owner] = 0;
    return true;
  }
}

contract TestContract is MultiOwnable {
  
  function withdrawAll() onlyOwner {
    msg.sender.transfer(this.balance);
  }

  function() payable {
  }

}
```
tip: ```newOwner``` did not check the modifier ```onlyOwner```
from my idea the attack scenario is this: 
1. ```Attacker``` running ```newOwner(Attacker.address)``` then attacker become an owner. 
2. at now, ```Attacker```  running TestContract.withdrawAll() and stole all the funds.

In hardhat, I figure out that ```owners```  (mapping structure) was not readable in TestContract.

I google it, and found https://ethereum.stackexchange.com/questions/63443/solidity-inheritance-cant-read-parents-value-correctly

any body can tell me, how we can implement such scenario as well! thank's alot

**Comment by norhh** [comment]
Just to confirm you need to run `TestContract.newOwner(someAddress)`, since `TestContract.owner` and `MultiOwnable.owner` are different.

**Comment by BuggerBag** [comment]
the issue is solved! Great.
Attacker must connect to ```TestContract``` and insert a record in ```owners```.
then it can stole all the funds. I forgot this step, when I'm coding.
thank's a lot.

**Comment by BuggerBag** [comment]
So, I close this issue.
