### ISSUE TITLE
Invalid NPM block error  

### ISSUE THREAD

**Issue by cybersafehaven** [ConsenSys/mythril#1601]
Trying to analyze with a .sol file throws the attached error. Path for solc has been set and am i the same directory as the .sol files

![image](https://user-images.githubusercontent.com/93176938/157870670-49cc608d-5cf6-498d-a3d3-c625d2c9fcf7.png)

Not sure what I am missing. The command I ran was: myth analyze <mycontract>.sol

**Comment by norhh** [comment]
Hi @cybersafehaven, thanks for logging the bug, can you paste the first 2 to 3 lines of the smart contract?
To circumvent this issue you can use `--solv 0.8.7` argument.

**Comment by cybersafehaven** [comment]
Thanks, forcing the compiler version did circumvent the issue. However, I hit into the issue of not being able to access openzeppelin contracts (from web) which were imported. Any suggestions on that?

**Comment by norhh** [comment]
You need to use solc json with remappings argument to successfully map library-type contract paths.
You can look up this test to see an example of how it's run and how a re-mapping in solc json is written (or you can look up solc documentation) https://github.com/ConsenSys/mythril/blob/8fbe2e2748ea3ada8f4b0a94d9321e8418656704/tests/integration_tests/test_solc_settings.py#L11

But a quicker alternative way is to simply paste all those openzeppelin contracts into your contract before running.
