### ISSUE TITLE
is this contract vulnerable?

### ISSUE THREAD

**Issue by BuggerBag** [ConsenSys/mythril#1603]
Hi, I found new contract 
```solidity
pragma solidity ^0.4.19;

contract Ownable{
    address newOwner;
    address owner = msg.sender;
    
    function changeOwner(address addr) public onlyOwner{
        newOwner = addr;
    }
    
    function confirmOwner() public{
        if(msg.sender==newOwner){
            owner=newOwner;
        }
    }
    
    modifier onlyOwner{
        if(owner == msg.sender)_;
    }
}

contract Token is Ownable{
    address owner = msg.sender;
    function WithdrawToken(address token, uint256 amount,address to) public onlyOwner{
        token.call(bytes4(sha3("transfer(address,uint256)")),to,amount); 
    }
}

contract TokenBank is Token{
    uint public MinDeposit;
    mapping (address => uint) public Holders;
    
     ///Constructor
    function initTokenBank() public{
        owner = msg.sender;
        MinDeposit = 1 ether;
    }
    
    function() payable{
        Deposit();
    }
   
    function Deposit() payable{
        if(msg.value>MinDeposit){
            Holders[msg.sender]+=msg.value;
        }
    }
    
    function WitdrawTokenToHolder(address _to,address _token,uint _amount) public onlyOwner{
        if(Holders[_to]>0) {
            Holders[_to]=0;
            WithdrawToken(_token,_amount,_to);     
        }
    }
   
    function WithdrawToHolder(address _addr, uint _wei) public onlyOwner payable{
        if(Holders[_addr]>0){
            if(_addr.call.value(_wei)()){
                Holders[_addr]-=_wei;
            }
        }
    }
}
```
I found it at https://etherscan.io/address/0x627fa62ccbb1c1b04ffaecd72a53e37fc0e17839#code
it's from https://github.com/smartbugs/smartbugs/blob/master/dataset/reentrancy/0x627fa62ccbb1c1b04ffaecd72a53e37fc0e17839.sol

what is reentrancy scenario? was it vulnerable?!
we have a constructor but it can't pass onlyowner modifier to stole the funds.

**Comment by BuggerBag** [comment]
Becareful, the contract above is Honeypot.
other contract (PrivateBank) is also a Honeypot for ethereum or tron hackers.
PrivateBank address:
https://etherscan.io/address/0xd116d1349c1382b0b302086a4e4219ae4f8634ff#code

more info at: https://www.reddit.com/r/ethereum/comments/7xvoui/exposing_ethereum_honeypots/
more info at: https://www.reddit.com/r/ethdev/comments/7x5rwr/tricked_by_a_honeypot_contract_or_beaten_by/

My Questions:
1) was it vulnerable? or not?
2) can we detect such contract by mythril?

**Comment by norhh** [comment]
There is no re-entrancy issue since withdrawal can only be executed by the owner. (As the name says, it's a Token Bank where only the owner can transfer tokens across different people).
Withdrawals being only allowed to be executed by the owner leans more towards the business logic than a security flaw, If the owner is some "trustworthy" person, it makes sense(Hence the name TokenBank).

**Comment by BuggerBag** [comment]
👍 I agree with you, this smart contract is definitely not vulnerable
