### ISSUE TITLE
mythril.interfaces.cli [ERROR]: IPC / RPC error: 401

### ISSUE THREAD

**Issue by mstrong-tech** [ConsenSys/mythril#1605]
I tried to test contract of Ethereum mainnet but failed. I also tested docker side.
OS: Ubuntu 18.04 (WSL environment)

myth a --infura-id 1 -a 0x0f51bb10119727a7e5eA3538074fb341F56B09Ad
docker run mythril/myth a --infura-id 1 -a 0x0f51bb10119727a7e5eA3538074fb341F56B09Ad

**Comment by norhh** [comment]
Hi @mstrong-tech did you register an infura id from https://infura.io/ . It should be free, mythril can either access mainnet through infura or you can manually run a full ethereum node and use a local host address as an argument to mythril, but the easier way would be using infura api.

**Comment by norhh** [comment]
Hi @aga7hokakological are you sure that the contract exists in the mainnet? Since I could not find it in etherscan. That's probably why infura received empty response.

**Comment by aga7hokakological** [comment]
Thank you for the reply. I was supposed to use `--rpc` too. I have resolve the issue.

**Comment by MajdT51** [comment]
Hi @norhh , I have the same problem

docker run mythril/myth analyze -a 0xdac17f958d2ee523a2206206994597c13d831ec7 --rpc infura-mainnet --infura-id https://mainnet.infura.io/v3/my-id --execution-timeout 240 --rpctls true

Error
`mythril.interfaces.cli [ERROR]: IPC / RPC error: 401`

Thanks
