### ISSUE TITLE
Concolic execution requires additional plugin.

### ISSUE THREAD

**Issue by break1ngpoint** [ConsenSys/mythril#1626]
Hello,

I am trying to use Mythril to perform concolic execution, but it seems that a plugin named "myth_concolic_execution" is required in the first place. And I don't know where it is and how to install it.

https://github.com/ConsenSys/mythril/blob/6b34febd5ec53bd61c2115013bda1e21164ee96d/mythril/interfaces/cli.py#L296-L304

**Comment by norhh** [comment]
Hi @break1ngpoint, That module might not be much of a help. If you want to restrict transactions that you want to execute, you can always try `--transaction-sequence "[[<list of candidate function hashes for 1st tx>], [list of candidate function hashes for 2nd tx], ....[list of candidate function hashes for nth tx]]"`.
For example something like `--transaction-sequence "[[0xe46dcfeb], [0xcbf0b0c0]]"`. This will only execute transactions 0xe46dcfeb and 0xcbf0b0c0 in that following order of function hashes.

**Comment by break1ngpoint** [comment]
> Hi @break1ngpoint, That module might not be much of a help. If you want to restrict transactions that you want to execute, you can always try `--transaction-sequence "[[<list of candidate function hashes for 1st tx>], [list of candidate function hashes for 2nd tx], ....[list of candidate function hashes for nth tx]]"`. For example something like `--transaction-sequence "[[0xe46dcfeb], [0xcbf0b0c0]]"`. This will only execute transactions 0xe46dcfeb and 0xcbf0b0c0 in that following order of function hashes.

Thanks for your advice. But I still have interest in the "concolic" command because the help message says that it is able to flip the desired branches. So how can I test with this command?

**Comment by norhh** [comment]
It is meant to be used with fuzzing as this mode does not detect any vulnerabilities, it just flips branches and gives out an output to be used by a fuzzer.

**Comment by break1ngpoint** [comment]
> It is meant to be used with fuzzing as this mode does not detect any vulnerabilities, it just flips branches and gives out an output to be used by a fuzzer.

Got it. So how can I install the required plugin named "myth_concolic_execution"? It is not located in this repo.

**Comment by norhh** [comment]
At this moment, that plugin isn't public.
