### ISSUE TITLE
Questions about JSON output

### ISSUE THREAD

**Issue by chinhonglee** [ConsenSys/mythril#1645]
When I print out the result from Mythril in JSON and I look at the `tx_sequence`, there are attributes named `address`, `calldata` , `origin` and `input`,  and `value`, would you please explain the differences among these attributes or pointers to the documentation where I can find the definitions of these attributes?

**Comment by norhh** [comment]
Hi, this is EVM terminology, you can refer to the [yellow paper](https://ethereum.github.io/yellowpaper/paper.pdf) for more information.

**Comment by norhh** [comment]
The first 4 bytes of call data which in your case is `0xa9059cbb` displays the function signature.
Yes, in many cases multiple transactions are required to find vulnerabilities.

**Comment by chinhonglee** [comment]
I understand there should be multiple transactions in one sequence, but I see multiple different sequences for the same contract.

**Comment by norhh** [comment]
Arguments are divided by 64 bytes, so the first 64 bytes denotes the address, and the next 64 bytes (pad it with 0s to the right if it's less the 64 bytes) denotes the uint256.

**Comment by chinhonglee** [comment]
I tried to decode the `input` using ABI, but it throws error saying `Tried to read 32 bytes.  Only got 1 bytes`, do you know why?

<img width="1134" alt="Screen Shot 2022-07-13 at 1 37 47 PM" src="https://user-images.githubusercontent.com/108829512/178796124-ddd9e753-809a-4227-a81f-f7b138410533.png">

**Comment by norhh** [comment]
Oops, let me make a correction and be a bit more precise.

If you see a calldata as `0x4a6781a901` here the first 4 bytes are function signature, which is `0x4a6781a9`. The next set of `32 bytes` are the arguments, if there are two arguments of `uint256, uint256` for this function, then the following is true.

function signature:- `0x4a6781a9` as these are the first 4 bytes.
first `uint256`:- the remaining calldata left is only a single byte valued as `01`, so you'll have to append it with 0s to make it 32 bytes, hence it will be `0100000000000000000000000000000000000000000000000000000000000000`
the second `uint256`:- since the remaining calldata is empty now, the second uint is `0000000000000000000000000000000000000000000000000000000000000000` which is `0`.

All these arguments are in hex, you'll have to convert them to `uint`.

For the following error that you encountered you can see that it expected 32 bytes for the second argument, but it only got a single byte, you'll need to append 31 bytes of 0s which is 62 zeros to correct the error.

**Comment by chinhonglee** [comment]
Several follow-up questions

1. You said all these arguments are in hex, you'll have to convert them to uint. How's `0000000000000000000000000108010101010101200201010204010104080404` being hex? I think the only hex in the `input` is `0xa9059cbb` though `0000000000000000000000000108010101010101200201010204010104080404` is a hex after decoding.
2. How come mythril does not output the remaining 62 zeros? Is there any documentation that I can refer to so that I can be aware of this type of thing? For example, the attached screenshot here also throws `InsufficientDataBytes: Tried to read 96 bytes.  Only got 65 bytes` when I try to decode the `input`. Is there a way that I can automatically parse the `input` bytes by looking at the function arguments?

<img width="1109" alt="Screen Shot 2022-07-13 at 5 34 46 PM" src="https://user-images.githubusercontent.com/108829512/178840726-f84391e2-807a-4aaa-b1a8-ec9efde913c6.png">

**Comment by norhh** [comment]
`For example, the attached screenshot here also throws InsufficientDataBytes: Tried to read 96 bytes. Only got 65 bytes when I try to decode the input. Is there a way that I can automatically parse the input bytes by looking at the function arguments?` Input is of chunks of 32 bytes, you'd have to pad it to fit that `32*k` pattern for some integer `k`. You'd just have to pad it and pass it to that corresponding decoder.

`You said all these arguments are in hex, you'll have to convert them to uint. How's 0000000000000000000000000108010101010101200201010204010104080404 being hex? ` Yes, that's hex.

**Comment by chinhonglee** [comment]
Wait just to want to double check, you mean each argument is 32 bytes, but the function signature is 4 bytes, so the total bytes of `input` should be `(32*k)+4`, right?

**Comment by norhh** [comment]
Yes. that's the case, here `k` is a non-negative integer and everything is a `hex`.

**Comment by chinhonglee** [comment]
Then, I don't get the following issue.  Suppose I have a transaction sequence as follows from Mythril. I converted the entire `input` from hex to binary and found there were `800` bits, which I can use to find how many zeros I need to pad. In this case, there are 100bytes, then using the formula, we need `(100-4)/32 = 3 bytes`. Then, I pad `6` zeros to get 3 bytes. But I get `NonEmptyPaddingBytes: Padding bytes were not empty: b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00 '
` when I decode the `input`. How come?

```
{'address': '0x901d12ebe1b195e5aa8748e62bd7734ae19b51f',
 'calldata': '0xbe45fd62000000000000000000000000affeaffeaffeaffeaffeaffeaffeaffeaffeaffe00000000000000000000000000000000000000000000000000000000000000150000000000000000000000000000000000000000000000000000000000000020',
 'input': '0xbe45fd62000000000000000000000000affeaffeaffeaffeaffeaffeaffeaffeaffeaffe00000000000000000000000000000000000000000000000000000000000000150000000000000000000000000000000000000000000000000000000000000020',
 'name': 'transfer(address,uint256,bytes)',
 'origin': '0xaffeaffeaffeaffeaffeaffeaffeaffeaffeaffe',
 'value': '0x0'}
```

**Comment by norhh** [comment]
Are you sure you need padding in this case, the length of the string is 202, `202 - 2 (this is the "0x") - 8 (the 4 bytes of function signature) = 192 = 64*3`

**Comment by chinhonglee** [comment]
> Are you sure you need padding in this case, the length of the string is 202, `202 - 2 (this is the "0x") - 8 (the 4 bytes of function signature) = 192 = 64*3`

Even if I don't pad, I still get this error `NonEmptyPaddingBytes: Padding bytes were not empty: b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00`

You can try it. The address is `0x009c80eff4f5d8fca2b961ee607b00b9c64ef9f2`

**Comment by norhh** [comment]
Oops, `bytes` was one of the argument Nevermind. I'll likely implement abi-support when Source Code is provided this weekend. That should potentially simplify your work.

**Comment by chinhonglee** [comment]
If `bytes` is one of the arguments, how can I possibly decode that? Is that also a `32` bytes?

**Comment by norhh** [comment]
For dynamic types, the first data of calldata are static types such as the `uint, bool .. etc` of types. These have fixed 32 bytes width, the other classes are dynamic types such as `bytes, array[] ...` these point to some corresponding location in the calldata. So you'll have to extend the calldata to the corresponding location. In some cases mythril might generate a calldata that the program can run, but it's not possible to directly decode it since it's considered invalid, like in this case (although you can execute the program with such an input, the abi programs such as `eth-abi` consider them as invalid).

**Comment by lesMN** [comment]
Hello, what parameter in this json otuput indicates the line number of an issue?

**Comment by norhh** [comment]
@lesMN  Here is a sample output of json
```
{
	"error": null,
	"issues": [{
		"address": 153,
		"code": "selfdestruct(addr)",
		"contract": "Suicide",
		"description": "Any sender can cause the contract to self-destruct.\nAny sender can trigger execution of the SELFDESTRUCT instruction to destroy this contract account. Review the transaction trace generated for this issue and make sure that appropriate security controls are in place to prevent unrestricted access.",
		"filename": "solidity_examples/suicide.sol",
		"function": "kill(address)",
		"lineno": 7,
		"max_gas_used": 563,
		"min_gas_used": 468,
		"severity": "High",
		"sourceMap": "107:18",
		"swc-id": "106",
		"title": "Unprotected Selfdestruct",
		"tx_sequence": {
			"initialState": {
				"accounts": {
					"0xaffeaffeaffeaffeaffeaffeaffeaffeaffeaffe": {
						"balance": "0x8",
						"code": "",
						"nonce": 0,
						"storage": "{}"
					},
					"0xdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef": {
						"balance": "0x0",
						"code": "",
						"nonce": 0,
						"storage": "{}"
					}
				}
			},
			"steps": [{
				"address": "",
				"calldata": "",
				"input": "0x608060405234801561001057600080fd5b50610163806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c8063cbf0b0c014610030575b600080fd5b61004a60048036038101906100459190610100565b61004c565b005b600073ffffffffffffffffffffffffffffffffffffffff168173ffffffffffffffffffffffffffffffffffffffff16141561009a578073ffffffffffffffffffffffffffffffffffffffff16ff5b50565b600080fd5b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b60006100cd826100a2565b9050919050565b6100dd816100c2565b81146100e857600080fd5b50565b6000813590506100fa816100d4565b92915050565b6000602082840312156101165761011561009d565b5b6000610124848285016100eb565b9150509291505056fea26469706673582212208b0a67e22376e2583a68bbebc260765f737bbb8f4e832f1eb7346a53d77b6cd064736f6c634300080c0033",
				"name": "unknown",
				"origin": "0xaffeaffeaffeaffeaffeaffeaffeaffeaffeaffe",
				"value": "0x0"
			}, {
				"address": "0x901d12ebe1b195e5aa8748e62bd7734ae19b51f",
				"calldata": "0xcbf0b0c00000000000000000000000000000000000000000000000000000000000000000",
				"input": "0xcbf0b0c00000000000000000000000000000000000000000000000000000000000000000",
				"name": "kill(address)",
				"origin": "0xdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef",
				"value": "0x0"
			}]
		}
	}],
	"success": true
}
```

**Comment by lesMN** [comment]
Thank you @norhh  for your answer.  I ran mythril with the options:  **-a** and **-o jsonv2**  
But in the json output I haven't "lineno".

**Comment by norhh** [comment]
Hi @lesMN, with `-o json` you get `lineno`, with `-o jsonv2` you get `SourceMap` which can be decoded to a line number.

**Comment by lesMN** [comment]
Hi @norhh, thank you for your feedback. With **-o json** also I haven't the line number.
 Can you please, share with a documentation about the link between source map and line number?

**Comment by norhh** [comment]
Hi @lesMN, are you running Mythril on sourcecode or Bytecode/addresses?

**Comment by lesMN** [comment]
@norhh  run Mythril with the contract **address**.

**Comment by norhh** [comment]
@lesMN , in such cases you cannot get the line number, since contracts on-chain do not contain source code.

**Comment by lesMN** [comment]
HI @norhh , OK. Thank you for your answer.
