### ISSUE TITLE
Mythril Always Seems To Exit With Code 0, Even If It Should Not

### ISSUE THREAD

**Issue by TheDarkula** [ConsenSys/mythril#1650]
## Description

As stated in the title, running mythril never throws an error code.

## How to Reproduce
Example CI runs can be found [here](https://github.com/themeliolabs/bridge-sol/runs/7327550085?check_suite_focus=true) and [here](https://github.com/themeliolabs/bridge-sol/runs/7327677872?check_suite_focus=true).

```console
$ myth analyze src/BridgeProxy.sol --solc-json mythril.config.json
```

## Expected behavior

I would expect `myth` to exit with `1` if it finds any vulnerabilities.

## Environment

This is running on a Linux, self-hosted runner for github actions.

- Mythril version: `v0.23.4`
- Solidity compiler and version: `0.8.13`
- Python version: `3.8.10`

**Comment by norhh** [comment]
Mythril wasn't exactly implemented as a CI-based tool, hence it doesn't exit with non-zero code unless it crashes.

Currently, you can write a script, which executes mythril using JSON output flag, and checks if the length of the `issues` field is greater than `0` to throw an error flag.
something like 
```
os.system("./myth a <file_path> -o json > output.json")
with open("output.json") as f:
  json_data = json.load(f)
  if len(json_data["issues"] > 0:
    exit(1)
```

**Comment by TheDarkula** [comment]
@norhh Ah, thank you for the information.

I ended up writing this solution:
```
      - name: Run Mythril Analysis On BridgeProxy
        run: myth analyze src/BridgeProxy.sol --solv ${{ env.SOLIDITY_VERSION}} --solc-json mythril.config.json --parallel-solving -o json > mythril_output

      - name: Check BridgeProxy Output
        shell: bash
        run: if [[ $(cat mythril_output | jq '.error == null') ]]; then exit 0; else echo $(cat mythril_output | jq .issues) && exit 1; fi
```
