### ISSUE TITLE
File "/home/ubuntu/.local/lib/python3.10/site-packages/mythril/disassembler/asm.py", line 5, in <module>     from collections import Generator ImportError: cannot import name 'Generator' from 'collections' (/usr/lib/python3.10/collections/__init__.py)

### ISSUE THREAD

**Issue by abdel2991** [ConsenSys/mythril#1656]
Hello, 

I have the error below with the commande  myth analyze or myth --version :

File "/home/ubuntu/.local/lib/python3.10/site-packages/mythril/disassembler/asm.py", line 5, in <module>
    from collections import Generator
ImportError: cannot import name 'Generator' from 'collections' (/usr/lib/python3.10/collections/__init__.py) 

Can you help please ? 

Thanks

**Comment by norhh** [comment]
Hi @abdel2991, can you try using mythril with a python 3.9 virtual environment.
