### ISSUE TITLE
False positive: "integer overflow" 

### ISSUE THREAD

**Issue by ksloven** [ConsenSys/mythril#166]
I'm getting an 'integer overflow' from a few contracts scans with mythril. The warning also shows up on the OpenZeppelin ERC-20 standard token implementation.

Another e.g scanning this contract shows an int overflow
https://etherscan.io/token/0x58b6a8a3302369daec383334672404ee733ab239

==== Integer Overflow ====
Type: Warning
Contract: 0x58b6a8a3302369daec383334672404ee733ab239
Function name: _function_0xd73dd623
PC address: 3368
A possible integer overflow exists in the function _function_0xd73dd623.
The addition or multiplication may result in a value higher than the maximum representable integer.

**Comment by b-mueller** [comment]
Hi @ksloven,

Thanks for the report! We're aware of this particular issue: The add function in SafeMath.sol contains an integer overflow but rolls back the transaction after the overflow. It's explained in my [recent article](https://media.consensys.net/detecting-batchoverflow-and-similar-flaws-in-ethereum-smart-contracts-93cf5a5aaac8?source=activity---post_recommended_rollup).

We're working on ways of eliminating this, but it still needs some experimentation.

@JoranHonig, FYI here is the output for the [OpenZeppelin](https://github.com/OpenZeppelin/openzeppelin-solidity) ERC20 token:

```
$ myth -x contracts/token/ERC20/StandardToken.sol 
==== Exception state ====
Type: Informational
Contract: StandardToken
Function name: increaseApproval(address,uint256)
PC address: 4018
A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. 
--------------------
In file: contracts/math/SafeMath.sol:45

assert(c >= a)

--------------------

==== Integer Overflow  ====
Type: Warning
Contract: StandardToken
Function name: increaseApproval(address,uint256)
PC address: 4005
A possible integer overflow exists in the function `increaseApproval(address,uint256)`.
The addition or multiplication may result in a value higher than the maximum representable integer.
--------------------
In file: contracts/math/SafeMath.sol:44

a + b

--------------------
```

**Comment by JoranHonig** [comment]
Should be fixed in #184

**Comment by JoranHonig** [comment]
This can be closed now

**Comment by JoranHonig** [comment]
I found the problem, a LOG2 instruction is not handled correctly by the TaintRunner

**Comment by JoranHonig** [comment]
Should be fixed with: https://github.com/b-mueller/laser-ethereum/pull/22#partial-pull-merging

**Comment by ksloven** [comment]
Hi, maybe i'm doing something wrong but I installed mythril on iMac.

>KLMs-iMac:~ KLM$ pip show laser-ethereum
Name: laser-ethereum
Version: 0.17.5
Summary: Symbolic Ethereum virtual machine
Home-page: UNKNOWN
Author: Bernhard Mueller
Author-email: bernhard.mueller11@gmail.com
License: MIT

Running it against the contract above doesn't even show the other informational bugs.
Running it against the "batchOverflow" bug, as per the post herehttps://media.consensys.net/detecting-batchoverflow-and-similar-flaws-in-ethereum-smart-contracts-93cf5a5aaac8) yeilds the following:
KLMs-iMac:~ KLM$ myth -xia 0xC5d105E63711398aF9bbff092d4B6769C82F793D -v1
INFO:root:Using INFURA for RPC queries
INFO:root:LASER EVM initialized with dynamic loader: None
INFO:root:- Entering function 0xC5d105E63711398aF9bbff092d4B6769C82F793D:_function_0x06fdde03
INFO:root:- Entering function 0xC5d105E63711398aF9bbff092d4B6769C82F793D:_function_0x095ea7b3
INFO:root:- Entering function 0xC5d105E63711398aF9bbff092d4B6769C82F793D:_function_0x18160ddd
INFO:root:- Entering function 0xC5d105E63711398aF9bbff092d4B6769C82F793D:_function_0x23b872dd
INFO:root:- Entering function 0xC5d105E63711398aF9bbff092d4B6769C82F793D:_function_0x313ce567
INFO:root:- Entering function 0xC5d105E63711398aF9bbff092d4B6769C82F793D:_function_0x3f4ba83a
INFO:root:- Entering function 0xC5d105E63711398aF9bbff092d4B6769C82F793D:_function_0x54fd4d50
INFO:root:- Entering function 0xC5d105E63711398aF9bbff092d4B6769C82F793D:_function_0x5c975abb
INFO:root:- Entering function 0xC5d105E63711398aF9bbff092d4B6769C82F793D:_function_0x70a08231
INFO:root:- Entering function 0xC5d105E63711398aF9bbff092d4B6769C82F793D:_function_0x83f12fec
INFO:root:- Entering function 0xC5d105E63711398aF9bbff092d4B6769C82F793D:_function_0x8456cb59
INFO:root:- Entering function 0xC5d105E63711398aF9bbff092d4B6769C82F793D:_function_0x8da5cb5b
INFO:root:- Entering function 0xC5d105E63711398aF9bbff092d4B6769C82F793D:_function_0x95d89b41
INFO:root:- Entering function 0xC5d105E63711398aF9bbff092d4B6769C82F793D:_function_0xa9059cbb
INFO:root:- Entering function 0xC5d105E63711398aF9bbff092d4B6769C82F793D:_function_0xdd62ed3e
INFO:root:- Entering function 0xC5d105E63711398aF9bbff092d4B6769C82F793D:_function_0xf2fde38b
INFO:root:Execution complete
INFO:root:889 nodes, 888 edges, 15906 total states
INFO:root:Starting analysis
INFO:root:Executing <module 'delegatecall' from '/usr/local/lib/python3.6/site-packages/mythril/analysis/modules/delegatecall.py'>
INFO:root:Executing <module 'dependence_on_predictable_vars' from '/usr/local/lib/python3.6/site-packages/mythril/analysis/modules/dependence_on_predictable_vars.py'>
INFO:root:Executing <module 'depreciated_ops' from '/usr/local/lib/python3.6/site-packages/mythril/analysis/modules/depreciated_ops.py'>
INFO:root:Executing <module 'ether_send' from '/usr/local/lib/python3.6/site-packages/mythril/analysis/modules/ether_send.py'>
INFO:root:Executing <module 'exceptions' from '/usr/local/lib/python3.6/site-packages/mythril/analysis/modules/exceptions.py'>
INFO:root:Executing <module 'external_calls' from '/usr/local/lib/python3.6/site-packages/mythril/analysis/modules/external_calls.py'>
INFO:root:Executing <module 'integer' from '/usr/local/lib/python3.6/site-packages/mythril/analysis/modules/integer.py'>
INFO:root:Executing <module 'suicide' from '/usr/local/lib/python3.6/site-packages/mythril/analysis/modules/suicide.py'>
INFO:root:Executing <module 'transaction_order_independence' from '/usr/local/lib/python3.6/site-packages/mythril/analysis/modules/transaction_order_independence.py'>
INFO:root:Executing <module 'unchecked_retval' from '/usr/local/lib/python3.6/site-packages/mythril/analysis/modules/unchecked_retval.py'>
**The analysis was completed successfully. No issues were detected.**

**Comment by b-mueller** [comment]
I'm getting the same result with 0.17.5.

@JoranHonig, we should add those integer overflows to our test suite and make sure that they are still detected after adding fp detection code.

**Comment by b-mueller** [comment]
> we should add those integer overflows to our test suite

...not the complete batchOverflow contract though, that takes very long to analyze!

**Comment by b-mueller** [comment]
What's interesting: When I analyze BECToken.sol from source, the integer overflow is detected successfully.

```
$ myth -x BECToken.sol:BecToken
==== Exception state ====
Type: Informational
Contract: BecToken
Function name: transfer(address,uint256)
PC address: 5260
A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. 
--------------------
In file: BECToken.sol:28

assert(c >= a)

--------------------

==== Integer Overflow  ====
Type: Warning
Contract: BecToken
Function name: transfer(address,uint256)
PC address: 5247
A possible integer overflow exists in the function `transfer(address,uint256)`.
The addition or multiplication may result in a value higher than the maximum representable integer.
--------------------
In file: BECToken.sol:27

a + b

--------------------

==== Integer Overflow  ====
Type: Warning
Contract: BecToken
Function name: batchTransfer(address[],uint256)
PC address: 2460
A possible integer overflow exists in the function `batchTransfer(address[],uint256)`.
The addition or multiplication may result in a value higher than the maximum representable integer.
--------------------
In file: BECToken.sol:257

uint256(cnt) * _value

--------------------
```

So maybe the integer overflow module isn't the cause of the false negative?

**Comment by ksloven** [comment]
I concur the local scan does detect the int overflow. so maybe the flaw lies elsewhere

**Comment by JoranHonig** [comment]
@b-mueller I checked the BECToken contract before creating the pr. But we could try to get more overflow cases in the test suite

**Comment by JoranHonig** [comment]
Maybe the contract at the address is different due to solidity

**Comment by b-mueller** [comment]
According to Etherscan, compiler version is solc v0.4.19+commit.c4cbbb05

**Comment by JoranHonig** [comment]
I'm currently running analysis with several older versions to find which change caused the problem

**Comment by JoranHonig** [comment]
At 8605d252797bcd582881edca0f1f887443d4bd47 shows the vulnerabilities.
At 37ed299f2295c4284c5005574ed68e5b78202388(newer) we dont see the vulnerabilities.

The only change here is the following:
To:
```
    if type(op0) is not int:
        op0_value = int(str(model.eval(op0, model_completion=True)))
        model0 = _try_constraints(node.constraints, [op0 != op0_value])

    if type(op1) is not int:
        op1_value = int(str(model.eval(op1, model_completion=True)))
        model1 = _try_constraints(node.constraints, [ op1 != op1_value])
```
From:
```
    if type(op0) is not int:
        op0_value = int(str(model.eval(op0, model_completion=True)))
        model0 = _try_constraints(node.constraints, [constraint, op0 != op0_value])

    if type(op1) is not int:
        op1_value = int(str(model.eval(op1, model_completion=True)))
        model1 = _try_constraints(node.constraints, [constrant, op1 != op1_value])
```
Applying the change to:8605d252797bcd582881edca0f1f887443d4bd47, does not change its output.
Therefore I believe that indeed the integer module is not the problem here

**Comment by JoranHonig** [comment]
@b-mueller I think this last problem, where contracts from the network are somehow not correctly analysed belongs in a separate issue.

Also, once https://github.com/b-mueller/laser-ethereum/pull/22 is merged. This pr should be closed.

**Comment by ksloven** [comment]
quick question @JoranHonig @b-mueller , initially we opened this issue for the int overflow false positive when running the scan on-chain, correct? But it appears that the false positive int overflow is not detected when running the scan on-chain. Does the fix (https://github.com/ConsenSys/mythril/pull/184) also address the issue of an `assert` that reverts the int overflow when it occurs as per the post (https://media.consensys.net/detecting-batchoverflow-and-similar-flaws-in-ethereum-smart-contracts-93cf5a5aaac8); specifically 

>  function add(uint256 a, uint256 b) internal pure returns (uint256) {
    uint256 c = a + b;
    **assert(c >= a);**
    return c;
  }

**Comment by JoranHonig** [comment]
@ksloven, the pr is merged so you can try it ;). But yes the overflow for a + b is not showed anymore
