### ISSUE TITLE
Split Dockerfile into two

### ISSUE THREAD

**Issue by joshuata** [ConsenSys/mythril#167]
I have been working on testing, and created a dockerfile for the test machine. However, it is pretty heavy since it has 3 full python installs and build-essentials. I think it would be a good idea to create two dockerfiles, one for testing and on for usage. They could be pushed up under different tags so that the default would be the thin mythril execution container, and the other would be just for matrix testing the tools (and laser as well)

@birdofpreyru Where should I set this up? Also, is there a reason that the projects are added into `/home/mythril` rather than the CircleCI default of `/root/project`? If we moved to separate containers we could use the CI default for testing, and then install to a different location for users.

**Comment by b-mueller** [comment]
FYI the mythril-ci repo was private, I made it public just now.

**Comment by b-mueller** [comment]
Can we close this issue?

**Comment by joshuata** [comment]
Yep
