### ISSUE TITLE
Question about mythril analyzer

### ISSUE THREAD

**Issue by awlliom** [ConsenSys/mythril#1678]
Hi
I was trying to run mythril analyzer on BECToken contract ([link](https://github.com/smartbugs/smartbugs/blob/master/dataset/arithmetic/BECToken.sol)). I ran below commands
```
time myth -v4 analyze --loop-bound 2 dataset/arithmetic/BECToken.sol
```
```
time myth -v4 analyze -t 1 dataset/arithmetic/BECToken.sol
```
```
time myth -v4 analyze --execution-timeout 3600 --parallel-solving dataset/arithmetic/BECToken.sol:BecToken 
```
```
time myth -v4 analyze --max-depth 55 --parallel-solving dataset/arithmetic/BECToken.sol:BecToken 
```
```
time myth -v4 analyze --max-depth 100 --execution-timeout 3600 dataset/arithmetic/BECToken.sol:BecToken
```
```
time myth -v4 analyze --max-depth 30 --solver-timeout 1000 --parallel-solving dataset/arithmetic/BECToken.sol:BecToken
```
None of the commands above could find integer overflow in BECToken contract. I finally got the correct results from the command below:
```
time myth -v4 analyze --solver-timeout 60000 --parallel-solving dataset/arithmetic/BECToken.sol:BecToken
```
![Screenshot from 2022-09-03 23-29-03](https://user-images.githubusercontent.com/52703400/188304611-82b2eaa8-0526-44bc-9074-1fc0f1b25cfc.png)
```
$ myth version
Mythril version v0.23.3
```
as you can see it ended in more than 2 hours. so my question is, is it normal? or am I missing something in running my commands? I know symbolic execution tools should take their time so like if I have a huge contract with hundreds of lines of codes it will take few days maybe a week or two to analyze it, am I right?

Thank you

**Comment by norhh** [comment]
You can execute this with a single transaction like this.
`./myth -v4 a <file> -t 1 --solver-timeout 60000`
Although on my PC, the default solver timeout of (25000/ 25 seconds) is enough.

**Comment by awlliom** [comment]
@norhh 
I executed this command but analyzer didn't find any issue.
```
mythril.analysis.security [INFO]: Starting analysis
mythril.mythril.mythril_analyzer [INFO]: Solver statistics: 
Query count: 660 
Solver time: 626.6787559986115
The analysis was completed successfully. No issues were detected.

myth -v4 a dataset/arithmetic/BECToken.sol -t 1 --solver-timeout 25000  1112.60s user 251.43s system 184% cpu 12:19.37 total
```

**Comment by norhh** [comment]
Based on your output, you'd need `--solver-timeout 60000`

**Comment by norhh** [comment]
Are you running it on a server/VM/ or a Docker? Because the solver time to query ratio is quite high.

**Comment by awlliom** [comment]
@norhh 
I'm running it on my own PC. 
is it always possible to get the results with a single transaction?

**Comment by norhh** [comment]
Yes

**Comment by awlliom** [comment]
@norhh 
ok thank you
has anyone ever gathered some best practices of using options for different contracts? for example, "best flags to execute for an ERC20 contract that lower the effective run time" or something like that

**Comment by norhh** [comment]
`
@norhh
ok thank you
has anyone ever gathered some best practices of using options for different contracts? for example, "best flags to execute for an ERC20 contract that lower the effective run time" or something like that
`
It's dependent on the contract and the type of vulnerabilities that you want to find. But there are no best practices per contract type as of now.

**Comment by awlliom** [comment]
@norhh 
thank you for your time
