### ISSUE TITLE
Installation instructions problems

### ISSUE THREAD

**Issue by alcuadrado** [ConsenSys/mythril#171]
Hi,

I have two issues with the installation instructions available at the README:

1. It's not mentioned there, but in macos you need to install `leveldb` before installing `mythril` from `pip`. `brew install leveldb` worked for me. If you don't install it first, `plyvel`'s compilation will fail.

2. It's not unclear if this message "If you plan to analyze Solidity code you'll also need the native version of solc. Solcjs is not supported." also applies when running `myth --truffle`, as you have to compile everything first.

**Comment by b-mueller** [comment]
Thanks @alcuadrado! We clearly need better installation instructions, see also #129. I'll add the leveldb requirement to the README for now.

For Truffle projects, the bytecode is taken from the compiled output files, so theoretically you should get away with having only `solcjs` (which Truffle depends on).

**Comment by b-mueller** [comment]
Per-OS installation instructions added. Truffle support will be re-assessed at a later point (might become a separate tool).
