### ISSUE TITLE
Integer Overflow for array lengths can't happen

### ISSUE THREAD

**Issue by k06a** [ConsenSys/mythril#175]
I think this kind of warnings should be suppressed:

```
==== Integer Overflow  ====
Type: Warning
Contract: Multiownable
Function name: _function_0x3e41d5eb
PC address: 1869
A possible integer overflow exists in the function `_function_0x3e41d5eb`.
The addition or multiplication may result in a value higher than the maximum representable integer.
--------------------
In file: Multiownable.json:251

owners.length + newOwners.length
```

**Comment by b-mueller** [comment]
Hmm but purely theoretically, they can happen?

I wonder if we should have more detailed classifications, e.g. classify integer overflows that are very unlikely to happen as "informational".

**Comment by k06a** [comment]
@b-mueller absolutely not possible: https://www.techsupportalert.com/content/what-is-256-bit.htm

**Comment by b-mueller** [comment]
I agree that they absolutely can't happen by incrementally increasing the array length. This would take longer than counting all hydrogen atoms in the universe.

That said, `array.length` is a regular uint256 in storage, e.g. located at storage[0] if the array is the first variable declared. You can explicitly set this value to anything you want. In fact, decreasing array length explicitly is a common replacement for pop() in Solidity (page 23 of the [HITB paper](https://github.com/b-mueller/smashing-smart-contracts/blob/master/smashing-smart-contracts-1of1.pdf) has an example for setting the length of an array to 2**256 - 1). 

So I could absolutely imagine situations where an overflow is possible - it depends what else can happen to the length variable. You can't be 100% sure without having the full context & multi-transactional analysis (which unfortunately we don't have yet).

**Comment by k06a** [comment]
@b-mueller in this case I agree :)

**Comment by b-mueller** [comment]
Thanks @k06a :)

I'll leave this open for now as something we want to address, but that probably take foundational improvements to the analysis engine.
