### ISSUE TITLE
`myth -j` creates massive log file

### ISSUE THREAD

**Issue by makoto** [ConsenSys/mythril#177]
## Symptom

Calling myth with `-j` on my project (300 LOC in total) took very long time and generated over 90mb of json object dump

## Version
0.16.31      

## Steps to recreate

```
git clone https://github.com/makoto/blockparty.git
cd blockparty
git checkout 1c2884cc9262c5fc8aba026720b289620c00bceb
myth -j ./statespace.json contracts/Conference.sol --max-depth 8
$ ls -ltr statespace.json 
-rw-r--r--  1 makoto  staff  92582854  5 May 20:52 statespace.json
```

**Comment by b-mueller** [comment]
Thanks Makoto, we'll try to address this soon.

**Comment by JoranHonig** [comment]
There is probably a state explosion due to:
```
	function attend(address[] _addresses) external onlyAdmin onlyActive{
		for(uint i=0;i<_addresses.length;i++){
			address _addr = _addresses[i];
			require(isRegistered(_addr));
			require(!isAttended(_addr));
			emit AttendEvent(_addr);
			participants[_addr].attended = true;
			attended++;
		}
}
```

**Comment by b-mueller** [comment]
Could this be related to #111? It seems that loops don't always trigger the depth limit..

**Comment by JoranHonig** [comment]
Not sure, I'll look into it

**Comment by JoranHonig** [comment]
@b-mueller Yes, it seems to be the same problem. There is a state explosion due to of the inverted jumpi condition branch

**Comment by b-mueller** [comment]
Second example from #111:

The loop in `getTransactionCount()` causes the interpreter to enter an endless loop if max-depth>=10.

```
    function getTransactionCount(bool pending, bool executed)
        public
        constant
        returns (uint count)
    {
        for (uint i=0; i<transactionCount; i++)
            if (   pending && !transactions[i].executed
                || executed && transactions[i].executed)
                count += 1;
    }
```

**Comment by b-mueller** [comment]
I assume this will be solved if we implement the wordlist algorithm instead of recursive `_sym_exec`.
