### ISSUE TITLE
What's the best way to view the HTML report?

### ISSUE THREAD

**Issue by yomiso** [ConsenSys/mythril#180]
How to get a responsive, clear view of the HTML report? I tried to open in Firefox and Chrome. But I can only see small green boxes in both cases.

**Comment by JoranHonig** [comment]
You can use scrolling to zoom, and dragging to move around. You can also drag boxes around.
Or is that not what you meant?

**Comment by b-mueller** [comment]
I assume you mean the markdown report?

There's a nice little trick by @maurelian:

```
$ pip install grip
$ grip <(myth -x token.sol -o markdown)
```

This will start a web server & you can view the markdown in your browser.

**Comment by JoranHonig** [comment]
There has been no response so I'm closing this issue. @yomiso If you feel your question is not answered feel free to respond to this issue and we'll reopen.
Otherwise you could swing by on gitter: https://gitter.im/ConsenSys/mythril
Which will probably work better for questions like this.
