### ISSUE TITLE
Mythril Dockerfile for Alpine 

### ISSUE THREAD

**Issue by golra03** [ConsenSys/mythril#183]
Docker has adopted Alpine as base linux version for its obvious advantages. Current Mythril dockerfile is using base as Ubuntu. Is there any Alpine version available? 

Building Mythril on Alpine base is giving issues.. 
a. First option by directly installing mythril via pip3
*****************
—> _RUN pip3 install mythril_
 Collecting BTrees (from mythril)
  Downloading https://files.pythonhosted.org/packages/09/e6/85b7fffb792e1cd7c4820487b641162f1412b8ed1f3bc6a22118a4bbfb81/BTrees-4.5.0.tar.gz (171kB)

**Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-ahh4kiv7/BTrees/
The command '/bin/sh -c pip3 install mythril' returned a non-zero code: 1**

b. Second option by building mythril
_—>RUN git clone https://github.com/b-mueller/mythril/
—>RUN cd mythril && python setup.py install__

Installed /usr/lib/python3.6/site-packages/pytest-3.5.1-py3.6.egg
Searching for plyvel
Reading https://pypi.org/simple/plyvel/
Downloading https://files.pythonhosted.org/packages/e0/7b/9302e33972c4af861f5a425cb37468b4dbb17d7a4d282a657bfdb240055e/plyvel-1.0.4.tar.gz#sha256=134e78519403a6f71f1e66df945763413c48d0f6dec02e1a61f55adf0f83106d
Best match: plyvel 1.0.4
Processing plyvel-1.0.4.tar.gz
Writing /tmp/easy_install-nn06nj9u/plyvel-1.0.4/setup.cfg
Running plyvel-1.0.4/setup.py -q bdist_egg --dist-dir /tmp/easy_install-nn06nj9u/plyvel-1.0.4/egg-dist-tmp-5ivvbrxa
**warning: no files found matching 'plyvel/*.pxi'
error: Setup script exited with error: command 'gcc' failed with exit status 1
The command '/bin/sh -c cd mythril && python setup.py install' returned a non-zero code: 1**
******************

Any help will be appreciated.

**Comment by b-mueller** [comment]
I'm now aware of anyone running Mythril on Alpine. Seems like several dependencies fail installing? I'm afraid we don't have the resources to address this right now, but we'd definitely grateful for a contribution to the docs or an Alpine Dockerfile!
