### ISSUE TITLE
slow analysis speed on bytes-typed public storage variable variable

### ISSUE THREAD

**Issue by suhabe** [ConsenSys/mythril#186]
Running Mythril on the following program takes 41 seconds, which seems slow for Mythril when compared to its speed on more complex programs. Interestingly, if the `public` modifier is removed, the analysis takes only 0.5 seconds.

```
contract Benchmark {
    bytes public x;
}
```

```
vagrant@vagrant:~$ time myth -x host/benchmarks/perf1.sol 
The analysis was completed successfully. No issues were detected.

real	0m40.484s
user	0m40.240s
sys	0m0.192s
```

**Comment by b-mueller** [comment]
> Interestingly, if the public modifier is removed, the analysis takes only 0.5 seconds.

The reason for this is that solc automatically creates an accessor function for state variables that have the `public` modifier. Maybe this function leads to a large state space (could be a loop over the length of the `bytes` variable).

**Comment by suhabe** [comment]
Does Mythril represent as `bytes`-typed variables as having a symbolic length?
