### ISSUE TITLE
Latest mythril isn't working on macOS

### ISSUE THREAD

**Issue by chapati23** [ConsenSys/mythril#197]
Hey :)
first of all: thanks for this tool, we have integrated into our CI and i love the increased confidence about potential security issues that it adds to our development process!

### Issue
Latest version of mythril doesn't work on macOS. Getting the following exception when running `myth`:

```
Traceback (most recent call last):
  File "/usr/local/bin/myth", line 6, in <module>
    import mythril.interfaces.cli
  File "/usr/local/lib/python3.6/site-packages/mythril/interfaces/cli.py", line 16, in <module>
    from mythril.mythril import Mythril
  File "/usr/local/lib/python3.6/site-packages/mythril/mythril.py", line 20, in <module>
    from mythril.ether.soliditycontract import SolidityContract
  File "/usr/local/lib/python3.6/site-packages/mythril/ether/soliditycontract.py", line 4, in <module>
    from laser.ethereum import helper
ImportError: cannot import name 'helper'
```

Guess it's missing a `helper` file somewhere?

### Versions
* mythril: 0.17.8
* macOS 10.13.4
* pip: 10.0.1
* python: 3.6.5
* solc: 0.4.23+commit.124ca40d.Darwin.appleclang
* leveldb: 1.20.2

Overall I followed this install readme to the letter: https://github.com/ConsenSys/mythril/wiki/Install-from-Pypi-on-Mac-OS

**Comment by JoranHonig** [comment]
This might be caused by the way helper is imported.
Could you try it with the following fork?
https://github.com/JoranHonig/mythril/tree/bugfix/importhelper

**Comment by b-mueller** [comment]
> first of all: thanks for this tool, we have integrated into our CI and i love the increased confidence about potential security issues that it adds to our development process!

OT: That's great to hear! Would you be able to share a guide of how you set this up in whatever CI environment you use?

**Comment by chapati23** [comment]
@b-mueller unfortunately not anymore because it stopped working with one of the last updates :-/

this was our script (run in a `centos7` VM) that recently stopped working:

```
#!/bin/bash

set -euf -o pipefail

figlet -f small "Mythril"

cd /tmp

# Install mythril build dependancies
yum install openssl-devel wget bzip2 -y --quiet

# Install minimal anaconda python at /opt.
wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh --quiet
chmod +x Miniconda3-latest-Linux-x86_64.sh
chronic ./Miniconda3-latest-Linux-x86_64.sh -b -p /opt/python3

# Install mythril in /opt
printf "\n\n"
echo "Installing mythril, this can take 10-15 minutes 🕙"
printf "\n\n"
cd /opt
git clone https://github.com/ConsenSys/mythril
cd /opt/mythril
chronic /opt/python3/bin/python3 setup.py install

# NOTE: $PATH does not include python3 or mythril so these binaries need to be called with their full path
```

**Comment by JoranHonig** [comment]
I'll create a pr

**Comment by b-mueller** [comment]
Merged :)
