### ISSUE TITLE
Possible regression?

### ISSUE THREAD

**Issue by birdofpreyru** [ConsenSys/mythril#200]
While working on integration testing solution for Mythril API, we got integration tests done for mythril v0.15.9. Now I run them for the latest mythril v0.17.9, and I see the following mismatch between expected and actual responses:
![screenshot](https://user-images.githubusercontent.com/20144632/40190047-24c0086c-59fe-11e8-811f-b6e70a628ce8.png)

I have not look into this closely, but it might be some regression.

**Comment by b-mueller** [comment]
@birdofpreyru I tried running the mythril-api tests locally but didn't get them to work.

What is the bytecode submitted in the test above?

**Comment by b-mueller** [comment]
The reason was a change in laser-ethereum which caused states losing their associated function names. Should be fixed, can you retest?

**Comment by JoranHonig** [comment]
The other differences are probably caused by z3 giving different proofs, I think in the mythril tests this was solved by just not checking that part

**Comment by birdofpreyru** [comment]
@b-mueller @JoranHonig it looks much better to me now:

![image](https://user-images.githubusercontent.com/20144632/40480470-eb1a7916-5f4e-11e8-8389-a78ea169cbb9.png)

The function names are back, and the absence of *Integer Underflow* warning, I guess, relates to intentional changes in laser, thus legit?

**Comment by b-mueller** [comment]
Yes, most likely. We added false positive detection to the integer module which eliminates some issues.

**Comment by birdofpreyru** [comment]
@b-mueller @JoranHonig now I have found that the latest pair of *laser-ethereum* and *mythril* from `master` branch fail, for example, on `$ myth -xc abcc` with the following error
```
root@4b8e9a2487db:/home# myth -xc abcc
Traceback (most recent call last):
  File "/usr/local/bin/myth", line 4, in <module>
    __import__('pkg_resources').run_script('mythril==0.17.12', 'myth')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 742, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1503, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.17.12-py3.6.egg/EGG-INFO/scripts/myth", line 9, in <module>
    mythril.interfaces.cli.main()
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.17.12-py3.6.egg/mythril/interfaces/cli.py", line 205, in main
    'text': report.as_text(),
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.17.12-py3.6.egg/mythril/analysis/report.py", line 54, in as_text
    filename = list(self.issues.values())[0].filename
IndexError: list index out of range
```
the same works fine with their 0.17.2 versions

**Comment by b-mueller** [comment]
Hmm I can't reproduce this with mythril + laser-ethereum master:

```
$ $MYTH -x abcc
Input file not found: abcc
```

But I'm getting various issues since the b-mueller/laser-ethereum#36. E.g.:

```
$ $MYTH -x solidity_examples/underflow.sol 
python3(22073,0x7000014a8000) malloc: *** error for object 0x7f96c7a6b400: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

See also #212

**Comment by b-mueller** [comment]
Yeah, right. I'm getting the same results as you.

**Comment by JoranHonig** [comment]
@birdofpreyru I found the problem and I'll make a separate issue for that if thats okay

**Comment by b-mueller** [comment]
@birdofpreyru the `abcc` issue is now separated into in #215.

The other issues discussed in this thread should be resolved as well. I'm rolling back some of the latest commits that are currently causing issues so that we have a 100% working setup for the mythril/laser merge. Will open a separate issue for that.
