### ISSUE TITLE
Specifying bytecode's ABI

### ISSUE THREAD

**Issue by franklinsch** [ConsenSys/mythril#202]
When using the `-c` option, I'm guessing Mythril doesn't know which public functions can be called on the contract.

Is there an option to specify a JSON ABI to help Mythril find the functions to analyze?

**Comment by b-mueller** [comment]
Hi @franklinsch, it does identify public functions automatically. This happens implicitly because only public functions have entries in the function hash table.

At the moment there are no plans to add ABI support to the `myth` utility. We're planning to create a separate tool meant for developers that will have better support for use cases where you have access to the source code and/or ABI.

**Comment by b-mueller** [comment]
I haven't found any documentation on this either. But the bytecode of a compiled contract starts with a jump table (sequence of JUMPI instructions) that compares the first 4 bytes of the calldata with each function signature hash. `external` and `public` functions are included in that table, but `internal` and `private` ones aren't -> thus they cannot be called.

**Comment by franklinsch** [comment]
Ah, that's quite neat. This is specific to Solidity contracts, though. I wanted to use Mythril for Flint (https://github.com/franklinsch/flint) contracts, for which the bytecode is laid out differently.

**Comment by b-mueller** [comment]
Interesting! In principle Mythril should follow all executable code paths no matter what language was used, but it wouldn't be able to recognize the start of a function unless there is a Solidity-type jump table. 

Do you have some example bytecode?

**Comment by franklinsch** [comment]
In this [gist](https://gist.github.com/franklinsch/4212632c36fe6c3e568494c5f4714610), I've uploaded a Flint contract, its IR form as inline assembly in a Solidity file, and the final binary.

**Comment by b-mueller** [comment]
Hmm the CFG for Mythril generates for that bytecode doesn't look right. 

```
$ myth -g graph.html --max-depth 128 -c "[bytecode]"
```

Is this the contract creation bytecode or the runtime bytecode (the one that ends up in the contract account)?

Also, can you explain briefly how function calls are resolved in Flint?

**Comment by franklinsch** [comment]
This is the contract creation bytecode. (running `solc --bin` on the Solidity IR file).

Function calls are also resolved by looking at the first four bytes of Keccak hash (like Solidity). This is performed in the fallback function of a Solidity function (see [line 213](https://gist.github.com/franklinsch/4212632c36fe6c3e568494c5f4714610#file-simpleauction-sol-L213), which is the entry point of all function calls)

**Comment by nbanmp** [comment]
Closing issue, as it is over a year old and is stale. Feel free to open a new issue if specifying the ABI for a contract will provide a significant improvement.
