### ISSUE TITLE
ImportError: cannot import name 'compile_solidity'

### ISSUE THREAD

**Issue by bishesh16** [ConsenSys/mythril#204]
Hi,
I am getting errors while running the analysis.py from [here](https://gist.github.com/b-mueller/cece053c95adf28f42a557a8a14a82df). it seems like the `compile_solidity` method has been removed from the util package. Is there a workaround ?

here is the error i'm getting. 

```
Traceback (most recent call last):
  File "analysis.py", line 3, in <module>
    from mythril.ether.util import compile_solidity
ImportError: cannot import name 'compile_solidity'
```

Thanks

**Comment by bishesh16** [comment]
I have tried that but now I'm getting an error for another package.

here's the error message: 
```
Traceback (most recent call last):
  File "./analysis.py", line 4, in <module>
    from mythril.ether.soliditycontract import SolidityContract
  File "/Users/bishesh16/mythril/mythril/ether/soliditycontract.py", line 1, in <module>
    import laser.ethereum.helper as helper
ModuleNotFoundError: No module named 'laser'
```

**Comment by bishesh16** [comment]
yes it is. Anyways I was trying to follow the story by @b-mueller from [here](https://media.consensys.net/how-formal-verification-can-ensure-flawless-smart-contracts-cbda8ad99bd1). And I think the [gist](https://gist.github.com/b-mueller/cece053c95adf28f42a557a8a14a82df) file is probably outdated as the mythril version has changed a lot from since the time the article was written. 

myth cli itself is working fine though...

**Comment by b-mueller** [comment]
@bishesh16 you're right, the interface has changed since I wrote that article. For example, to compile a Solidity file and execute the bytecode symbolically you'd now do:

```
from mythril.ether.soliditycontract import SolidityContract
from mythril.analysis.symbolic import SymExecWrapper
from mythril.ether import util

contract = SolidityContract(filename)
sym = SymExecWrapper(contract, util.get_indexed_address(0))
```

There's changes in how state is represented as well, so the old script is pretty useless. I'll update it when I find some time & we're also planning to write better documentation on the various classes (contributions are welcome of course :))

**Comment by JoranHonig** [comment]
It seems like your question is answered now, nice!
@bishesh16 if you have any questions you can always hop by on our gitter channel https://gitter.im/ConsenSys/mythril
