### ISSUE TITLE
Implement a more organized development process

### ISSUE THREAD

**Issue by b-mueller** [ConsenSys/mythril#213]
Due to the growing amount of coders & amount of TopCoder challenges coming in, I feel that things are getting a little out of control. Moving forward, we should implement a standard development process. My proposal:

1. Merge laser-ethereum and Mythril repos. This will be done in an upcoming TopCoder challenge;
2. Set up the Mythril board on waffle.io with a SCRUM-like structure (if it isn't already);
3.  Introduce user stories, sprints and stand-ups (maybe twice weekly) with the core team and someone from TopCoder. Other contributors can join voluntarily.
4. Bring on a deployment manager who is in charge of creating releases and driving the development process in accordance to the roadmap.

parent of #223

**Comment by birdofpreyru** [comment]
2. I would just keep on using Trello board for overall planning, using separate GitHub repos and boards there for planning related to these repos (to keep technicalities out of Trello).

**Comment by JoranHonig** [comment]
1. What is the timeframe on that challenge? As merging the repositories would help with keeping track of issues (in waffle)
2. Waffle is using a kanban like setup, which is compatible with scrum (so I guess that is already done). 
@birdofpreyru I agree
3. Good idea, with the upcoming brainstorm for laser we can start building a backlog for laser. For mythril it would be also useful to translate the roadmap into stories and tasks (preferably prioritized)
4. Can we maybe take on a product owner(/have somebody take up this role)? It seems like "driving the development process in accordance to the roadmap" describes that role.

**Comment by b-mueller** [comment]
> I would just keep on using Trello board for overall planning, using separate GitHub repos and boards there for planning related to these repos (to keep technicalities out of Trello).

Agreed.

> What is the timeframe on that challenge? As merging the repositories would help with keeping track of issues (in waffle)

The merging challenge should run this week I hope.

> Can we maybe take on a product owner(/have somebody take up this role)? It seems like "driving the development process in accordance to the roadmap" describes that role.

That's probably [this guy](https://new.consensys.net/careers/?gh_jid=1127282). Until we have that person, it'll probably be shared between me, Sergey and the soon-to-be-onboarded "deployment manager".

**Comment by JoranHonig** [comment]
We have completed all the points listed, so I think this issue can be closed. Further improvements on the process can probably be done/discussed during sprint meetings
