### ISSUE TITLE
What does the warning "WARNING:root:Unsupported memory symbolic index" mean? 

### ISSUE THREAD

**Issue by Ethanwl** [ConsenSys/mythril#214]
How can I solve it?

**Comment by Ethanwl** [comment]
@b-mueller  Thank you for your reply! Though there are just some warnings at the beginning or the end, the analysis works well.

**Comment by Ethanwl** [comment]
@b-mueller Thank you for your reply! Though there are some warnings at the beginning or the end, the analysis works well.

**Comment by b-mueller** [comment]
Actually this is a debugging message that's not supposed to be printed to stdout.I fixed this in laser-ethereum.
