### ISSUE TITLE
Worklist implementation

### ISSUE THREAD

**Issue by JoranHonig** [ConsenSys/mythril#222]
Currently laser uses a dfs based algorithm to symbolically execute a contract.
This will be changed to a worklist based implementation, allowing for easy integration of different execution strategies

child of #203

**Comment by b-mueller** [comment]
Should fix #177, #186

**Comment by b-mueller** [comment]
Depending on how long it takes to implement this, we might need some workaround for preventing infinite analysis loops in the meantime?

**Comment by JoranHonig** [comment]
I started working on this, https://github.com/JoranHonig/mythril/tree/features/worklist contains the current state of the work. I hope to have something working at wednesday

**Comment by JoranHonig** [comment]
I'm almost done with implementing the worklist feature, the only problem are the analysis modules that used the full symbolic return values from the current implementation (while the new laser will use the actual return symbol)
