### ISSUE TITLE
Merge laser-ethereum into Mythril

### ISSUE THREAD

**Issue by b-mueller** [ConsenSys/mythril#223]

**Comment by b-mueller** [comment]
This is an ongoing TopCoder challenge.

https://www.topcoder.com/challenges/30065733

**Comment by birdofpreyru** [comment]
Just for a record: we got a good submission from the related Topcoder challenge. I have asked the winner to go on, and create PR request with the merge, on the way updating it with the latest changes is Laser / Mythril, and fixing a few issues highlighted by reviewers.

**Comment by b-mueller** [comment]
This should be ready to merge?

**Comment by birdofpreyru** [comment]
Yes, the winner of the challenge should create PR today. Wanna him to do it, so that he can leverage any changes in the repos, happening since his submission.

**Comment by birdofpreyru** [comment]
@b-mueller merged. Pending is to add docs page from LASER to Mythril wiki (into _For Developers_ section), we'll do it tomorrow.

The merged version passes all existing tests. In case there are any other merge-related fixes to do, let's handle them separately.
