### ISSUE TITLE
Implement precompiled contracts

### ISSUE THREAD

**Issue by b-mueller** [ConsenSys/mythril#224]
The EVM specification defines four so-called ‘precompiled’ contracts. The four contracts in addresses 1, 2, 3 and 4 execute the elliptic curve public key recovery function (ecrecover), the SHA2 256-bit hash scheme, the RIPEMD 160-bit hash scheme and the identity function respectively.

Call to the ecrecover precompiled contract in assembly:

CALL 0x1

Currently, LASER-Ethereum ignores calls to the precompiled contracts. In this task, the precompiled contracts are to be implemented. When a precompiled contract is called, the result should be computed using the appropriate Python cryptographic libraries. Also create tests for each of the four precompiles.

Go-Ethereum implementation:

https://github.com/ethereum/go-ethereum/blob/master/core/vm/contracts.go

This is an ongoing TopCoder challenge:

https://www.topcoder.com/challenges/30065730

**Comment by b-mueller** [comment]
We have a seemingly working implementation or precompiles from TopCoder. The question is, can we merge it into laser while fundamental changes are being implemented. Needs to be coordinated with @suhabe.

**Comment by b-mueller** [comment]
@birdofpreyru I'll test this once #223 is done.

**Comment by birdofpreyru** [comment]
@b-mueller #223 is done :) Any news here?

**Comment by b-mueller** [comment]
Sorry, haven't gotten to this yet, will review ASAP.

**Comment by b-mueller** [comment]
OK, I merged the changes to laser and did a bit of testing. Seems all good so far!

I didn't yet integrate the tests into our test suite, please ask the candidate to do that later (he can do it when he's hopefully onboarded as "release manager").

**Comment by birdofpreyru** [comment]
so, do we onboard him as _release manager_, or are you still considering other options?
