### ISSUE TITLE
Update expected output in API tests

### ISSUE THREAD

**Issue by b-mueller** [ConsenSys/mythril#239]
**Describe the bug**
Merging #236 passes the Mythril-CLI tests but causes the [API tests to fail](https://circleci.com/gh/ConsenSys/mythril/285) because an additional issue is detected.

**Expected behavior**
This is expected behavior assuming that the issue is not a false positive. @birdofpreyru, please update the expected outputs to include this issue.

**Comment by birdofpreyru** [comment]
Updated
