### ISSUE TITLE
Test behavior depends on unspecified Python 3.6 behavior

### ISSUE THREAD

**Issue by joshuata** [ConsenSys/mythril#245]
**Describe the bug**
The test suite fails when run under python 3.6, specifically the `test_json_report` and the `test_get_source_info_without_name_gets_latest_contract_info` test. This is because they rely on ordering behavior, namely json key ordering and issue map insertion ordering respectively.

**To Reproduce**
1. See pull request #242  where the tests are run under both 3.5 and 3.6

**Expected behavior**
The test suite should pass under both versions

**Comment by JoranHonig** [comment]
@joshuata Was this fixed with https://github.com/ConsenSys/mythril/pull/242?

**Comment by joshuata** [comment]
No. It is caused by the truffle tests, and I don't know enough about the system to feel comfortable changing them. If we don't need both tests, we could drop `test_get_source_info_without_name_gets_latest_contract_info` which would resolve the problem.
