### ISSUE TITLE
Improve Wiki: Build The Docker Image

### ISSUE THREAD

**Issue by rocky** [ConsenSys/mythril#251]
It would be nice to give an example of how to run the docker image after building it.
Also, I'd suggest adding a tag to the to the build command, e.g. 

```
docker build -t mythril mythril
```

Also it would be nice to give a couple of simple example on how to run via docker. For example: 

```
docker run mythril --help
docker run mythril -d -c "0x6060"
```

I'd update the wiki directly, but it seems to be protected from general update.

**Comment by birdofpreyru** [comment]
Thanks for the suggestions, I have added these to the Wiki
