### ISSUE TITLE
Simple function is not flagged as containing an int overflow

### ISSUE THREAD

**Issue by fernand** [ConsenSys/mythril#266]
I'm trying to understand why the following contract isn't flagged as containing a potential integer overflow:
```
contract Test {
    function test(uint256 input1, uint256 input2) returns(uint256) {
        uint256 res = input1 * input2;
        return res;
    }
}
```
I used `--solc-args=--optimize` to get simpler EVM instructions.
It looks like Z3 is trying to solve the following constraints and returns `unsat` for the relevant `MUL` operation in the `integer` module `_check_integer_overflow` function:
```
[Not(ULT(calldatasize_Test, 4)), UDiv(calldata_Test_0,
      26959946667150639794667015087019630673637144422540572481103610249216) &
 4294967295 ==
 3951741217, callvalue == 0, Or(And(ULT(calldata_Test_4*calldata_Test_36,
            calldata_Test_36),
        calldata_Test_4 != 0),
    And(ULT(calldata_Test_4*calldata_Test_36,
            calldata_Test_4),
        calldata_Test_36 != 0))]
```
However if I try to initialize these constraints myself by setting all the calldata/value vars to `BitVec(256)` the solver *does* find a solution (as it should).
What am I missing?

**Comment by b-mueller** [comment]
I think it has to do with the way we qualify integer overflows as false positives. Overflows are not reported unless they change the account state or impact program flow.

If let's say you would also *use* your vulnerable function in an if-statement, the integer overflow would be reported:

```
contract Test {

    function test(uint256 input1, uint256 input2) returns(uint256) {
        uint256 res = input1 * input2;
        return res;
    }

    function useTest(uint256 input1, uint256 input2) returns(bool) {
    	if(test(input1, input2) < 1000) {
    		return true;
    	}

    	return false;
    }
}
```

Or, say you'd save the result in a state variable:

```
contract Test {

    uint256 res;

    function test(uint256 input1, uint256 input2) returns(uint256) {
        res = input1 * input2;
    }
}
```

Does that make sense?

**Comment by fernand** [comment]
Thanks for the response! The issue was actually that the solver was timing out because of `s.set("timeout", 100000)` in `get_model`. With more time it does find a solution. That solution then would get filtered out for the reasons you mentioned. FYI the first contract you shared is flagged as containing an overflow and not the second one.

**Comment by b-mueller** [comment]
> FYI the first contract you shared is flagged as containing an overflow and but the second one.

They both get flagged for me:

```
$ myth -x test2.sol 
==== Integer Overflow  ====
Type: Warning
Contract: Unknown
Function name: test(uint256,uint256)
PC address: 145
A possible integer overflow exists in the function `test(uint256,uint256)`.
The addition or multiplication may result in a value higher than the maximum representable integer.
--------------------
In file: test2.sol:6

input1 * input2

--------------------
```

Weird that you're getting solver timeouts, I don't think it it's a difficult task to solve. Can you share more details about your hardware and OS?

**Comment by fernand** [comment]
My bad both do get flagged if I increase the timeout. I have a mid 2014 macbook pro (2.2GHz i7) on High Sierra. Takes around 16 seconds to solve for this example.

**Comment by fernand** [comment]
Most other model checks I've tried take around second (or less) on my computer, for some reason Z3 is struggling on this constraint set.

**Comment by JoranHonig** [comment]
Providing timing settings through the cli is something we can look at with the implementation of symbolic execution strategies. 
But besides that, @fernand it seems that your question is answered. If not feel free to reopen this issue or hop by on gitter https://gitter.im/ConsenSys/mythril
