### ISSUE TITLE
Analysis Module: Best Practices Dumpfile

### ISSUE THREAD

**Issue by chronaeon** [ConsenSys/mythril#267]
# Detection issue:
Everything commented `// bad` on the [Solidity Recommendations](https://consensys.github.io/smart-contract-best-practices/recommendations/) page.

## Description: 
Provided in link above.

## Link
^

## Implementation details:Initial implementation ideas/instruction
Mythril already catches all of the Solidity problems mentioned in the link above.  I recommend additionally autogenerating a dump file that clumps best practices excerpts with the associated problems.

So it would look like:

`$ myth calls.sol -x`
Which returns this:
```
==== Message call to external contract ====
Type: Informational
Contract: Caller
Function name: thisisfine()
PC address: 691
This contract executes a message call to to another contract. Make sure that the called contract is trusted and does not execute user-supplied code.
--------------------
In file: solidity_examples/calls.sol:16

fixed_address.call()

--------------------
```
and then gives this message:
```
Total Errors: 1
Errors along with associated best practices have been dumped to calls_sol_analysis.html
```
which then would contain everything under the "External Calls" section [here](https://consensys.github.io/smart-contract-best-practices/recommendations/) and group similar errors/mistakes together. 

So if `Total Errors:` returned `16` and three of those were "External Calls", then the `myth -x` output would dump along with the associated best practices excerpt(s) pertaining to those three, and then repeating group/dump, group/dump errors for each error type out of the total of `16`.

To keep the HTML document from getting too cluttered with text, an auto-generated table of contents at the top could link a single heading to each associated group of errors.

**Comment by JoranHonig** [comment]
Hi @chronaeon, we were already planning on implementing something like this.

See #225, in which case issues would be printed with a link to our wiki, the first page is here: https://github.com/ConsenSys/mythril/wiki/Integer-Overflow

I'm not sure what is better when thinking about usability/maintainability

**Comment by chronaeon** [comment]
@JoranHonig Cool, then I'll close this one and focus on improving/adding to #225
