### ISSUE TITLE
Both pip3 and docker installations stuck

### ISSUE THREAD

**Issue by kyriediculous** [ConsenSys/mythril#268]
**Describe the bug**
both docker and pip3 installs fail to process beyond 
```
Building wheels for collected packages: z3-solver
  Running setup.py bdist_wheel for z3-solver ... |

```

**Expected behavior**
Expect it to continue

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04 

**Additional context**
As good as clean VM.

**Comment by birdofpreyru** [comment]
@kyriediculous have you tried to wait? Installation of `z3-solver`, indeed, takes some time, before printing much on the progress into the console log.

**Comment by kyriediculous** [comment]
Yes been waiting for 20 minutes so far :D 
I'll wait a couple more. 

aplogies if my issue is a little premature.

**Comment by b-mueller** [comment]
Yep, z3-solver builds native packages which takes a long time. It will finish eventually.

**Comment by birdofpreyru** [comment]
Ok, forget about building Docker images yourself, I have setup automated Docker releases as a part of our CI/CD setup. Please refer to the updates instructions: https://github.com/ConsenSys/mythril/wiki/With-Docker

Basically, all you need now:
```
$ docker pull mythril/myth
$ docker run mythril/myth --help
```
