### ISSUE TITLE
Jinja2 Import Error From Fresh Ubuntu Install

### ISSUE THREAD

**Issue by Ramlall** [ConsenSys/mythril#270]
I installed Mythril on my Ubuntu 16.04 Virtual Machine using the instructions found on the [wiki page here](https://github.com/ConsenSys/mythril/wiki/Install-from-Pypi-on-Ubuntu). 

When I tried to do a `myth -x contract.sol` on one of the example contracts, I got an import error.

![mytherr](https://user-images.githubusercontent.com/6525145/41305368-af95996a-6e40-11e8-910d-19cabaa3605c.png)

I googled around and doing 

`sudo pip3 install --upgrade jinja2`

fixed the error and allowed me to use the myth command to test contracts.

So maybe either:
1. Include that command in the wiki instructions (although this is not the neatest solution).
2. Package that command somewhere  in the mythril install process. (Perhaps in `pip3 install mythril`.)

Just bringing it up since it was giving me problems. I'm not sure if this affects every other fresh install.

**Comment by JoranHonig** [comment]
Hi Ramiall, thanks for the report!
Did pip3 install mythril complete successfully? Because jinja 2 should actually be installed during the execution of that command

**Comment by joshuata** [comment]
It may be a problem with a system version of jinja2. We may want to add a requirement of `jinja2>=2.9` to make sure our version is new enough to have the method available

**Comment by Ramlall** [comment]
Ah unfortunately I closed the terminal and didn't check to see if it installed successfully or not, so I'm not sure if it's a version issue or an install failure.

**Comment by bordalix** [comment]
I had the exact same problem yesterday, and also solve it with `sudo pip3 install --upgrade jinja2`

**Comment by JoranHonig** [comment]
@joshuata, so jinja2>=2.9 should be required by mythril?

At the moment it isn't so that would indeed explain why the installation failed for @Ramlall and @bordalix.

**Comment by JoranHonig** [comment]
@norhh  Can you take this issue?
