### ISSUE TITLE
False Positive on Public Enums

### ISSUE THREAD

**Issue by suhabe** [ConsenSys/mythril#277]
Mythril 0.18.4 reports false positive on public enum storage variables.

```
pragma solidity ^0.4.19;

contract Benchmark {
    enum State {
        s1
    }
    State public state;
}
````

````
==== Exception state ====
Type: Informational
Contract: Unknown
Function name: _function_0xc19d93fb
PC address: 100
A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. 
--------------------
In file: public_storage_enum.sol:7

State public state

--------------------
```

**Comment by b-mueller** [comment]
My intuition is that this is an assert in a auto-generated accessor similar to #243 and #276.

**Comment by suhabe** [comment]
Manticore doesn't seem to reach an 0xfe on this benchmark, unlike the dynamic array in #276. Don't know why.

**Comment by chronaeon** [comment]
Added tto FAQ

**Comment by JoranHonig** [comment]
@chronaeon I'm not sure that this issue can be closed,  it seems from @suhabe s comment that it is possible to prevent this false positive.

**Comment by chronaeon** [comment]
@JoranHonig Would it make sense to close the multiple false positive issues and create a new one that encapsulates the new direction?

**Comment by JoranHonig** [comment]
@chronaeon I'm not sure about that. The different false positives might be caused by different aspects in mythril. So we'd need to validate/triage them first to see if they are the same false positive.
If two false positives have the same root cause, I'm fine with merging them

**Comment by rocky** [comment]
Here is a related thought regarding this. With interaction with static analysis we can know this is an enum and adjust severity. The ethereum best practices guide says that smaller datatypes like int8's are more vulnerable than int256's. But on the other hand, if we can do some static analysis and determine this is boilerplate code, that might change things drastically. Dunno yet. 

And I am not suggesting, the false positive not get tracked down.

**Comment by JoranHonig** [comment]
This seems to be fixed with the current version of master, closing
