### ISSUE TITLE
False Positive on Require Check

### ISSUE THREAD

**Issue by suhabe** [ConsenSys/mythril#278]
Mythril 0.18.4 reports a false positive on the following benchmark:

```
pragma solidity ^0.4.19;

contract Benchmark {

    enum State {
        s1
    }
    State private state;

    function f() {
        require(state == State.s1);
    }
}
```

```
vagrant@vagrant:~/host/benchmarks$ myth -x enum_check.sol 
==== Exception state ====
Type: Informational
Contract: Unknown
Function name: f()
PC address: 123
A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. 
--------------------
In file: enum_check.sol:11

state == State.s1

```

**Comment by b-mueller** [comment]
I'm not exactly sure why (too tired to think much right now) but for some reason there's an assert in there that fails when `State private state` is uninitialized.

![screen shot 2018-06-15 at 22 34 43](https://user-images.githubusercontent.com/5194767/41476709-8b1d0b28-70ec-11e8-9256-2e30cbf172a7.png)

**Comment by suhabe** [comment]
Manticore doesn't seem to reach an 0xfe on this benchmark, unlike the dynamic array in #276. Don't know why.

**Comment by JoranHonig** [comment]
This seems to be fixed with the current version of master, closing
