### ISSUE TITLE
Documentation docker

### ISSUE THREAD

**Issue by JoranHonig** [ConsenSys/mythril#279]
We got a question from @svantetobias on the gitter channel on how to use docker on a solidity file.

To use the docker container on solidity files extra parameters need to be passed to ```docker run```, see also the discussion on gitter and https://ethereum.stackexchange.com/questions/51304/docker-mythril-cant-connect-to-ganache-or-local-sol-contracts.

It would be usefull to add instructions for this on the documentation wiki page for the docker container

**Comment by birdofpreyru** [comment]
@JoranHonig Great catch! Yeah, when you do:
```
$ docker run mythril/myth -x MyContract.sol
```
Docker tries to find `MyContract.sol` inside the container, thus does not find it.

Probably, the most convenient way to deal with this would be to add an option in `myth` to read Solidity contracts from `stdin`, and then, I guess, we should be able to pipe contracts in like:
```
$ more MyContract.sol | docker run mythril/myth --stdin
```
What do you think?

**Comment by birdofpreyru** [comment]
The other option, which should work already, is to use [docker cp](https://docs.docker.com/engine/reference/commandline/cp/) to copy contract(s) into container first, then running analysis on files inside the container.

**Comment by JoranHonig** [comment]
@birdofpreyru I think the solution provided in the stackexchange post is quite good.
```
docker run -v $(pwd):/working-dir mythril/myth -x /working-dir/MyContract.sol
```
This way you can just mount your working directory in the docker container

**Comment by birdofpreyru** [comment]
Oh, missed that comment and option. I added it to the doc, thus closing the ticket.
