### ISSUE TITLE
“Invalid JSON in signatures file" when generating json format output

### ISSUE THREAD

**Issue by TonyZhouCH** [ConsenSys/mythril#294]
**Describe the bug**
When I use mythril to output a json format,  a bug may occur which shows:  "error": "Invalid JSON in signatures file /home/xxx/.mythril/signatures.json\nExpecting ',' delimiter: line 1 column 254411 (char 254410)"

**Expected behavior**
I assume some certain contracts can cause this problem.

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04

**Additional context**
+ I can fix it by deleting the signatures.json in /.mythril, and mythril goes well then.
+ I open the signatures.json to find the error, I notice the problem is the "0x" is missing in column 254411 in my signatures.json. (sorry I have deleted it, so I can't give more details)
+ What is signatures.json??

**Comment by JoranHonig** [comment]
@TonyZhouCH Thanks for the report, could you upload you signatures.json file? That might help us a lot. The signatures file is a mapping from hexadecimal function identifiers to their function description. You might find the following page interesting: https://ethereum.stackexchange.com/questions/7602/how-does-the-evm-find-the-entry-of-a-called-function

**Comment by TonyZhouCH** [comment]
@JoranHonig  Hi, I have uploaded two signatures.json, which are both wrong. Hope this helps.

[signatures.zip](https://github.com/ConsenSys/mythril/files/2133399/signatures.zip)

**Comment by shashank-srikant** [comment]
I faced a similar issue. 

Although the symptom's the same, my issue stemmed from the fact that i was running Mythril in parallel on several cores. Write/Update-operations to the common `signatures.json` file seemed to cause content inconsistency, leading to a invalid JSON format.

As soon as i remove parallelism and run this on a single core, the issue doesn't seem to surface.

**Comment by TonyZhouCH** [comment]
@shashank-srikant  It seems your explanation is very convincing，beacuse I run mythril in parallel. Thanks a lot!

**Comment by JoranHonig** [comment]
Thanks for the discussion, I believe we don't currently support concurrent runs of mythril. But imo this would be a super useful feature, with some important usecases. We'll probably pick this up in the coming weeks :+1:

**Comment by JoranHonig** [comment]
Should be fixed with #308
