### ISSUE TITLE
”Integer Overflow“ output field has one extra space

### ISSUE THREAD

**Issue by TonyZhouCH** [ConsenSys/mythril#295]
When reporing overflow bug, the "Integer Overflow" field has one extra space.

https://github.com/ConsenSys/mythril/blob/35ff192db18fee8bca1543c3e3a46c03942c59b9/mythril/analysis/modules/integer.py#L88

**Comment by norhh** [comment]
Thanks for mentioning, removed the extra space.

**Comment by norhh** [comment]
It seems it might take some time as integration tests are to be changed

**Comment by birdofpreyru** [comment]
done
