### ISSUE TITLE
myth --truffle not catching all the errors.

### ISSUE THREAD

**Issue by simondlr** [ConsenSys/mythril#297]
**Describe the bug**
```myth --truffle``` not catching all the errors. Running checks via commandline solc catches the errors, but not when doing mythril --trufle

**To Reproduce**

Fork: https://github.com/UjoTeam/contracts-badges/tree/fix/audit.
Run: truffle compile
Run: myth --truffle

**Expected behavior**
There's overflows to be caught in PatronageBadges.sol, but it's showing that there's no issues found.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: OS X
 - Version: Sierra.

**Additional context**
Running the ```myth -xo markdown contracts/UjoPatronageBadges.sol > patronage_mythril.md``` produces an incorrect report (duplicating incorrectly) as can be seen in the markdown in that branch above. This might be related.

**Comment by norhh** [comment]
using --truffle uses max depth of 10 compared to default '-x' where max depth of  22 is used

**Comment by norhh** [comment]
Also as of now --max-depth is not considered when --truffle is used as argument, that should be fixed
