### ISSUE TITLE
Symbolic names containing operand suffixes can be missleading

### ISSUE THREAD

**Issue by LoCorVin** [ConsenSys/mythril#303]
When data comes from memory or calldata the operands that are appended to describe the index should be simplified, and if still symbolic should be surrounded with brackets. If not some constraints or symbolic contents are ambiguous:
BitVec("mem_" + str(op0), 256) **->** mem_128 + calldatavalue_contractname_someindex **better** mem[128 + calldatavalue_contractname_someindex] **or** mem_at[128 + calldatavalue_contractname_someindex]

state.stack.append(BitVec("calldata_" + str(environment.active_account.contract_name) + "_" + str(op0), 256)) -> calldata_4 + 32 **better** calldata[4+32] **or** calldata_at[4+32] **with simplify** calldata[36] and calldata_at[36] respectively

**Comment by JoranHonig** [comment]
Hi @LoCorVin, that seems like a reasonable change to laser. Would you like to contribute?

**Comment by LoCorVin** [comment]
Definitely :) I hope i will find all the spots where changes have to be made to stay consistent :)

**Comment by JoranHonig** [comment]
This issue can be closed now right? Due to #310
