### ISSUE TITLE
Mythril's results are't consistent

### ISSUE THREAD

**Issue by TonyZhouCH** [ConsenSys/mythril#305]
**Describe the bug**
Guys, sorry to bother you again.
I'm not sure it is a bug. I use mythril to detect the vulnerability of one contract. However, I find out that the results reported by mythri are different.
I use json output format.Here is my result.
+ 1st time：Issues contain
    + Message call to external contract
    + Multiple Calls
    + Exception state
+ 2nd time: No issues
+ 3rd time: Issues contain
    + Message call to external contract
    + Exception state
    + Integer Overflow

It confuses me.How does it happen?
I uploaded the source code and result so you can inspect it.
[evalgit.zip](https://github.com/ConsenSys/mythril/files/2157577/evalgit.zip)

**Comment by JoranHonig** [comment]
Hi @TonyZhouCH , thanks for the report!. What kind of system are you running mythril on?

mythril.analysis.solver uses a timeout of 10.000 when using z3, could you try with a few different values (20.000, 1.000, 50.000) to see if they give consistent results?

Mythril is actually being ran on very different machines, so we're thinking about providing cli options with different profiles (longer/smaller timeouts, more/less symbolic execution)

**Comment by JoranHonig** [comment]
@TonyZhouCH If I analyze the solidity file locally I don't have this problem, even with lowering the timeout by a lot.
Could it be that you were running an old version of mythril?

**Comment by JoranHonig** [comment]
So this turned out to be the same issue as in #329, closing this issue so all discussion can happen there.

To be short, use the following:
```
myth -x contract_file_name.sol:ContractName
```
