### ISSUE TITLE
Geth LevelDB search returns incorrect contract addresses

### ISSUE THREAD

**Issue by b-mueller** [ConsenSys/mythril#306]
**Describe the bug**

When using the leveldb search feature, search results contain invalid contract addresses. 

**To Reproduce**

Run the following with the current master build:

```
$ $MYTH --leveldb ~/Library/Ethereum/geth/chaindata/ --search "func#withdrawAll()#"
Matched contract with code hash 971879f99a024e31a9c70b67af4fb797
Address: 0x000b9d8799c3f14d0522717c52f84ffe44b7ef1bcf62262e4c5cb3f899282d7f, balance: 8074800000000000000
Matched contract with code hash 971879f99a024e31a9c70b67af4fb797
Address: 0x0018e2ebfa668e1d8daa131cf7821fe21784e420941296770d47ec6a6f4325e6, balance: 56]
```

The addresses shown have invalid length and don't exist.

**Expected behavior**

The search should return the correct address of contract instances.

**Desktop (please complete the following information):**
 - OS: MacOS High Sierra

**Comment by norhh** [comment]
The ethereum SecureTrie does a sha3 hash on the address before storing. so we are getting sha3 of the addresses.
Was this problem present before the leveldb refactor commit?

**Comment by b-mueller** [comment]
> Was this problem present before the leveldb refactor commit?

Probably. I never used the feature successfully before because it would attempt to parse the whole DB and never finish.

Is the original address not stored in the trie? If not, is there any workaround we can use?

**Comment by norhh** [comment]
The ethereum doc mentions one way which is to store a dbmapping with the sha3 values to the addresses https://github.com/ethereum/wiki/wiki/Design-Rationale#merkle-patricia-trees.
That might not be easy.

**Comment by b-mueller** [comment]
Uhhh, I wasn't aware that *sha3(k)* is used as the lookup key. This makes it indeed very difficult to enumerate addresses.

Maybe geth stores the sha3(k) -> k mapping as well? Probably not :)

**Comment by b-mueller** [comment]
The easiest way I can think of is to repurpose our `--init-db` feature so that it builds the mapping from local blockchain data. This should be relatively fast and would only need to be done once (and from then on it can sync new addresses continuously).

It's annoying, but still much better than doing everything via RPC.

**Comment by norhh** [comment]
yeah, sounds good

**Comment by norhh** [comment]
after some calculations it looks like hashing and storing should be quite fast(will be done in minutes if 100 million addresses are considered), is there a way to get all addresses list from geth without traversing transaction trie?, if there is a fast way for that then init-db should be quite fast.

**Comment by b-mueller** [comment]
> is there a way to get all addresses list from geth without traversing transaction trie?

I guess not, unless geth maintains an address list somewhere (which it doesn't have a reason to do). But traversing the transaction trie shouldn't be too slow either?

**Comment by norhh** [comment]
looks like iterating over transaction trie may take quite an amount of time for fully synced geth (maybe atleast 1 day) , [here](https://ethereum.stackexchange.com/questions/27809/how-to-list-all-ethereum-addresses-with-a-positive-balance) it is mentioned to run for a week but we don't need positive balance addresses and we are using local leveldb so it may be faster than that.(but python is slow). I think we might be able to parallelise the traversal and also the mapping of hash to some extent.
