### ISSUE TITLE
Ability to specify compiler version

### ISSUE THREAD

**Issue by ajsantander** [ConsenSys/mythril#31]
If you try to run `myth -x MyContract.sol` and MyContract.sol specifies any pragma version < latest:

```
Source file requires different compiler version (current compiler is 0.4.19-develop.2017.11.22+commit.ea18bed3.Linux.g++ - note that nightly builds are considered to be strictly less than the released version
pragma solidity 0.4.17;
^---------------------^
```

If there is a way to specify the compiler version, I did not find it, so sorry in advance.

**Comment by b-mueller** [comment]
Thanks for the suggestion. Mythril uses the solc binary in PATH, or specified in the 'SOLC' environment variable. So at the moment, installing the required solc version (or installing multiple versions and setting SOLC to the required version) would be the only option.

I'll look into how to improve this but for now, the easiest workaround is to pre-compile on Remix or deploying the contract(s) on testrpc.

**Comment by b-mueller** [comment]
It might be possible to use [py-solc](https://pypi.python.org/pypi/py-solc) for managing compiler versions. I'll look into it!

**Comment by step21** [comment]
I started implementing this. Py-solc stores its binaries below `~/.py-solc/`. As far as I can tell, it however doesn't have a function to check its already installed versions. So either we would have to implement that in mythril or in py-solc to check, or maybe it is ok that it briefly tries to re-download and then wget or whatever it uses notices that it is already there.

**Comment by b-mueller** [comment]
Hmm sounds like it would be cleaner to check if the binary exists already?

**Comment by step21** [comment]
Ok. This should work https://github.com/ConsenSys/mythril/pull/50

**Comment by b-mueller** [comment]
Feature has been added.
