### ISSUE TITLE
Mythril reports different outputs for the same input

### ISSUE THREAD

**Issue by shashank-srikant** [ConsenSys/mythril#329]
**Describe the bug**
Mythril produces two different outputs on the same input. It seems to be some caching-effect coming into play. On running it several times over, the "correct" output gets printed.

**To Reproduce**
I run the following command:
`myth -xo json file_path.sol`

I'm running the following source code - 
[https://etherscan.io/address/0x00000b233566fcc3825f94d68d4fc410f8cb2300#code](https://etherscan.io/address/0x00000b233566fcc3825f94d68d4fc410f8cb2300#code)
I've copied the code from there and placed it in a file on my local machine where I'm running Mythril.

**Expected behavior**
Mythril is supposed to detect possible integer overflows.

However, on most runs, it outputs the following - 
`{"error": null, "issues": [], "success": true}`

And in a one-off run, it dumps the seemingly correct output -
```
{  
   "error":null,
   "issues":[  
      {  
         "address":1595,
         "code":"     emit Transfer(owner, to[i], values[i]);\n        }\n        return(i);\n    }\n}",
         "debug":"calldata_ApproveAndCallFallBack_4: 0xfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc\ncalldata_ApproveAndCallFallBack_0: 0xaad41a4100000000000000000000000000000000000000000000000000000000\ncalldatasize_ApproveAndCallFallBack: 0x4\ncallvalue: 0x0\n",
         "description":"A possible integer overflow exists in the function `multisend(address[],uint256[])`.\nThe addition or multiplication may result in a value higher than the maximum representable integer.",
         "filename":"sol_0x00000b233566fcc3825f94d68d4fc410f8cb2300.sol",
         "function":"multisend(address[],uint256[])",
         "lineno":274,
         "title":"Integer Overflow ",
         "type":"Warning"
      },
      {  
         "address":1826,
         "code":"k(spender).receiveApproval(msg.sender, tokens, this, data);\n        return true;\n    }\n\n\n    // ------------------------------------------------------------------------\n    // Owner can transfer out any accidentally sent ERC20 tokens\n    // ------------------------------------------------------------------------\n    function t",
         "debug":"calldata_ApproveAndCallFallBack_32 + 36: 0xfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc\ncalldata_ApproveAndCallFallBack_0: 0xcae9ca5100000000000000000000000000000000000000000000000000000000\ncalldatasize_ApproveAndCallFallBack: 0x4\ncallvalue: 0x0\n",
         "description":"A possible integer overflow exists in the function `approveAndCall(address,uint256,bytes)`.\nThe addition or multiplication may result in a value higher than the maximum representable integer.",
         "filename":"sol_0x00000b233566fcc3825f94d68d4fc410f8cb2300.sol",
         "function":"approveAndCall(address,uint256,bytes)",
         "lineno":241,
         "title":"Integer Overflow ",
         "type":"Warning"
      },
      {  
         "address":6549,
         "debug":"The exception is triggered under the following conditions:\n\ncalldata_ApproveAndCallFallBack_4 + calldata_ApproveAndCallFallBack_4: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\nstorage_0: 0x0\ncaller: 0x0\ncalldata_ApproveAndCallFallBack_0: 0xaad41a4100000000000000000000000000000000000000000000000000000000\ncalldatasize_ApproveAndCallFallBack: 0x4\nmem_128 +\n32 +\n32*\ncalldata_ApproveAndCallFallBack_4 + calldata_ApproveAndCallFallBack_4: 0x0\ncallvalue: 0x0\n",
         "description":"A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ",
         "filename":"sol_0x00000b233566fcc3825f94d68d4fc410f8cb2300.sol",
         "function":"multisend(address[],uint256[])",
         "lineno":278,
         "title":"Exception state",
         "type":"Informational"
      },
      {  
         "address":8556,
         "code":"quire",
         "debug":"calldata_ApproveAndCallFallBack_32 + 36: 0x800000000000000003ffd0badcb9b7000000002781000000000000000006bfff\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_ApproveAndCallFallBack_32_+_4: 0x800000000000000000008eb2e34648ee0801030820000000000000000000a000\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncaller: 0x800000000000000003ffd0badcb9b7000000002781000000000000000006bfff\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_ApproveAndCallFallBack_4: 0x800000000000000003ffd0badcb9b7000000002781000000000000000006bfff\nstorage_1: 0xff00\ncalldata_ApproveAndCallFallBack_0: 0x23b872dd00000000000000000000000000000000000000000000000000000000\ncalldatasize_ApproveAndCallFallBack: 0x4\ncallvalue: 0x0\n",
         "description":"A possible integer overflow exists in the function `transferFrom(address,address,uint256)`.\nThe addition or multiplication may result in a value higher than the maximum representable integer.",
         "filename":"sol_0x00000b233566fcc3825f94d68d4fc410f8cb2300.sol",
         "function":"transferFrom(address,address,uint256)",
         "lineno":19,
         "title":"Integer Overflow ",
         "type":"Warning"
      }
   ],
   "success":true
}
```
**Screenshots**
![myth_bug](https://user-images.githubusercontent.com/14936946/42517988-04e77b0a-842f-11e8-9823-a3f6e42ec57c.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu, 16.04.4 LTS
 - Latest codebase pulled from Mythril's github account

**Comment by shashank-srikant** [comment]
Was looking up other issues - seems to be related to @305
Will try tweaking Z3's timeout.

In any case, if Z3 is indeed timing out on the default time provided, the current output shown
`{"error": null, "issues": [], "success": true}`
 is just not right! It should have an appropriate message letting the user know that Z3 has timed out.

**Comment by JoranHonig** [comment]
@shashank-srikant thanks for the report.

First of all, could you try (that should fix your problem):
```
myth -xo json file_path.sol:NRM
```

I think this is actually caused by our implementation that doesn't (internally) always order contracts in the same way. If you don't specify the contract name, then it will pick the last one it can find (which is not always the same contract) so you'll get different results.

@b-mueller What was the expected behavior here? Intuitively I'd think that if you don't specify a contract, then it just analyzes all (which it doesn't :innocent:).

As to the z3 timeout, z3 is the constraint solver we use. In some cases its super hard/undecidable to say if something is satisfiable, in which case we don't want the solver to keep working forever. This isn't a super weird situation, and the timeout just tells the solver how extensively to look for a certain situation. In the end we need to make a tradeoff between how much possibilities we can explore (smt solving, and symbolic execution) vs resource costs. We are planning on providing customization options through the cli, to allow the user to choose these parameters (fitting them to their resources and requirements).  I'll add a logging rule (that logs timeouts) which will make it easier to find what values work best

**Comment by shashank-srikant** [comment]
Thanks.

What then is the current way to analyze all the contracts in a script? Without knowing the contract names a priori? Is there anything convenient? Or should i get the names off of the script's AST and then supply those one by one to `myth`?

Regarding Z3 timeouts -- yup. i'm perfectly fine with timing out Z3. There's no other way around it. I was under the assumption that this output `{"error": null, "issues": [], "success": true}` was reported in cases when Z3 would time out.

**Comment by JoranHonig** [comment]
@shashank-srikant Like I said, I think the expected behavior should be to analyze all contracts (or at least give a message to the user with the options). 

Because I fully understand how this might be confusing, and it might give people the assumption that everything is fine while its not. I'm keeping the issue open until we have decided what good behaviour would be in this case (which is also why I wanted @b-mueller s input)

**Comment by b-mueller** [comment]
I agree, analyzing all contracts by default makes more sense.

**Comment by shashank-srikant** [comment]
yup; sure. thank you.

but while we wait for others' inputs, i wanted to make progress with my analysis -- and hence wanted to know what i could do in the existing framework to push in names of all the contracts. any pointers? thanks again.

**Comment by b-mueller** [comment]
> should i get the names off of the script's AST and then supply those one by one to myth?

Currently I'm afraid that's the best option.

**Comment by JoranHonig** [comment]
For the contract you had its: 
```
NRM
Owned
SafeMath
```

I think I can get it fixed rather quickly

**Comment by shashank-srikant** [comment]
also, would be great if the output had a field which reflected the name of the contract which was analyzed. that'll be super useful as well, i'm guessing. 

in case someone encounters a stray output blurb, they'll be able to discern which contract it corresponds to.

something like this - 
`{"error": null, "issues": [], "success": true, "contract_name":file_path.sol:NRM}`

currently, the `file name`, `function name`, and the `line number` gets added in this `error` key in the dict, but nowhere is the name of the contract mentioned.

**Comment by JoranHonig** [comment]
@shashank-srikant That is now in master ^^
