### ISSUE TITLE
Regarding the default connection when using -l

### ISSUE THREAD

**Issue by norhh** [ConsenSys/mythril#340]
This is regarding the 'connecting when using -l and not mentioning any node to connect' issue as was discussed on gitter.

Two options as mentioned on gitter are:-
1) Warn users that 'using -l option without mentioning anything to connect will not use the dynamic loader'.
2) Have the configuration set on config.ini file defaulting to INFURA.

**Comment by b-mueller** [comment]
+1 for option 2 :)
