### ISSUE TITLE
Error in delegatecall

### ISSUE THREAD

**Issue by JoranHonig** [ConsenSys/mythril#346]
## Description
Running analysis on the followin contract results in an error:
```
 0xdF7C42c18c4BAc520dd7A845AA0d85FbB87168d9
```

Two things need to be done to fix this:
 - Index error except on mload
 - delegate call fix

**Comment by JoranHonig** [comment]
See also the discussion in #344

**Comment by norhh** [comment]
Probably because delegate call returns a new state with pc = 0, then the decorator does a pc++ after new state is returned to it.

**Comment by norhh** [comment]
also it seems that would result an assertion error in taintrunner (but unrelated to #309 ), it seems there is a misalignment of Calls with the TaintRunner(record stack length=14 and state stack length =0)

**Comment by JoranHonig** [comment]
@norhh This is not actually caused by the delegate call, but by the taintrunner that doesn't handle calls correctly, which leads to mismatched memory states. 
You are right about the pc=0, I already had that fixed locally and this is implemented in #345
