### ISSUE TITLE
contribute to the repository

### ISSUE THREAD

**Issue by KennyFood** [ConsenSys/mythril#349]
# Detection issue:
During learning Mythril, although there are lots of comments, I found it‘s laborious to totally understand the source code and symbolic analysis mechanism.

## Description: 
I documented some details when I learned the source code and after learning I wrote a document about how Mythril and Laser works and what the symbolic analysis in Mythril is. I just want to contribute this document to repository even if it doesn't help. I'm glad to share my document and If you want to, please reply me or provide me with your email address.
Thanks a lot!

**Comment by JoranHonig** [comment]
@KennyFood awesome that you'd like to contribute. Maybe we can add this to our wiki.

Could you do a pull request with the document vs sending it via email? That would make discussion and review a lot more easy

**Comment by KennyFood** [comment]
@JoranHonig I can send this document to you directly via email however I didn't find your email address in personal information. 

I'm glad to share this with you and others. After learning Mythril, I summarized my understanding of source code execution including concolic execution. Although this document is not particularly refined, I think it might slightly help others who want in-depth understanding of Mythril.

**Comment by norhh** [comment]
@KennyFood that would be quite helpful for the people who want to understand mythril. You can put a PR with the document or you can  put the content in google docs and share it in this thread with permissions such that we can drop comments on it, we can have easier discussions in this way over the email.

**Comment by KennyFood** [comment]
@norhh @JoranHonig I create a new public repository and upload this document. This is URL: [https://github.com/KennyFood/Mythril-Mechanism-Analysis.git](url). :blush::blush:

I think we can have some discussion since I don't know if this document is helpful. 😛

**Comment by rocky** [comment]
@KennyFood In markdown put the link name first in square brackets and then the parenthesis . Like this [Mythril-Mechanism-Analysis](https://github.com/KennyFood/Mythril-Mechanism-Analysis.git). You had the link name first.

**Comment by b-mueller** [comment]
@KennyFood I think a Medium article would be the right format for this. Maybe with the title "Mythril Internals: How Symbolic Execution Works" or something similar. We'll be happy to share it on Gitter 
/ Telegram / Twitter.

**Comment by norhh** [comment]
@b-mueller Also it would be good if we can place it in 'for contributors section' in wiki. And mention it in ReadMe, as those two are the main sections which new contributors see first.

**Comment by KennyFood** [comment]
@b-mueller thanks for your reply.

I have changed the title and If there is something wrong with this document or whatever else, just let me know.  Thanks 😄

**Comment by JoranHonig** [comment]
I've had a quick look and you have put in great effort! :+1: One thing to note is that there is a lot going on around implementation for laser.
One example is the restructuring of functionality in separate modules.
Another is the fact that svm.py isn't using a giant loop anymore but we're now using a worklist and search strategies.
Even more awesome is the multi-transactional analysis that we're now getting started on, which would allow us to do more accurate analysis (atm we need to overestimate some symbols)

**Comment by b-mueller** [comment]
@KennyFood I'm closing this issue for now. Please convert you content to a Medium post and let us know the link, and we'll create a new Wiki page to link to your article (and other Mythril-related articles).
