### ISSUE TITLE
Add a comand-line option, e.g. `--version|-V` to show the Mythril version installed? 

### ISSUE THREAD

**Issue by rocky** [ConsenSys/mythril#351]
**Describe the bug**
Mythril is improving all the time, so it useful to know what version you have installed

I propose we add a command-line option like `--version` and/or `-V` and show the version number when help is shown.

**Comment by b-mueller** [comment]
I've already looked into options to implement -v before but didn't find any good way to do it.

**Comment by rocky** [comment]
Perhaps I'll suggest something then. I think I've run into this problem before.

**Comment by rocky** [comment]
Fixed in a6443dc
