### ISSUE TITLE
When Pypy 3.6+ comes out, consider using in the mythril docker container? 

### ISSUE THREAD

**Issue by rocky** [ConsenSys/mythril#352]
Pypy works on 3.5 and so does Mythril

Perhaps we would get speed ups in the mythril docker container if we used Pypy rather than CPython?

**Comment by birdofpreyru** [comment]
Somebody should test whether Mythril is compatible with PyPy. If yes, then we should do it.

**Comment by rocky** [comment]
Sigh. It looks like this can't be easily done right now. The latest stable version of PyPy is 3.5 and mythril needs 3.6. Also [pysha3 is broken for PyPy 3.5](https://bitbucket.org/pypy/pypy/issues/2687/pypy3-is-missing-pystrhexh-breaking-pysha3). 

So let's revisit if/when a newer version of Pypy comes out and when pysha3 is fixed for Pypy. 

@birdofpreyru  @b-mueller  In a way I'd like this to revisit until sometime in the future. Should we close it and reopen later, or can it be kept open with some suitable label or something else?

**Comment by rocky** [comment]
Probably could hack aroudn pysha3 for PyPy 3.5. I hacker-night kind of challenge.

**Comment by nbanmp** [comment]
This is stale, and Python 3.6 is the default in the docker container now.
