### ISSUE TITLE
Wrong file name listed for a contract in a truffle project

### ISSUE THREAD

**Issue by rocky** [ConsenSys/mythril#356]
**Describe the bug**
On an error (IntegerOverflow), I am seeing the wrong filename, the filename of the truffle project JSON rather than filename of the contract.

**To Reproduce**

Create a truffle project

```
$  truffle init IntegerOverflow
$ cd IntegerOverflow
```
create IntegerOverflow.sol: 

```
pragma solidity ^0.4.23;

contract IntegerOverflow {
    uint public count = 1;

    function run(uint256 input) public {
        count *= input;
    }
}
```
Run: 

```
$ myth -d -t .   # Note -d option is ignored.
# Analysis result for IntegerOverflow:

==== Integer Overflow ====
Type: Warning
Contract: IntegerOverflow
Function name: _function_0xa444f5e9
PC address: 174
A possible integer overflow exists in the function `_function_0xa444f5e9`.
The addition or multiplication may result in a value higher than the maximum representable integer.
--------------------
In file: IntegerOverflow.json:7
                         ^^^^

count *= input

--------------------
```

**Expected output***:

```
In file: IntegerOverflow.sol:7
```

Note that using JSON output `-o json` doesn't change the wrong data.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: bionic

**Comment by norhh** [comment]
mythril runs on build directory for truffle projects, so it just takes the file name from there which is json

**Comment by rocky** [comment]
Yes, it was coincidence here (but probably often done) that I used the same for the truffle project and for the single file name under contracts.
