### ISSUE TITLE
Follow PC with address in the state

### ISSUE THREAD

**Issue by FFengIll** [ConsenSys/mythril#370]
**Describe the bug**
PC and Address `not easy` to mapping. (Feature needed)

While we use mythril, we have `pc` in the state as instruction index, and then we can get the instruction by a list using pc.
Then we have ins with `address`, but unfortunately, we do never have a convenience way to map `address` with `pc` except debug.

**To Reproduce**
Maybe we can both keep pc and address in state.
```
{'pc':723, 'addr':1663}
```
Furthermore, keep both in graph output.
```
723: 1663 PUSH2
```

**Expected behavior**
while put pc into state, follow an address, this help to debug and analysis develop.
output graph with pc and address, good for user and developer.

**Comment by rocky** [comment]
For what it is worth, as a longer-term project I have been working on mapping on going from the instruction index to the corresponding source and the corresponding abstract-syntax tree. Would this help?

**Comment by FFengIll** [comment]
@rocky good to know it!
Also follow the address in state may help more.
The mis-mapping of them may make some analysis implement more hard.

**Comment by rocky** [comment]
Hmm - rereading this, I don't see how anything I've been looking at is relevant.

**Comment by FFengIll** [comment]
@rocky if the white-box content (source code / AST) can mapping to the black-box content (bytecode), of course it help.
I just wish to have a possible to mapping PC and Addr -- these 2 works maybe completed together.
(Of course, it should be fully considered)
