### ISSUE TITLE
Decoupling the Instruction usage and merge all info into Instruction itself.

### ISSUE THREAD

**Issue by FFengIll** [ConsenSys/mythril#373]
**Describe the bug**

**It is only a suggestion for you while I see the refactor is in-process.**

* Now only opcode in Instruction, but in analysis, we need more info (in fact).
```python
#use
op_code = disassembly.instruction_list[index]['opcode']
```
```python
#define
    def __init__(self, op_code, dynamic_loader):
        self.dynamic_loader = dynamic_loader
        self.op_code = op_code
```
* in disasm, instruction info work as a dict, like
```python
instruction_list.append({'address': addr, 'opcode': "INVALID"})
```
so the instruction must follow some info though the address may not be right.

**To Reproduce**
search the code to see more.

**Expected behavior**
may it is possible like this
```python
class BaseInstruction:
    def __init__(self, address=None, opcode=None, argument=None):
        self.address = address
        self.opcode = opcode
        self.argument = argument
        self.subop = None

class Instruction2(BaseInstruction):
    """
    Instruction class is used to mutate a state according to the current instruction
    """

    def __init__(self, base, dynamic_loader):
        self.dynamic_loader = dynamic_loader
        self.base = base
   @property
    def address(self):
         return self.base.address

```

**Comment by FFengIll** [comment]
@b-mueller I am not sure the address can keep ( since I only use it in local mode and I read little in the loader ).
Furthermore, as a transition period, it won't miss any possible failure and will keep all callers except the first args. (keep the change min)
Maybe a extra remove of the `dynamic_loader` in the future.

**Comment by JoranHonig** [comment]
@FFengIll I see you closed the issue, you agree with my points? Otherwise I'm open for other arguments, in any case I/we appreciate the input of this issue :+1:

**Comment by FFengIll** [comment]
@JoranHonig Somehow, it is not means a full agree, but understand the design of current arch.
Though I implement in another schema, I agree with the design for mythril's requirements.

Thanks for you explain.
