### ISSUE TITLE
Contract search returns some invalid addresses

### ISSUE THREAD

**Issue by b-mueller** [ConsenSys/mythril#401]
## Description

Replace this text with a clear and concise description of the bug.

## How to Reproduce

Sync a mainnet node up to block ~1,000,000, then run a search, e.g.:

```
$MYTH --search "func#withdraw()#"
Updating hash-to-address index from block 1022728
32768 blocks processed (in 13 seconds), 1139 unique addresses found, next block: 1055497
65536 blocks processed (in 27 seconds), 2461 unique addresses found, next block: 1088265
98304 blocks processed (in 31 seconds), 2624 unique addresses found, next block: 1096267
Finished indexing
Address: 0x9d4f32fc70c0a12b05d3649ec3ce0bf60e208616, balance: 0
Address: 0x6d02e52b84bed06f4bc19a14cd8758b2b5fc35c5, balance: 0
Address: 0x134040641530b0b841d6034a9eb849d9ba00bc9e1a5b2dc1571641b149b6e139, balance: 800000000000000
Address: 0xc18a7746bcc691ceb766d8f24c70e93e4666fb9f, balance: 0
Address: 0x21cc9de70e5aa5b6b955395ea850e88b8ee7e6e7771566cf8ace754cec858291, balance: 0
Address: 0x51bb3a35edc75915a561fe794dfb1acf161879af, balance: 10000000000000000
Address: 0xea51521b3e88cbf6c8933b81c0101683618ea18a, balance: 0
Address: 0xe76d48c09223180b7aa940307d4456e130343718, balance: 0
Address: 0x2945e60678d76acc6178730488d1f00e7dbf5105, balance: 20
Address: 0x1e49786167d3cf430895080d6d3ab352c5d95322, balance: 0
Address: 0x32810d803049aea9c8e60d960ad0ac08b005ef5f144cb15f5edbd1b0b2af00e3, balance: 0
Address: 0x1d9d6b70b64ddef36c195a03b5d092f2aa0aa125, balance: 0
```

Some of the addresses are correct, but some have an invalid length.

## Expected behavior

Only correct addresses of 20 bytes length should be reported.

## Environment

- Mythril version: Master plus #396
- Python version: 3.6.3
- OS: High Sierra
- Geth 1.8.11-stable

**Comment by b-mueller** [comment]
Tracking down the problem, it seems that there's some issue when building the hash->address mapping that causes some addresses to be missing from the mapping.

Note that the hashes of the missing addresses all start with `0`:

```
Address: 0x53ee2d03aa525921e881ad9da28c67bad88b2d7e, balance: 0
Address: 0x8f2b69993d578aed4211299935c1a649b59a2dd4, balance: 0
Address: 0x05c174432097191726be3627d21aa361c9a9696cdfae1f73f5e6b73ce1714f36, balance: 0
Address: 0x9515a8a13beedca0bf5238dc36514d953c2c5625, balance: 0
Address: 0x05cde250c51c104ea4ddc0f5948adfacbf5ffd91b81fb49592ae46797da71d8b, balance: 0
Address: 0xeb27a00443d3dd90f1da71110a964d947cfedceb, balance: 12363064042475
```

**Comment by norhh** [comment]
Same thing happened for a 40MB of rinkeby in my case, but the missing hashes here didn't start with 0.

**Comment by b-mueller** [comment]
I take back the "0" thing, I think that was just a coincidence :)

The problem must be that either these hashes haven't been indexed for some reason, or they've been indexed in a way that doesn't match the hash used for lookup. I'm still not sure about the exact reason. @norhh can you look into this?

**Comment by norhh** [comment]
yep, i am currently looking into it.

**Comment by norhh** [comment]
those hash's corresponding addresses seem to be non existent in the receipts present in leveldb.By any chance is it possible for address to be in accounts but not in transaction receipt.(the other way would happen as some contract creation transactions may fail).

**Comment by b-mueller** [comment]
Hmm, the likely answer is that those contracts were created by other contracts (factory contracts) and not external transactions. If that's true then I don't see any easy way to add those addresses.

One idea though, this here is from [StackOverflow](https://ethereum.stackexchange.com/questions/760/how-is-the-address-of-an-ethereum-contract-computed):

```
The address for an Ethereum contract is deterministically computed from the address of its creator (sender) and how many transactions the creator has sent (nonce). The sender and nonce are RLP encoded and then hashed with Keccak-256.
```

What we theoretically could do is

1. for every contract address, check if another contract created by that contract exists. Would be expensive though because lots more SHA3 hashes to compute, also we'd also have to test multiple nonces.

2. concretely execute every transaction that goes to an existing contract and check whether it creates another contract, and if it does add that address to the index.

Both of those are difficult to do, so at the moment it's probably not worth the effort?

**Comment by norhh** [comment]
any contract when creating a new contract would form a transaction right?

**Comment by b-mueller** [comment]
Yes, but perhaps "internal" transactions by contracts aren't stored in the db? I'm not sure about that.

**Comment by norhh** [comment]
Yeah it seems internal transactions aren't specifically stored.Also what percentage of addresses are properly shown?

**Comment by b-mueller** [comment]
Roughly 90% are probably shown. It's still usable, for now I'd say let's filter those results and add a disclaimer somewhere that the search doesn't cover contracts created by internal transactions.

In the mid-term it would be nice to address this, but at the moment the effort required isn't justified. Except anyone can think of a simple solution? 🤔

**Comment by JoranHonig** [comment]
@b-mueller This could be closed right?

**Comment by b-mueller** [comment]
Yes, that's fixed.
