### ISSUE TITLE
Source-code constraint hinting, and --constraint option

### ISSUE THREAD

**Issue by rocky** [ConsenSys/mythril#405]
## Description

Allow a wrapper to augment the code with solver hints of invariants. This could also be given as an option `--constraint`.

In  Suhabe's benchmarks you can find in comments invariants like [this](https://github.com/ConsenSys/evm-analyzer-benchmark-suite/blob/master/benchmarks/integer_overflow_storageinvariant.sol#L1): 

     //No underflow because of credit/balance invariant: sum (credit.values) = balance

A front-end wrapper could look for comments of the form: 

    //invariant: sum (credit.values) = balance

And that coiuld be added as a constraint to the z3 solver. Presumably this would prevent Mythril from triggering the violation. 

Outside of a wrapper a `--constraint` option could be supplied. However note that when done inside the source code, we can be precise about the scope. 

A `--constraint` option can only work as a global scope constraint. 

## Tests

[integer_overflow_storage](https://github.com/ConsenSys/evm-analyzer-benchmark-suite/blob/master/benchmarks/integer_overflow_storageinvariant.sol)

## Background

This started as an off-shoot to #172. It may ameliorate that problem somewhat but it doesn't fully address it. So see that for more discussion.

**Comment by fubuloubu** [comment]
Suggestion: `invariant` should have extra symbol to key off of, such as `@invariant`

I guess `invariant:` is another possibility too. Parsing comments is fun!

**Comment by JoranHonig** [comment]
Closing this, with laser's new execution model this is not necessary
