### ISSUE TITLE
License conflict between mythril and laster-ethereum

### ISSUE THREAD

**Issue by hiqua** [ConsenSys/mythril#43]
Hi,

mythril is apparently released under the MIT license according to the LICENSE file (in which Dan Abramov is mentioned as the sole copyright owner even though he didn't contribute to this project AFAIK).

laster-ethereum, which is a dependency, is released under a "Free for non-commercial use" license according to the setup.py file and the resulting [package page](https://pypi.python.org/pypi/laser-ethereum/0.4.0) (no LICENSE file in the github repository).

I would have thought that a project using a library under this "Free for non-commercial use" license could not be released under the MIT license, which is free including for commercial use. If my interpretation is correct, one of these two projects should be relicensed to be compatible with the other (so mythril into "Free for non-commercial use" or laser-ethereum into MIT license).

**Comment by b-mueller** [comment]
Hi @hiqua, thanks for the feedback! Dan Abramov was indeed a copy/paste error, I fixed it. 

The "free for non-commercial use" license in laser-ethereum has historic reasons, I'm going to update this to MIT license as well.
