### ISSUE TITLE
Analysis doesn't run on some files

### ISSUE THREAD

**Issue by norhh** [ConsenSys/mythril#440]
## Description

Analysis terminates in seconds with no issue being detected. for this [contract](https://etherscan.io/address/0xa646e29877d52b9e2de457eca09c724ff16d0a2b#code), when it's copy pasted on file and then run.

## How to Reproduce
```console
$ myth -xl <filename> 
The analysis was completed successfully. No issues were detected.
...
$
```

## Expected behavior

Analysis should run.

## Environment

Please modify for your setup

- Mythril version: master
- Python version: `3.6`
- OS: Ubuntu
- OS Version 17.10

**Comment by JoranHonig** [comment]
This is caused by the creation transaction not successfully terminating
