### ISSUE TITLE
IPC RPC

### ISSUE THREAD

**Issue by Xeenych** [ConsenSys/mythril#45]
Interaction with geth node via IPC is much more than 10 times faster than by http.
Tested on my home PC.
Reading and wiriting to ipc is easy as RW to a stream or file (geth.ipc on windows)

**Comment by step21** [comment]
There is already ipc support. You can enable it with `--ipc`. Not sure how much faster it is, I wrote it but it didn't seem 10x faster for me. How did you test this setup where it was 10x faster?

**Comment by Xeenych** [comment]
I used it when scanning blockchain for contracts. Speed difference was measured visually.

**Comment by step21** [comment]
Ah ok. Glad you like it :)

**Comment by step21** [comment]
Close this?

**Comment by b-mueller** [comment]
I didn't get around to try it out myself yet & update the docs.

**Comment by b-mueller** [comment]
IPC is now the default (https://github.com/ConsenSys/mythril/commit/97ecda77856ae064f32d625fcee1801a2403a1b1).

**Comment by step21** [comment]
What were your measurements, if you did any?

**Comment by b-mueller** [comment]
I didn't do any actually :) I just figured using IPC at the default is cleaner anyway.

**Comment by Xeenych** [comment]
I made som rough measurements. Geth 1.7.3, Win7, chaindata is on SSD.
```
            Stopwatch s = new Stopwatch();
            s.Start();
            for (int b = 0; b < 100000; b++)
                rpc.eth_getBlockByNumber(b);
            s.Stop();
            Console.WriteLine(s.Elapsed);
            Console.ReadKey();
            return;
```

IPC takes 40 sec
HTTP takes 58 sec

**Comment by step21** [comment]
You could also think about implementing ipc separately, similar to rpc, so that web3.py is not necessary. As web3.py might introduce some overhead. But I just figured I probably couldn't do it better than them.
