### ISSUE TITLE
contract name and instruction address missing in mythril's report output

### ISSUE THREAD

**Issue by rags1412** [ConsenSys/mythril#458]
## Missing contract name and instruction address in mythril's output

From mythril.interfaces.cli.py:main(), the `report` variable contains all `issues`. Each of these issues hold fields for contract-name and the address of the instruction that raised this vulnerability. I see that the contract name is always 'unknown' and the address of the instruction is always set to zeroes.

## How to reproduce?
Run ./myth -x tests/testdata/input_contracts/overflow.sol
==== Integer Underflow ====
Type: Warning
Contract: unknown
Function name: sendeth(address,uint256)
PC address: 600
A possible integer underflow exists in the function `sendeth(address,uint256)`.
The subtraction may result in a value < 0.
--------------------
In file: tests/testdata/input_contracts/overflow.sol:11

balances[msg.sender] - _value

--------------------
--------------------
DEBUGGING INFORMATION:

calldata_unknown[36]: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
calldata_unknown[0]: 0xa3210e8700000000000000000000000000000000000000000000000000000000
calldatasize_unknown: 0x4
call_value: 0x0

==== Integer Underflow ====
Type: Warning
Contract: unknown
Function name: sendeth(address,uint256)
PC address: 682
A possible integer underflow exists in the function `sendeth(address,uint256)`.
The subtraction may result in a value < 0.
--------------------
In file: tests/testdata/input_contracts/overflow.sol:12

balances[msg.sender] -= _value

--------------------
--------------------
DEBUGGING INFORMATION:

calldata_unknown[36]: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
calldata_unknown[0]: 0xa3210e8700000000000000000000000000000000000000000000000000000000
calldatasize_unknown: 0x4
call_value: 0x0

==== Integer Overflow ====
Type: Warning
Contract: unknown
Function name: sendeth(address,uint256)
PC address: 758
A possible integer overflow exists in the function `sendeth(address,uint256)`.
The addition or multiplication may result in a value higher than the maximum representable integer.
--------------------
In file: tests/testdata/input_contracts/overflow.sol:13

balances[_to] += _value

--------------------
--------------------
DEBUGGING INFORMATION:

calldata_unknown[36]: 0x8000000000000000000000000000000000000000000000000000000000000000
calldata_unknown[0]: 0xa3210e8700000000000000000000000000000000000000000000000000000000
calldatasize_unknown: 0x4
call_value: 0x0

**Comment by JoranHonig** [comment]
The contract naming issue has been fixed with #469. 

It seems to me though that the address is being initialized just fine? 600, 682 and 758
