### ISSUE TITLE
Remove Truffle support

### ISSUE THREAD

**Issue by b-mueller** [ConsenSys/mythril#459]
## Description

Remove the `--truffle` option. It doesn't work very well anyway, and we'll soon have an API-based tool that integrates perfectly with truffle.

**Comment by norhh** [comment]
lets remove it after the api launch

**Comment by jeamick** [comment]
Hello @b-mueller @norhh ,

I can work on this issue if nobody will be on it .

Thanks

**Comment by norhh** [comment]
hi @jeamick , yes it would be great if you would like to do that, but unfortunately we are thinking of removing the truffle support after the api release, so might be good if you can do that then.

**Comment by jeamick** [comment]
@norhh  so after the release right ?

**Comment by norhh** [comment]
@jeamick , yes after the api launch.

**Comment by jeamick** [comment]
did the api has been launched?

**Comment by norhh** [comment]
@jeamick , it's still in progress, let's remove this after the truffle integration, which might be done in a month.

**Comment by JoranHonig** [comment]
Well, the API release isn't until the first of March. Lets not remove anything until that point

**Comment by JoranHonig** [comment]
This seems to be a stale issue -> closing 🙌
