### ISSUE TITLE
Source code analysis misses constraints

### ISSUE THREAD

**Issue by b-mueller** [ConsenSys/mythril#460]
## Description

When running Mythril on the [Ethereum verified contracts](https://github.com/thec00n/etherscan_verified_contracts), I noticed a large number of false positives from the ether_send and suicide models. It appears that constraints on functions are not detected or somehow misinterpreted.

## How to Reproduce

Here is an example for a "suicide" false positive ([source](https://github.com/thec00n/etherscan_verified_contracts/blob/master/contracts/0x000621424c60951cb69e9d75d64b79813846d498_WIZE.sol)):

```
$ $MYTH -msuicide -x contracts/0x000621424c60951cb69e9d75d64b79813846d498_WIZE.sol
No contract was created during the execution of contract creation Try to increase the resouces for creation exection (max-depth or create_timeout)
==== Unchecked SUICIDE ====
Type: Warning
Contract: unknown
Function name: destroy()
PC address: 495
The function `destroy()` executes the SUICIDE instruction. The remaining Ether is sent to the caller's address.

It seems that this function can be called without restrictions.
--------------------
In file: contracts/0x000621424c60951cb69e9d75d64b79813846d498_WIZE.sol:71

selfdestruct(owner)

--------------------

==== Unchecked SUICIDE ====
Type: Warning
Contract: unknown
Function name: destroyAndSend(address)
PC address: 861
The function `destroyAndSend(address)` executes the SUICIDE instruction. The remaining Ether is sent to an address provided as a function argument.

It seems that this function can be called without restrictions.
--------------------
In file: contracts/0x000621424c60951cb69e9d75d64b79813846d498_WIZE.sol:75

selfdestruct(_recipient)

--------------------

==== Unchecked SUICIDE ====
Type: Warning
Contract: unknown
Function name: destroy()
PC address: 3643
The function `destroy()` executes the SUICIDE instruction. The remaining Ether is sent to the caller's address.

It seems that this function can be called without restrictions.
--------------------
In file: contracts/0x000621424c60951cb69e9d75d64b79813846d498_WIZE.sol:71

selfdestruct(owner)

--------------------

==== Unchecked SUICIDE ====
Type: Warning
Contract: unknown
Function name: destroyAndSend(address)
PC address: 4934
The function `destroyAndSend(address)` executes the SUICIDE instruction. The remaining Ether is sent to an address provided as a function argument.

It seems that this function can be called without restrictions.
--------------------
In file: contracts/0x000621424c60951cb69e9d75d64b79813846d498_WIZE.sol:75

selfdestruct(_recipient)

--------------------
```

Example for the ether_send module ([source](https://github.com/thec00n/[source](https://github.com/thec00n/etherscan_verified_contracts/blob/master/contracts/0x000621424c60951cb69e9d75d64b79813846d498_WIZE.sol))):

```
$ $MYTH -mether_send -x contracts/0x001ea8150f4965195e10e5b5568047e1555a6dcd_SenseProtocol.sol
No contract was created during the execution of contract creation Try to increase the resouces for creation exection (max-depth or create_timeout)
==== Ether send ====
Type: Warning
Contract: unknown
Function name: fallback
PC address: 1806
In the function `fallback` a non-zero amount of Ether is sent to msg.sender.
It seems that this function can be called without restrictions.
--------------------
In file: contracts/0x001ea8150f4965195e10e5b5568047e1555a6dcd_SenseProtocol.sol:80

owner.transfer(msg.value)

--------------------
```
## Expected behavior

These issues should not be reported.

Note: This only affects the current master, Mythril v0.18.11 pip doesn't report those issues.

## Environment

- Mythril version: f3c12a1c2fde00cfc745cf9ae5295cfac14cb23a
- Solidity compiler and version: 0.4.24+commit.e67f0147.Darwin.appleclang
- Python version: Python 3.6.3
- OS: Mac OS High Sierra

**Comment by b-mueller** [comment]
Just noticed that the problem in the second example is a different one: The function can indeed be called by anyone, but the Ether is sent to `owner` and not to `msg.sender` as reported.

**Comment by JoranHonig** [comment]
I found the problem here. It has to do with our loading concrete storage. The module checks for the occurence of 'storage' in the constraint.
I think this technique is also a bit flawed as it only ever accounts for uninitialized storage slots.

I propose to change this to check for a situation where you can reach the suicide instruction independent of the caller. Which to me seems to be a good descriptor of the vulnerability.

**Comment by b-mueller** [comment]
> The module checks for the occurence of 'storage' in the constraint.

It's a very hackish way of doing it. 

Now that we support contract creation bytecode, if `owner` is set to `msg.sender` in the constructor, do we set a concrete address? Or is it a symbolic variable?

**Comment by JoranHonig** [comment]
@b-mueller The first transaction will have the symbol corresponding to msg.sender. Which is unconstrained atm, but ofc we can also use a concrete value here.

But there might also be situations where its not the "owner" of a contract that can suicide, but it would use a different construction. I think that the generalization, "not every caller should be able to call suicide()" will capture this property

**Comment by b-mueller** [comment]
> "not every caller should be able to call suicide()" will capture this property

What we had before was a slightly extended version where we asked "can every caller execute suicide?" and, if the answer was "no because there's a constraint that says msg.sender must match storage_x", we also looked for a reachable SSTORE operation that writes to "storage_x". This was imperfect, but helped catch cases such as wrongly names constructors.

If owner is set to a concrete value 0x1234 during construction the the solver would simply output "msg.sender = 0x1234" as part of the solution?

It's possible to solve this using multi-transactional analysis, but I think it'll still take us a while to get there.

**Comment by JoranHonig** [comment]
Okay, the problem here is the symbolic initialization. It will initialize the owner as msg.sender, which is an unconstrained symbol. As such its not weird that in the analysis message call, the check "owner == msg.sender" is satisfiable, because owner will also be symbolic.

To solve this we could make the message sender a concrete value. This could roughly look like this:
- create initial "creator" account => creator
- initiate contract creation transaction where origin and sender are creator
(- create initial "actor" account => actor) (optional)
- do analysis transactions where msg.sender != creator (and msg.sender = actor)

This would still fail in situations where the owner is set using an constructor parameter vs msg.sender, but that is very hard to generalize

**Comment by b-mueller** [comment]
How about this logic:

1. Remember the storage constraints for every function that executes a critical action:
--> send ether to msg.sender or address from calldata
--> execute SUICIDE
2. Investigate every closing state of T1...Tn. Taint all storage locations that contain calldata or msg.sender. Those are assumed to be storage locations that can be modified arbitrarily.
3. Report a vulnerability if *all* storage slots that constrain the critical function are tainted.

It would be similar to the SSTOR analysis before, not perfect but at least a start. We can verify those findings with dynamic analysis (basically what you described above).

**Comment by rocky** [comment]
It feels to me that when we have such involved descriptions, this would be better formulated as in terms of dataflow using t"def/use" (for a given newly created computation, where are the uses of the computation) and "use/def" for a given computed value at some point in the program (sometime after it has previously been computed) what is the span of the effect that particular use.

In this particular situation though, I don't feel I understand enough about what's going on to attempt to reformulate this as a data-flow problem.
