### ISSUE TITLE
Exp implementation

### ISSUE THREAD

**Issue by JoranHonig** [ConsenSys/mythril#467]
## Description 
Implement full exp functionality in laser

**Comment by JoranHonig** [comment]
Not really (except that its about the same instruction ^^), this is about the virtual machine implementation. And #350 is about the detection modules

**Comment by LoCorVin** [comment]
I ran into a problem to, i think it is because exp_ only knows how to exponentiate concrete values with the base 2 correct? I ran into this when the masks where computed to read and write to storage variables shorter than 256 bits.
