### ISSUE TITLE
Ability to specify entry point contract by name

### ISSUE THREAD

**Issue by GNSPS** [ConsenSys/mythril#47]
The title is pretty self-explanatory. 😄 

The motivation for asking this is:
Mythril doesn't currently handle the dependencies from Dapphub's [`dapp` tool](https://dapp.tools/dapp/) and when using a merger tool to solve dependencies (like `solidity-merger`) the contract being analyzed is always the last one (per `solc` requirements).
If we could specify the entry point the merging tools would be a working solution!

**Comment by b-mueller** [comment]
That would be an option, but I am thinking it might be better to remove Mythril's source code input options altogether and leave the compiling and linking to the build environment. Otherwise, a lot of complicated logic has to be implemented and it will be difficult to cover the various types of imports etc.. This is high up on my list, just need to play more with Truffle and Dapp.

**Comment by b-mueller** [comment]
Input files are now [analyzed one-by-one](https://github.com/ConsenSys/mythril/commit/a412d78b4dfd9b60dc7133d4e2d514ba5f42b7d7). To scan linked contracts, deploy to blockchain and analyze with the `a` and `-l` flags.

**Comment by b-mueller** [comment]
This actually needs some more work. I discovered several issues when working on source code mapping. One special case that needs to be handled is multiple contract definitions in a single .sol file. The best option I see is allowing users to specify both filename and target contract name e.g.:

$ myth -x whatever.sol:WhatEver

Will be added soon.

**Comment by b-mueller** [comment]
I added the following behavior for solc files that contain multiple contracts.

This will analyze the *last* bytecode entry generated by solc:

```
$ /myth -x OmiseGo.sol
```

This will analyze the contract `OMGToken` in the file `OmiseGo.sol`:

```
$ /myth -x OmiseGo.sol:OMGToken
```
