### ISSUE TITLE
Dependence on predictable environment variable

### ISSUE THREAD

**Issue by shashank-srikant** [ConsenSys/mythril#470]
## Description

I wanted to understand why Mythril flags the following codes with a `Dependence on predictable environment variable`. I couldn't really spot what the dependency was. Can you please help.

Source codes - 
[1] 
Code: https://etherscan.io/address/0x1DABd43E0F8a684a02712bcD767056E25026061c#code
Contract name|Function name detected by Myth: GIFT_1_ETH | PassHasBeenSet

[2]
Code: https://etherscan.io/address/0x7f37472ee88062acc82f14ccfe6e7bf5f469dd05#code
Contract name|Function name detected by Myth: E4Token | setOpGas

Trying to pin down false-positives which Mythril flags.

## How to Reproduce
`myth -xo json filename`

**Comment by norhh** [comment]
Dependence on predictable environment variable means dependence on timestamp, blockhash etc for sending `ether>0`. 
in this case the modifier uses `now` right? that's what gives out the timestamp of block.
timestamp can be manipulated by miner to some extent by a few seconds,
