### ISSUE TITLE
CFG HTML output is broken

### ISSUE THREAD

**Issue by b-mueller** [ConsenSys/mythril#488]
## Description

The CFG HTML file is broken in master. CFG is shown in a small frame:

![screen shot 2018-08-30 at 18 26 48](https://user-images.githubusercontent.com/5194767/44848799-4cdbcf80-ac82-11e8-80b3-b9ab0cb9871a.png)

## How to Reproduce

```
$./myth -g cfg.html -ia 0x35efabf6e2d970a3bc3fa1de991ec63987c127bc
```

## Expected behavior

CFG should be displayed in full frame as usual.

## Environment

- Mythril version: 4446b7692570b6188794b29992c8d174b61a2a04
- Python version: 3.6..3
- OS and Version: Mac OS High Sierra

**Comment by norhh** [comment]
Probably due to the change in html version when DOCTYPE string was added

**Comment by dmuhs** [comment]
Working on this. Seems to be a relatively straightforward issue with the browser rendering engines switching to standards mode now that the doctype is specified.
