### ISSUE TITLE
Long execution time

### ISSUE THREAD

**Issue by AyaCoin** [ConsenSys/mythril#500]
## Description

I'm running Mythril on Ubuntu 18.04, and although it executes in a few seconds on sample contracts, when I run it on my own contract, it's been running for over 2 hours now without any signs of life. It doesn't appear to be hung, although I'm doubting that it should be taking this long. 

Given that the contract being analyzed is 234 lines of code which creates a relatively straightforward token, I'm wondering if there's an issue or if maybe I'm must not being patient enough?

I don't see any reference in the documentation to what kind of timeline to expect, and I'm not seeing any live videos of anyone else using this, so I don't really have a frame of reference. So any helpful input in this regard would be appreciated.

## How to Reproduce

`myth -x AyaCoin.sol`
Contract code: https://github.com/AyaCoin/AyaCoin-smart-contract/blob/master/AyaCoin.sol

## Environment

Ubuntu: 18.04
Python: 3.6.5
Mythril: 0.18.11
Solc: 0.4.24+commit.e67f0147.Linux.g++

**Comment by norhh** [comment]
hey @AyaCoin , it's not just 234 lines , it also adds all the libraries and analyses them through that too, so. I encountered a similar problem sometimes but in my case my pc got hung, can you mention the RAM of the PC you are using?

**Comment by AyaCoin** [comment]
You make a good point about the libraries, although the weird thing is that a colleague of mine ran it on an instance of Ubuntu 16.04 and it finished within a matter of 30 seconds or less, so I'm working my way through the (difficult) installation process on a VM that still has 16.04.

To answer your question though, it has 4GB or RAM.

Thanks also for your suggestions to specify a max-depth. I had hoped for a comprehensive analysis, but I'll keep that suggestion in mind if this doesn't work on 16.04. And I'll report back either way.

**Comment by norhh** [comment]
probably OS shouldn't matter here, mine is 17.10 and it takes around 2-3 minutes, Also VM might probably slow it down.Also is your colleague's processor and yours similar?

**Comment by AyaCoin** [comment]
Well, I installed Mythril on a fresh installation of Ubuntu 16.04, and Mythril ran and finished on the contract in about 20 seconds. I have no idea what components are being changed from 16.04 to 18.04, but the process of upgrading to 18.04 is what seems to have killed it somehow.

One small suggestion is that it'd be helpful if the program at least said "Looks good!" Or had some other sort of confirmation message to let the user know that the contract analyzed passed without any notable issues vs. just returning to a blank prompt without any feedback whatsoever. 

Also, it seems that you have to be very careful regarding what version of things you're running and in what order you install them in. To be honest, I'm not much a Linux user, though I have been an IT Manager in a Windows environment for several years, and this is probably the single most difficult program I've ever had to install.

In the end, my colleague did the following on a completely fresh installation of Ubuntu 16.04 since I was apparently running into version conflicts on a pre-existing version of Ubuntu:
```
apt-get install python3-pip
apt-get update
apt-get install -y software-properties-common
add-apt-repository -y ppa:ethereum/ethereum
apt-get install -y solc
pip3 install mythril==0.8.11
pip3 uninstall web3
pip3 install web3==3.16.5
```
Hope this helps someone else further down the line.

**Comment by AyaCoin** [comment]
P.S. Thank you for developing such a helpful tool. I may have had difficulties installing it, but it's hugely beneficial, and I very much appreciate the value it adds to the crypto community.

**Comment by yxliang01** [comment]
@AyaCoin @norhh Any idea on whether running on Ubuntu 16.04 is really so much faster than Ubuntu 18.04?

**Comment by norhh** [comment]
@yxliang01 I think it mainly depends on the processor rather than the operating system.

**Comment by yxliang01** [comment]
> Well, I installed Mythril on a fresh installation of Ubuntu 16.04, and Mythril ran and finished on the contract in about 20 seconds. I have no idea what components are being changed from 16.04 to 18.04, but the process of upgrading to 18.04 is what seems to have killed it somehow.
> 
> One small suggestion is that it'd be helpful if the program at least said "Looks good!" Or had some other sort of confirmation message to let the user know that the contract analyzed passed without any notable issues vs. just returning to a blank prompt without any feedback whatsoever.
> 
> Also, it seems that you have to be very careful regarding what version of things you're running and in what order you install them in. To be honest, I'm not much a Linux user, though I have been an IT Manager in a Windows environment for several years, and this is probably the single most difficult program I've ever had to install.
> 
> In the end, my colleague did the following on a completely fresh installation of Ubuntu 16.04 since I was apparently running into version conflicts on a pre-existing version of Ubuntu:
> 
> ```
> apt-get install python3-pip
> apt-get update
> apt-get install -y software-properties-common
> add-apt-repository -y ppa:ethereum/ethereum
> apt-get install -y solc
> pip3 install mythril==0.8.11
> pip3 uninstall web3
> pip3 install web3==3.16.5
> ```
> 
> Hope this helps someone else further down the line.

@norhh Well, I think it is. But, I was just referring to this. Since it's also possible to have incompatibility causing performance degradation.

**Comment by norhh** [comment]
@yxliang01 Mythril wasn't written by thinking of any specific OS version. Currently, I can't see any performance difference between Ubuntu 16 and 17 for the latest mythril develop branch.  Maybe 18.04 wasn't stable at that time and had a buggy process scheduling. Or probably the versions tried there might be different like 0.18.11 analyzes a single transaction whereas 0.18.12 analyzes multiple transactions.

**Comment by yxliang01** [comment]
Alright, thanks for your detailed comment! @norhh

**Comment by 0x0918** [comment]
> 该图看起来很大（而且有点糟糕），但我仍然不确定它应该以多快的速度完成：
> 
> ![图像](https://user-images.githubusercontent.com/37425279/45261061-1f9bc980-b3c6-11e8-9925-4362c7e04936.png)

Hi, which tool did you use to view the invocation path of the contract in this graph?

**Comment by norhh** [comment]
Hi @0x0918 , you can use mythril for this. 
Something like
`myth -v4 analyze <filename> -g output.html`
