### ISSUE TITLE
Severity of issues raised by Mythril

### ISSUE THREAD

**Issue by shashank-srikant** [ConsenSys/mythril#504]
I couldn't seem to find good documentation which explains the severity of issues currently raised by Mythril.
I see that issues currently are annotated with a `type` which can read either as a `warning` or `information`.

Can we have this more well defined? And added to the Wiki?

Thanks.

**Comment by norhh** [comment]
hi @shashank-srikant , it's kind of in progress currently, https://github.com/ConsenSys/mythril/wiki/Vulnerabilities is the wiki page related to that.
or you can also check [this](https://github.com/ConsenSys/mythril/wiki/Mythril-Detection-Capabilities) where there are references to the corresponding problems.

**Comment by shashank-srikant** [comment]
i see. sure
my concern is not much with understanding what the nature of these vulnerabilities are - i think they've been decently documented.
i'd specifically like to understand the significance of the `type` field in the output reports, and want to understand the basis of classifying something as `information` versus a `warning`.
i want to understand the different `type`s and map them to the list of vulnerabilities.

**Comment by JoranHonig** [comment]
This issue seems finished with work going on in a different repository, therefore I'm closing this issue
