### ISSUE TITLE
Could not connect to RPC server. Make sure that your node is running and that RPC parameters are set correctly.

### ISSUE THREAD

**Issue by dovancao** [ConsenSys/mythril#506]
## Screenshots
![screenshot_1 2 _li](https://user-images.githubusercontent.com/36324165/45401765-674b7b00-b67c-11e8-9fbc-dbc68df6a7ef.jpg)

Hi everyone, I got this message when try to run "docker" in my computer.

As the picture, I run this command
```
docker run mythril/myth --rpc ganache -d -a "0x84f391e9259700723bd82721769bdde2e1c8bdf5"
```

This is system and tools which i used
```
- Window 10
- Ganache CLI v6.1.8 
- Newest Docker
```
Thank you for your help!

**Comment by norhh** [comment]
Hi @dovancao , In this case what might be happening is that the docker cannot find any ganache running inside the container, so it is resulting in an error.
try
`sudo docker run --network="host" mythril/myth --rpc localhost:8545 -da 0xe94a93e43551513d46197c649bfba9f9d6d73f59`
change the port from 8545 to default of ganache. 
Also can you please mention the port on which your ganache was running?As mine runs on 8545 but mythril is using 7545.

**Comment by dovancao** [comment]
Thank you so much. I solved that issue
