### ISSUE TITLE
Z3Exception when analyzing solidity code

### ISSUE THREAD

**Issue by jstoeffler** [ConsenSys/mythril#51]
I'm trying to analyze the solidity source code of [this contract](https://etherscan.io/address/0xa7ca36f7273d4d38fc2aec5a454c497f86728a7a#code) by running 

`myth -x ./PonziTokenV3.sol`

The error is

z3.z3types.Z3Exception: Symbolic expressions cannot be cast to concrete Boolean values.

I've noticed this error only when --max-depth > 7

I'm on a mac using the pip3 version of mythril

**Comment by b-mueller** [comment]
Hi @jstoeffler, there was a bug in how the SDIV instruction was processed. It should work as of mythril 0.10.9!
