### ISSUE TITLE
Init-db doesn't seem to do anything

### ISSUE THREAD

**Issue by jstoeffler** [ConsenSys/mythril#52]
Hello,

I run a nod synced using `geth --syncmode "fast"`. It finished syncing, but when I run `myth --init-db` it outputs

    Starting synchronization from latest block: 0

and ends without any error right after.

I've tried to use the `--sync-all` and `--rpc` options but I get the same result. The .fs files in `~/.mythril/` are very small and `myth --search "func#changeMultisig(address)#"` doesn't find anything.

**Comment by step21** [comment]
Syncmode should not matter afaik. Is there no other output at all? Have you enabled rpc/ipc on the node? Which geth version?
Otherwise it is kinda hard to debug like that. Just for comparison the fs files should def be bigger and it should take a while, but the search is more normal f.e. on my files it also doesn't return anything on half-synced chain.

**Comment by jstoeffler** [comment]
Thanks for the answer!

I'm using `Geth/v1.7.3-stable`
I believe IPC is enabled because geth outputs

     INFO [02-06|07:19:37] IPC endpoint opened: /home/ubuntu/.ethereum/geth.ipc 

and when I run mythril **without geth running** I get

    Error syncing database over IPC: [Errno 2] No such file or directory

which I don't get when it's running, so I assume IPC isn't the problem

I've also tried running `myth --init-db --rpc localhost:8545`which fail when I run get normally:

     Could not connect to RPC server. Make sure that your node is running and that RPC parameters are set correctly.

but when I run `geth --syncmode "fast" --rpc` I get the same output:

    Starting synchronization from latest block: 0

before program ends. 

The only way it seems to work is with `myth --init-db --infura-mainnet`, then it outputs:

    Starting synchronization from latest block: 5039876
    Processing block 5039000, 3 unique contracts in database
    Processing block 5038000, 10 unique contracts in database
    ...

But it takes forever.

Here's the full `geth` log in case there's something there:

	ubuntu@ip-xxx-xxx-xxx-xxx:~$ geth --syncmode "fast" --rpc
	WARN [02-06|07:34:57] No etherbase set and no accounts found as default 
	INFO [02-06|07:34:57] Starting peer-to-peer node               instance=Geth/v1.7.3-stable-4bb3c89d/linux-amd64/go1.9
	INFO [02-06|07:34:57] Allocated cache and file handles         database=/home/ubuntu/.ethereum/geth/chaindata cache=128 handles=1024
	INFO [02-06|07:34:57] Initialised chain configuration          config="{ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000 Engine: ethash}"
	INFO [02-06|07:34:57] Disk storage enabled for ethash caches   dir=/home/ubuntu/.ethereum/geth/ethash count=3
	INFO [02-06|07:34:57] Disk storage enabled for ethash DAGs     dir=/home/ubuntu/.ethash               count=2
	INFO [02-06|07:34:57] Initialising Ethereum protocol           versions="[63 62]" network=1
	INFO [02-06|07:34:57] Loaded most recent local header          number=5039797 hash=11635e…08c1de td=2393124418221748417822
	INFO [02-06|07:34:57] Loaded most recent local full block      number=0       hash=d4e567…cb8fa3 td=17179869184
	INFO [02-06|07:34:57] Loaded most recent local fast block      number=5039499 hash=02c90e…31ee7a td=2392297964743664312070
	INFO [02-06|07:34:57] Loaded local transaction journal         transactions=0 dropped=0
	INFO [02-06|07:34:57] Regenerated local transaction journal    transactions=0 accounts=0
	INFO [02-06|07:34:57] Starting P2P networking 
	INFO [02-06|07:35:00] UDP listener up                          self=enode://11b6b16c0c67dadacc1c07333cf94b3c241d6b6ecbe5674a330aa2e43b4221dda74fb76009368a5d7e98582d73426323a1982681c4c6eab4dcc1ff2f625df95e@[::]:30303
	INFO [02-06|07:35:00] HTTP endpoint opened: http://127.0.0.1:8545 
	INFO [02-06|07:35:00] IPC endpoint opened: /home/ubuntu/.ethereum/geth.ipc 
	INFO [02-06|07:35:00] RLPx listener up                         self=enode://11b6b16c0c67dadacc1c07333cf94b3c241d6b6ecbe5674a330aa2e43b4221dda74fb76009368a5d7e98582d73426323a1982681c4c6eab4dcc1ff2f625df95e@[::]:30303
	INFO [02-06|07:35:20] Block synchronisation started 
	INFO [02-06|07:35:20] Imported new block headers               count=0 elapsed=16.024ms number=5039691 hash=7cd2f4…ad3931 ignored=192

**Comment by b-mueller** [comment]
Are you sure that geth is fully synced?

Try running `geth --syncmode fast console` and check the output of the following commands:

`eth.syncing`
`eth.blockNumber`

**Comment by jstoeffler** [comment]
I was under the impression that it was, but after double checking, I get:

	> eth.syncing
	{
	  currentBlock: 5049158,
	  highestBlock: 5049252,
	  knownStates: 242272,
	  pulledStates: 233600,
	  startingBlock: 5049128
	}
	> eth.blockNumber
	0


So it seems it's a problem with Geth, I've seen some issues on the repo, so I'll try to look there. 
I'll close this issue and report back if/when I find a solution, if someone has the same problem and I didn't, don't hesitate to ping :)

**Comment by b-mueller** [comment]
I actually had the same problem, geth almost syncs but never fully catches up.

The "solution" for me was to restart geth frequently and wait, until some day I woke up and it was finally synced. Probably not the best solution though, so please update the issue if you find a better one :)
