### ISSUE TITLE
metacoin.sol doesn't detect overflow

### ISSUE THREAD

**Issue by norhh** [ConsenSys/mythril#521]
## How to Reproduce
```console
$ ./myth -x tests/testdata/input_contracts/metacoin.sol 
The analysis was completed successfully. No issues were detected.
```

## Environment

- Mythril version: master
- Solidity compiler and version: `0.4.25`
- Python version: `3.6`
- OS and Version: Ubuntu 17.10

**Comment by b-mueller** [comment]
```
pragma solidity ^0.4.17;

contract MetaCoin {
	mapping (address => uint) public balances;
	function MetaCoin() public {
		balances[msg.sender] = 10000;
	}
	
	function sendToken(address receiver, uint amount) public returns(bool successful){
		if (balances[msg.sender] < amount) return false;
		balances[msg.sender] -= amount;
		balances[receiver] += amount;
		return false;
	}
}
```

Overflow is impossible because there's no way to increase `balances[msg.sender]` amirite?

**Comment by norhh** [comment]
Yeah, there is no overflow.  I didn't look at the code properly, I just remember previous `myth` output which detected an overflow here :stuck_out_tongue:  .
