### ISSUE TITLE
Include SWC ID in analysis results

### ISSUE THREAD

**Issue by b-mueller** [ConsenSys/mythril#526]
## Description

Include the [SWC ID](https://github.com/SmartContractSecurity/SWC-registry/) for each issue reported in the text, markdown and json outputs. This will make it easier to integrate with the SWC registry for benchmarking.

E.g.:

```
==== Unchecked CALL return value ====
SWC ID: 104
Type: Informational
Contract: ReturnValue
Function name: callnotchecked()
PC address: 294
The return value of an external call is not checked. Note that execution continue even if the called contract throws.
--------------------
In file: returnvalue.sol:5

function callnotchecked()  {
    callee.call();
  }

--------------------
```

Tagging @s0b0lev as it is relevant for SWC integration.

**Comment by JoranHonig** [comment]
It would also be cool/nice if we could make it a hyper link to the page describing it ( some terminal emulators should allow this )
