### ISSUE TITLE
Detect Tautologies

### ISSUE THREAD

**Issue by maurelian** [ConsenSys/mythril#54]
Example contract: 
```pragma solidity ^0.4.18;

contract MyContract {

  function foo(uint256 a) returns(uint256) {
    if(a >= 0){ //this will never be false
      return 0;
    }
    return 1;
  }
}```

Mythril should detect a comparison which is always true, at least one as simple as this.

**Comment by joshuata** [comment]
I am interested in working on this. I think we can do it fairly easily by checking the constraints on a block of the control-flow graph (essentially a reachability analysis). This can also be leveraged in other steps to remove false positives.

**Comment by b-mueller** [comment]
@JoranHonig and I were discussing this on [Gitter](https://gitter.im/ConsenSys/mythril) recently. I think the conclusion was that we that any path constraint that simplifies to "true" is a tautology.

**Comment by joshuata** [comment]
To accurately detect all tautologies (and simplify the CFG), it is likely more robust to check that the complement of the path constraint (!p) is UNSAT. This is the strategy I have used in other symbolic execution tools I have used, and catches simplifications in type constraints that are often missed by trying to reduce to boolean true.

**Comment by JoranHonig** [comment]
@b-mueller Unless I'm mistaken, if !p is unsat then the negation of that, p, must be true, because the sat solver will only say !p is unsat if it finds a contradiction.

**Comment by JoranHonig** [comment]
@b-mueller So I looked briefly at how laser handles conditional jumps and it already simplifies the cfg by checking if a path constraint is satisfiable and only following valid paths (+- ln 879 svm.py):
```
 elif (type(condition) == BoolRef):
                            if not is_false(simplify(condition)):
                            ### Here it builds the edge
```

So detecting tautologies should be trivial. I think, you'd need to look for nodes with a JUMPI instruction, and check if there are multiple outgoing edges ( if there is only one then there is a tautology ).

@joshuata do you still want to pick this up? Otherwise I could

**Comment by JoranHonig** [comment]
I have some time this weekend, so I will pick this up

**Comment by JoranHonig** [comment]
So there is an issue with this. The example code gets compiled to a situation
where the inverse of a >= 0 is checked and used as condition for a jump. The problem is that a compiler different from solidity might do the inverse ( so detecting a tautology in the sense of always true isn't possible, because we can't be sure how the compiler handles this).

**Comment by JoranHonig** [comment]
What we could analyze is if the condition for a jumpi is always true or always false. This would indicate a tautology and inverse tautology (dead branch)

**Comment by JoranHonig** [comment]
Output for the example:
```
==== Tautology ====
Type: Informational
Contract: MyContract
Function name: foo(uint256)
PC address: 130
Found a conditional jump which always follows the same branch
--------------------
In file: /home/walker/dev/mythril/tests/testdata/input_contracts/tautology.sol:4

if(a >= 0){ //this will never be false
      return 0;
    }

--------------------
```

**Comment by JoranHonig** [comment]
So it turns out that if you have a require(), then it does not use the inverse of the logical statement as conditional argument. So solidity sometimes uses the inverse of the actual condition and sometimes not.

**Comment by b-mueller** [comment]
Hmm I don't understand the issue. 

The compiler could  logically represented the condition `a >= 0` as either `a >= 0` or `¬(a < 0)`, but both are logically equivalent. So if `a >= 0` evaluates to tautology`¬(a < 0)` also does.

> What we could analyze is if the condition for a jumpi is always true or always false.

Yes, I think that's the way to do it.

**Comment by b-mueller** [comment]
OK I think I see what you mean. Yes, the detection only makes sense if we take control flow into consideration.

**Comment by JoranHonig** [comment]
Ok, so my current implementation checks if for each jumpi instruction if the condition is either always false or always true. 
And if thats the case creates an Issue

Would that still be called a tautology? Or would that need another name

**Comment by JoranHonig** [comment]
How about: "Static control flow path"?

**Comment by b-mueller** [comment]
I don't think "static" is the right word here.

**Comment by JoranHonig** [comment]
So it would look like this?:
```
==== Branch condition always evaluates to [true/false] ====
Type: Informational
Contract: MyContract
Function name: foo(uint256)
PC address: 130
Found a conditional jump which always follows the same branch
--------------------
In file: /home/walker/dev/mythril/tests/testdata/input_contracts/tautology.sol:4

if(a >= 0){ //this will never be false
      return 0;
    }

--------------------
```

**Comment by b-mueller** [comment]
Originally I meant "true" OR "false" in the title. But saying "branch
condition always evaluates to 'true'" should be fine.

**Comment by JoranHonig** [comment]
But then the title would be: Branch condition always evaluates to false.
As in this case the branch condition used by jumpi is (a < 0), while the if condition is a >=0

That might be confusing to a user

**Comment by JoranHonig** [comment]
Ok, so there seem to be a lot of false positives. Take weak_random.sol, this has a lot of jumpi instructions which could be jump instructions ( for example bc of a modulo operation)

**Comment by JoranHonig** [comment]
To clarify, this is the output of my fork on weak_random.sol:
```
==== Dependence on predictable environment variable ====
Type: Warning
Contract: WeakRandom
Function name: _function_0xe9874106
PC address: 1285
In the function `_function_0xe9874106` the following predictable state variables are used to determine Ether recipient:
- block.coinbase

--------------------
In file: /home/walker/dev/mythril/tests/testdata/input_contracts/weak_random.sol:47

winningAddress.transfer(prize)

--------------------

==== Ether send ====
Type: Warning
Contract: WeakRandom
Function name: _function_0xe9874106
PC address: 1285
In the function `_function_0xe9874106` a non-zero amount of Ether is sent to an address taken from storage slot 0.
There is a check on storage index 0. This storage slot can be written to by calling the function `fallback`.

There is a check on storage index 1. This storage slot can be written to by calling the function `fallback`.
There is a check on storage index 1. This storage slot can be written to by calling the function `fallback`.
--------------------
In file: /home/walker/dev/mythril/tests/testdata/input_contracts/weak_random.sol:47

winningAddress.transfer(prize)

--------------------

==== Exception state ====
Type: Informational
Contract: WeakRandom
Function name: fallback
PC address: 356
A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. 
--------------------
In file: /home/walker/dev/mythril/tests/testdata/input_contracts/weak_random.sol:11

prize / totalTickets

--------------------

==== Exception state ====
Type: Informational
Contract: WeakRandom
Function name: _function_0xe9874106
PC address: 146
A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. 
--------------------
In file: /home/walker/dev/mythril/tests/testdata/input_contracts/weak_random.sol:11

prize / totalTickets

--------------------

==== Invariant branch condition ====
Type: Informational
Contract: WeakRandom
Function name: fallback
PC address: 1142
Found a conditional jump which always follows the same branch
--------------------
In file: /home/walker/dev/mythril/tests/testdata/input_contracts/weak_random.sol:42

uint(randHash) % totalTickets

--------------------

==== Invariant branch condition ====
Type: Informational
Contract: WeakRandom
Function name: fallback
PC address: 912
Found a conditional jump which always follows the same branch
--------------------
In file: /home/walker/dev/mythril/tests/testdata/input_contracts/weak_random.sol:38

uint(msg.sender) % totalTickets

--------------------

==== Invariant branch condition ====
Type: Informational
Contract: WeakRandom
Function name: fallback
PC address: 821
Found a conditional jump which always follows the same branch
--------------------
In file: /home/walker/dev/mythril/tests/testdata/input_contracts/weak_random.sol:37

uint(block.coinbase) % totalTickets

--------------------

==== Invariant branch condition ====
Type: Informational
Contract: WeakRandom
Function name: fallback
PC address: 355
Found a conditional jump which always follows the same branch
--------------------
In file: /home/walker/dev/mythril/tests/testdata/input_contracts/weak_random.sol:11

prize / totalTickets

--------------------

==== Invariant branch condition ====
Type: Informational
Contract: WeakRandom
Function name: fallback
PC address: 145
Found a conditional jump which always follows the same branch
--------------------
In file: /home/walker/dev/mythril/tests/testdata/input_contracts/weak_random.sol:11

prize / totalTickets

--------------------

==== Invariant branch condition ====
Type: Informational
Contract: WeakRandom
Function name: _function_0xe9874106
PC address: 1424
Found a conditional jump which always follows the same branch
--------------------
In file: /home/walker/dev/mythril/tests/testdata/input_contracts/weak_random.sol:11

prize / totalTickets

--------------------
```

**Comment by JoranHonig** [comment]
Another thing that might happen is that solidity or another compiler might optimize compiled code so that the bytecode does not reflect the code(in which case the analysis module would become useless).

@b-mueller I'd propose the following. We still merge my code as behavior in the future might change, in which case we maybe could start using the module. Maybe we even find a way to filter benign cases. 
In addition to that I want to implement a way to "disable" analysis modules, so that the module won't get executed, and the users won't get overflown with Invariant branch detection issues.

**Comment by maurelian** [comment]
> If these tautology patterns often occur naturally it might be impossible to generate useful results here. @maurelian what do you think?

Sorry didn't see this before. Would it be possible to determine if the tautology is specifically used prior to a `REVERT` as in `require()`?

**Comment by JoranHonig** [comment]
Yes, that would be possible using some cfg exploration.

**Comment by maurelian** [comment]
My gut says that would at least partially address the issue, but maybe this is best done at the source code level where semantics are more easily extracted.

**Comment by b-mueller** [comment]
We should call it Muffle. Mythril + Truffle.

Or not.

**Comment by b-mueller** [comment]
> expanding to combined source and bytecode would drastically increase the complexity

It would, but it would also be much more powerful. The ultimate security analysis tool!

> My intent here is to not actually look for a solidity require(), but an un-reachable branch ending in REVERT.

I think laser-ethereum "prunes" those by default.

**Comment by maurelian** [comment]
> I think laser-ethereum "prunes" those by default.

So it's already detecting them then. Could a report be emitted when the pruning happens?

**Comment by JoranHonig** [comment]
I'll change the current implementation so that it tries to see if its in a requires statement. 
After that, this issue can probably be closed for now

**Comment by JoranHonig** [comment]
So @maurelian you'd basically want an issue when there is a conditional statement that always leads to a revert?

**Comment by maurelian** [comment]
@JoranHonig... that's my suggestion, the hypothesis being that it would detect something similar to `require(true)`.

**Comment by b-mueller** [comment]
FYI

```
    function test() public {
        require(true);
    }
```

<img width="1339" alt="screen shot 2018-05-23 at 16 50 44" src="https://user-images.githubusercontent.com/5194767/40417259-8998b1b2-5ea9-11e8-9560-515dceef3741.png">

```
contract COE {

    function test() public {
        require(false);
    }
}
```

<img width="1225" alt="screen shot 2018-05-23 at 16 51 53" src="https://user-images.githubusercontent.com/5194767/40417314-aa159cd4-5ea9-11e8-8acd-e9f8e1928398.png">

In each case, laser discards the always false branch and retains the always true branch.

**Comment by b-mueller** [comment]
It's meant to be a performance optimization so we don't follow paths that can never get executed. If we need to detect the "require(true)" case we'd need to:

1. In laser, execute and save the states of 1 basic block down the "always false" path
2. If that block ends in a revert or invalid instruction it's assumed to be an assert or require failure

**Comment by JoranHonig** [comment]
That seems like a lot of added complexity to laser for a small detection module

**Comment by ytrezq** [comment]
@JoranHonig too bad it didn t get implemented in a correct way.

Would it be possible to get it implemented, in a naive manner without getting the performance optimizations it deserve? Especially since getting Mythril not extremely slow is no longer an objective of the project.

**Comment by JoranHonig** [comment]
It's not about performance. It's just not a problem that symbolic execution is good at, with abstract interpretation you could get reasonably far.

**Comment by ytrezq** [comment]
> It's not about performance. It's just not a problem that symbolic execution is good at, with abstract interpretation you could get reasonably far.

@JoranHonig I know a lot of solver which would able to detect those cases. Wouldn t it possible to use z3 for that? At list only for simple cases.
What you re describing is rather for fuzzers which don t statically evaluate paths regarding the consequences of future paths.

**Comment by JoranHonig** [comment]
> I know a lot of solver which would able to detect those cases. Wouldn t it possible to use z3 for that? At list only for simple cases.

For sure! Just the simplification algorithm would probably do.

I guess it's more about the information that you can give. Symbolic execution would say "I haven't seen a path where the condition wasn't always true". Static analysis could say "there is no path where this condition isn't true".

I assume that with tautologies you're more interested in what static analysis can give you.
