### ISSUE TITLE
Can Mythril be installed on Window 10?

### ISSUE THREAD

**Issue by vardhmanandroid2015** [ConsenSys/mythril#540]
Description - I tried to install Mythril on Window 10 with Python-3.7.0 with PIP (**pip install mythril**). it download bunch of modules without any issue but got stuck at "    src/python/core.c(2): fatal error C1083: Cannot open include file: 'alloca.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "c:\users\abhishek.jain\appdata\local\programs\python\python37\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\ABHISH~1.JAI\\AppData\\Local\\Temp\\pip-install-zasn8v0c\\pyethash\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\ABHISH~1.JAI\AppData\Local\Temp\pip-record-e09b98m4\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\ABHISH~1.JAI\AppData\Local\Temp\pip-install-zasn8v0c\pyethash\"

How to Reproduce - 
1. On window 10 machine, Install python 3.7.0 version
2. pip install mythril

Collecting mythril
  Using cached https://files.pythonhosted.org/packages/f8/46/c8cac9bf90cbdd7a63125446ba0f96e17c423317d3d589cabbe418e24507/mythril-0.18.12.tar.gz
Collecting ethereum>=2.3.2 (from mythril)
  Using cached https://files.pythonhosted.org/packages/ca/48/bd2484ff00fad56bfabad46af8d91f0ab4c6844e389e00b00c7609b405e0/ethereum-2.3.2.tar.gz
Collecting z3-solver>=4.5 (from mythril)
  Downloading https://files.pythonhosted.org/packages/83/7e/9e3b84ed773945cfa3c00e64c3ef49c492bf4b6f60cf6223b8756053e7f4/z3-solver-4.8.0.0.post1.tar.gz (4.1MB)
    100% |████████████████████████████████| 4.1MB 333kB/s
Requirement already satisfied: requests in c:\users\abhishek.jain\appdata\local\programs\python\python37\lib\site-packages (from mythril) (2.13.0)
Collecting py-solc (from mythril)
  Using cached https://files.pythonhosted.org/packages/5d/8d/a20d1c0fa0083a7ee92fa48bb3561d824e20ce039d88db0ca7100c486fcb/py_solc-3.1.0-py3-none-any.whl
Collecting plyvel (from mythril)
  Downloading https://files.pythonhosted.org/packages/b3/1d/05e3555abddb49b9a2f3aa1268bec4933bf377ffcad3c1b2630fcfa597eb/plyvel-1.0.5.tar.gz (143kB)
    100% |████████████████████████████████| 153kB 730kB/s
Collecting eth_abi>=1.0.0 (from mythril)
  Using cached https://files.pythonhosted.org/packages/3d/4e/66d711f39c892c295cd61d2a241d26e4fa253e483382bdb34e39ea4c4d96/eth_abi-1.2.0-py3-none-any.whl
Collecting eth-utils>=1.0.1 (from mythril)
  Using cached https://files.pythonhosted.org/packages/97/35/6e41ccfecfdd422bb386f186c7288a3176af29d380419645723f5f0b534f/eth_utils-1.2.2-py3-none-any.whl
Collecting eth-account>=0.1.0a2 (from mythril)
  Using cached https://files.pythonhosted.org/packages/a3/d8/6118bc0e00d6ec092bb02b012989d1018893755eb84da53266412ac359e3/eth_account-0.3.0-py3-none-any.whl
Collecting eth-hash>=0.1.0 (from mythril)
  Using cached https://files.pythonhosted.org/packages/0d/d8/0f0c8d4ccaa4c8d25524fd1ed9f5c6d9551b52b74b973f338de3f0a23111/eth_hash-0.2.0-py3-none-any.whl
Collecting eth-keyfile>=0.5.1 (from mythril)
  Using cached https://files.pythonhosted.org/packages/eb/a5/3615d100b62fbf20fe5d5c0d1d4d7326eac861d260b0cd2a36af2bf8ccb1/eth_keyfile-0.5.1-py3-none-any.whl
Collecting eth-keys>=0.2.0b3 (from mythril)
  Using cached https://files.pythonhosted.org/packages/9b/96/bec507291a2ecac65358b4485282ce02e8c0cdd30980a232791b355a1f5b/eth_keys-0.2.0b3-py3-none-any.whl
Collecting eth-rlp>=0.1.0 (from mythril)
  Using cached https://files.pythonhosted.org/packages/56/4b/b309fb44dd9bb975e84f3d626392eec1eeed0108e55a51cd7dd8956a73ad/eth_rlp-0.1.2-py3-none-any.whl
Collecting eth-tester>=0.1.0b21 (from mythril)
  Downloading https://files.pythonhosted.org/packages/fc/6a/7f189676ea2065e55514c79e204ab6d9135631a32f139eb5650dd9175c29/eth_tester-0.1.0b32-py3-none-any.whl (58kB)
    100% |████████████████████████████████| 61kB 369kB/s
Collecting eth-typing<2.0.0,>=1.3.0 (from mythril)
  Using cached https://files.pythonhosted.org/packages/5f/cb/e941031a77d19eef05f8bcdd40f6d8a3b55b7fa45aa7100206d64216c29b/eth_typing-1.3.0-py3-none-any.whl
Collecting coverage (from mythril)
  Downloading https://files.pythonhosted.org/packages/35/fe/e7df7289d717426093c68d156e0fd9117c8f4872b6588e8a8928a0f68424/coverage-4.5.1.tar.gz (379kB)
    100% |████████████████████████████████| 389kB 316kB/s
Requirement already satisfied: jinja2>=2.9 in c:\users\abhishek.jain\appdata\local\programs\python\python37\lib\site-packages (from mythril) (2.10)
Collecting rlp>=1.0.1 (from mythril)
  Downloading https://files.pythonhosted.org/packages/98/88/6276aea1ded17ee6db53cc03a80bebdd9c71291dd29e65582314b4bc92fd/rlp-1.0.3-py2.py3-none-any.whl
Collecting transaction>=2.2.1 (from mythril)
  Downloading https://files.pythonhosted.org/packages/2e/fb/e4fd7f99e2349c86275037fa5ddd9a3700174df4779e6fd4b61408726f75/transaction-2.2.1-py2.py3-none-any.whl (52kB)
    100% |████████████████████████████████| 61kB 218kB/s
Collecting py-flags (from mythril)
  Downloading https://files.pythonhosted.org/packages/0b/84/9dac0652068c2901f56d37797eb2c303befdafc5f5131f041951b7c86e22/py_flags-1.1.2-py3-none-any.whl
Requirement already satisfied: mock in c:\users\abhishek.jain\appdata\local\programs\python\python37\lib\site-packages (from mythril) (2.0.0)
Requirement already satisfied: configparser>=3.5.0 in c:\users\abhishek.jain\appdata\local\programs\python\python37\lib\site-packages (from mythril) (3.5.0)
Collecting persistent>=4.2.0 (from mythril)
  Downloading https://files.pythonhosted.org/packages/55/5c/126a2403fc8934d1e0220a15e7d7c348407ebf8fcfa6ac619f842b27b71d/persistent-4.4.2-cp37-cp37m-win_amd64.whl (139kB)
    100% |████████████████████████████████| 143kB 596kB/s
Collecting coincurve>=7.0.0 (from ethereum>=2.3.2->mythril)
  Downloading https://files.pythonhosted.org/packages/9c/dc/bbad446f7491ef08905d425dfccb08250cd0e5678c7265844dbbfdc53779/coincurve-9.0.0-py2.py3-none-win_amd64.whl (257kB)
    100% |████████████████████████████████| 266kB 479kB/s
Requirement already satisfied: future in c:\users\abhishek.jain\appdata\local\programs\python\python37\lib\site-packages\future-0.16.0-py3.7.egg (from ethereum>=2.3.2->mythril) (0.16.0)
Collecting pbkdf2 (from ethereum>=2.3.2->mythril)
  Downloading https://files.pythonhosted.org/packages/02/c0/6a2376ae81beb82eda645a091684c0b0becb86b972def7849ea9066e3d5e/pbkdf2-1.3.tar.gz
Collecting py_ecc (from ethereum>=2.3.2->mythril)
  Downloading https://files.pythonhosted.org/packages/c9/49/6e07c459f57a497ebc69a98f6975289f5300bc3f05f7c0cc11c8272214a9/py_ecc-1.4.3.tar.gz
Collecting pyethash<1.0.0,>=0.1.27 (from ethereum>=2.3.2->mythril)
  Using cached https://files.pythonhosted.org/packages/6c/40/5bb02ad7e2fae9b04cd0c391dda81213bc786c30c8381b018600cfc7ce62/pyethash-0.1.27.tar.gz
Requirement already satisfied: pycryptodome>=3.4.7 in c:\users\abhishek.jain\appdata\local\programs\python\python37\lib\site-packages (from ethereum>=2.3.2->mythril) (3.6.6)
Collecting pysha3>=1.0.1 (from ethereum>=2.3.2->mythril)
  Using cached https://files.pythonhosted.org/packages/73/bf/978d424ac6c9076d73b8fdc8ab8ad46f98af0c34669d736b1d83c758afee/pysha3-1.0.2.tar.gz
Collecting PyYAML (from ethereum>=2.3.2->mythril)
  Using cached https://files.pythonhosted.org/packages/bf/96/d02ef8e1f3073e07ffdc240444e5041f403f29c0775f9f1653f18221082f/PyYAML-3.13-cp37-cp37m-win_amd64.whl
Collecting repoze.lru (from ethereum>=2.3.2->mythril)
  Using cached https://files.pythonhosted.org/packages/b0/30/6cc0c95f0b59ad4b3b9163bff7cdcf793cc96fac64cf398ff26271f5cf5e/repoze.lru-0.7-py3-none-any.whl
Collecting scrypt (from ethereum>=2.3.2->mythril)
  Downloading https://files.pythonhosted.org/packages/01/6f/3c8dd0f18f73ceddfbdd606c0c895ebb66748606682d77da3743c7c0c56f/scrypt-0.8.6.tar.gz (52kB)
    100% |████████████████████████████████| 61kB 880kB/s
Collecting semantic-version>=2.6.0 (from py-solc->mythril)
  Using cached https://files.pythonhosted.org/packages/28/be/3a7241d731ba89063780279a5433f5971c1cf41735b64a9f874b7c3ff995/semantic_version-2.6.0-py3-none-any.whl
Collecting parsimonious==0.8.0 (from eth_abi>=1.0.0->mythril)
  Using cached https://files.pythonhosted.org/packages/4a/89/32c55944cd30dff856f16859ee325b13c83c260d0c56c0eed511e8063c87/parsimonious-0.8.0.tar.gz
Collecting toolz<1,>0.8.2 (from eth-utils>=1.0.1->mythril)
  Using cached https://files.pythonhosted.org/packages/14/d0/a73c15bbeda3d2e7b381a36afb0d9cd770a9f4adc5d1532691013ba881db/toolz-0.9.0.tar.gz
Collecting cytoolz<1.0.0,>=0.8.2 (from eth-utils>=1.0.1->mythril)
  Using cached https://files.pythonhosted.org/packages/36/f4/9728ba01ccb2f55df9a5af029b48ba0aaca1081bbd7823ea2ee223ba7a42/cytoolz-0.9.0.1.tar.gz
Collecting hexbytes<1,>=0.1.0 (from eth-account>=0.1.0a2->mythril)
  Using cached https://files.pythonhosted.org/packages/18/bd/21697d93ee2153c8c12253262b740f571e94341d4cee411504032fff3f56/hexbytes-0.1.0-py3-none-any.whl
Collecting attrdict<3,>=2.0.0 (from eth-account>=0.1.0a2->mythril)
  Using cached https://files.pythonhosted.org/packages/35/bb/bac3e42ae04bc082c28cd8186bfb5b50fb240a4f7419f876c683125ccc8b/attrdict-2.0.0.tar.gz
Requirement already satisfied: MarkupSafe>=0.23 in c:\users\abhishek.jain\appdata\local\programs\python\python37\lib\site-packages (from jinja2>=2.9->mythril) (1.0)
Requirement already satisfied: zope.interface in c:\users\abhishek.jain\appdata\local\programs\python\python37\lib\site-packages (from transaction>=2.2.1->mythril) (4.5.0)
Collecting dictionaries==0.0.1 (from py-flags->mythril)
  Downloading https://files.pythonhosted.org/packages/4d/54/b45e79bcfb116b7f946cb91f3955618b01a1f80dc0ee85da0d68fcc5f318/dictionaries-0.0.1-py2.py3-none-any.whl
Requirement already satisfied: pbr>=0.11 in c:\users\abhishek.jain\appdata\local\programs\python\python37\lib\site-packages (from mock->mythril) (4.2.0)
Requirement already satisfied: six>=1.9 in c:\users\abhishek.jain\appdata\local\programs\python\python37\lib\site-packages\six-1.11.0-py3.7.egg (from mock->mythril) (1.11.0)
Requirement already satisfied: cffi>=1.3.0 in c:\users\abhishek.jain\appdata\local\programs\python\python37\lib\site-packages (from coincurve>=7.0.0->ethereum>=2.3.2->mythril) (1.11.5)
Requirement already satisfied: asn1crypto in c:\users\abhishek.jain\appdata\local\programs\python\python37\lib\site-packages (from coincurve>=7.0.0->ethereum>=2.3.2->mythril) (0.24.0)
Requirement already satisfied: setuptools in c:\users\abhishek.jain\appdata\local\programs\python\python37\lib\site-packages (from zope.interface->transaction>=2.2.1->mythril) (39.0.1)
Requirement already satisfied: pycparser in c:\users\abhishek.jain\appdata\local\programs\python\python37\lib\site-packages (from cffi>=1.3.0->coincurve>=7.0.0->ethereum>=2.3.2->mythril) (2.18)
Installing collected packages: coincurve, pbkdf2, py-ecc, pyethash, pysha3, PyYAML, repoze.lru, eth-hash, toolz, eth-typing, cytoolz, eth-utils, rlp, scrypt, ethereum, z3-solver, semantic-version, py-solc, plyvel, parsimonious, eth-abi, eth-keys, eth-keyfile, hexbytes, eth-rlp, attrdict, eth-account, eth-tester, coverage, transaction, dictionaries, py-flags, persistent, mythril
  Running setup.py install for pbkdf2 ... done
  Running setup.py install for py-ecc ... done
  Running setup.py install for pyethash ... error
    Complete output from command c:\users\abhishek.jain\appdata\local\programs\python\python37\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\ABHISH~1.JAI\\AppData\\Local\\Temp\\pip-install-zasn8v0c\\pyethash\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\ABHISH~1.JAI\AppData\Local\Temp\pip-record-e09b98m4\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'pyethash' extension
    creating build
    creating build\temp.win-amd64-3.7
    creating build\temp.win-amd64-3.7\Release
    creating build\temp.win-amd64-3.7\Release\src
    creating build\temp.win-amd64-3.7\Release\src\python
    creating build\temp.win-amd64-3.7\Release\src\libethash
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\abhishek.jain\appdata\local\programs\python\python37\include -Ic:\users\abhishek.jain\appdata\local\programs\python\python37\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /Tcsrc/python/core.c /Fobuild\temp.win-amd64-3.7\Release\src/python/core.obj -Isrc/ -std=gnu99 -Wall
    cl : Command line warning D9002 : ignoring unknown option '-std=gnu99'
    core.c
    C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\corecrt_io.h(49): warning C4820: '_finddata32i64_t': '4' bytes padding added after data member 'name'
    C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\corecrt_io.h(54): warning C4820: '_finddata64i32_t': '4' bytes padding added after data member 'attrib'
    C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\corecrt_io.h(64): warning C4820: '__finddata64_t': '4' bytes padding added after data member 'attrib'
    C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\corecrt_io.h(69): warning C4820: '__finddata64_t': '4' bytes padding added after data member 'name'
    C:\Program Files (x86)\Windows Kits\8.1\include\shared\basetsd.h(418): warning C4668: '_WIN32_WINNT' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
    C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\time.h(35): warning C4820: '_timespec64': '4' bytes padding added after data member 'tv_nsec'
    C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\time.h(42): warning C4820: 'timespec': '4' bytes padding added after data member 'tv_nsec'
    c:\users\abhishek.jain\appdata\local\programs\python\python37\include\object.h(381): warning C4820: '_typeobject': '4' bytes padding added after data member 'tp_flags'
    c:\users\abhishek.jain\appdata\local\programs\python\python37\include\object.h(425): warning C4820: '_typeobject': '4' bytes padding added after data member 'tp_version_tag'
    c:\users\abhishek.jain\appdata\local\programs\python\python37\include\object.h(440): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member 'slot'
    c:\users\abhishek.jain\appdata\local\programs\python\python37\include\object.h(448): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member 'flags'
    c:\users\abhishek.jain\appdata\local\programs\python\python37\include\pytime.h(123): warning C4115: 'timeval': named type definition in parentheses
    c:\users\abhishek.jain\appdata\local\programs\python\python37\include\bytearrayobject.h(30): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member 'ob_exports'
    c:\users\abhishek.jain\appdata\local\programs\python\python37\include\bytesobject.h(41): warning C4820: '<unnamed-tag>': '7' bytes padding added after data member 'ob_sval'
    c:\users\abhishek.jain\appdata\local\programs\python\python37\include\bytesobject.h(165): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member 'small_buffer'
    c:\users\abhishek.jain\appdata\local\programs\python\python37\include\unicodeobject.h(330): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member 'state'
    c:\users\abhishek.jain\appdata\local\programs\python\python37\include\unicodeobject.h(905): warning C4820: '<unnamed-tag>': '2' bytes padding added after data member 'readonly'
    c:\users\abhishek.jain\appdata\local\programs\python\python37\include\longintrepr.h(88): warning C4820: '_longobject': '4' bytes padding added after data member 'ob_digit'
    c:\users\abhishek.jain\appdata\local\programs\python\python37\include\memoryobject.h(45): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member 'flags'
    c:\users\abhishek.jain\appdata\local\programs\python\python37\include\memoryobject.h(62): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member 'flags'
    c:\users\abhishek.jain\appdata\local\programs\python\python37\include\methodobject.h(61): warning C4820: 'PyMethodDef': '4' bytes padding added after data member 'ml_flags'
    c:\users\abhishek.jain\appdata\local\programs\python\python37\include\moduleobject.h(62): warning C4820: 'PyModuleDef_Slot': '4' bytes padding added after data member 'slot'
    c:\users\abhishek.jain\appdata\local\programs\python\python37\include\pystate.h(48): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member 'utf8_mode'
    c:\users\abhishek.jain\appdata\local\programs\python\python37\include\pystate.h(51): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member 'argc'
    c:\users\abhishek.jain\appdata\local\programs\python\python37\include\pystate.h(55): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member 'nxoption'
    c:\users\abhishek.jain\appdata\local\programs\python\python37\include\pystate.h(58): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member 'nwarnoption'
    c:\users\abhishek.jain\appdata\local\programs\python\python37\include\pystate.h(68): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member 'nmodule_search_path'
    c:\users\abhishek.jain\appdata\local\programs\python\python37\include\pystate.h(77): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member '_disable_importlib'
    c:\users\abhishek.jain\appdata\local\programs\python\python37\include\pystate.h(95): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member 'install_signal_handlers'
    c:\users\abhishek.jain\appdata\local\programs\python\python37\include\pystate.h(222): warning C4820: '_ts': '2' bytes padding added after data member 'recursion_critical'
    c:\users\abhishek.jain\appdata\local\programs\python\python37\include\pystate.h(230): warning C4820: '_ts': '4' bytes padding added after data member 'use_tracing'
    c:\users\abhishek.jain\appdata\local\programs\python\python37\include\pystate.h(253): warning C4820: '_ts': '4' bytes padding added after data member 'gilstate_counter'
    c:\users\abhishek.jain\appdata\local\programs\python\python37\include\pystate.h(287): warning C4820: '_ts': '4' bytes padding added after data member 'coroutine_origin_tracking_depth'
    c:\users\abhishek.jain\appdata\local\programs\python\python37\include\pystate.h(290): warning C4820: '_ts': '4' bytes padding added after data member 'in_coroutine_wrapper'
    c:\users\abhishek.jain\appdata\local\programs\python\python37\include\genobject.h(33): warning C4820: '<unnamed-tag>': '7' bytes padding added after data member 'gi_running'
    c:\users\abhishek.jain\appdata\local\programs\python\python37\include\genobject.h(53): warning C4820: '<unnamed-tag>': '7' bytes padding added after data member 'cr_running'
    c:\users\abhishek.jain\appdata\local\programs\python\python37\include\genobject.h(70): warning C4820: '<unnamed-tag>': '7' bytes padding added after data member 'ag_running'
    c:\users\abhishek.jain\appdata\local\programs\python\python37\include\descrobject.h(29): warning C4820: 'wrapperbase': '4' bytes padding added after data member 'offset'
    c:\users\abhishek.jain\appdata\local\programs\python\python37\include\descrobject.h(33): warning C4820: 'wrapperbase': '4' bytes padding added after data member 'flags'
    c:\users\abhishek.jain\appdata\local\programs\python\python37\include\structseq.h(20): warning C4820: 'PyStructSequence_Desc': '4' bytes padding added after data member 'n_in_sequence'
    c:\users\abhishek.jain\appdata\local\programs\python\python37\include\pyerrors.h(18): warning C4820: '<unnamed-tag>': '7' bytes padding added after data member 'suppress_context'
    c:\users\abhishek.jain\appdata\local\programs\python\python37\include\pyerrors.h(22): warning C4820: '<unnamed-tag>': '7' bytes padding added after data member 'suppress_context'
    c:\users\abhishek.jain\appdata\local\programs\python\python37\include\pyerrors.h(32): warning C4820: '<unnamed-tag>': '7' bytes padding added after data member 'suppress_context'
    c:\users\abhishek.jain\appdata\local\programs\python\python37\include\pyerrors.h(39): warning C4820: '<unnamed-tag>': '7' bytes padding added after data member 'suppress_context'
    c:\users\abhishek.jain\appdata\local\programs\python\python37\include\pyerrors.h(48): warning C4820: '<unnamed-tag>': '7' bytes padding added after data member 'suppress_context'
    c:\users\abhishek.jain\appdata\local\programs\python\python37\include\pyerrors.h(53): warning C4820: '<unnamed-tag>': '7' bytes padding added after data member 'suppress_context'
    c:\users\abhishek.jain\appdata\local\programs\python\python37\include\pyerrors.h(65): warning C4820: '<unnamed-tag>': '7' bytes padding added after data member 'suppress_context'
    c:\users\abhishek.jain\appdata\local\programs\python\python37\include\modsupport.h(90): warning C4820: '_PyArg_Parser': '4' bytes padding added after data member 'max'
    c:\users\abhishek.jain\appdata\local\programs\python\python37\include\pylifecycle.h(15): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member 'user_err'
    c:\users\abhishek.jain\appdata\local\programs\python\python37\include\import.h(143): warning C4820: '_frozen': '4' bytes padding added after data member 'size'
    c:\users\abhishek.jain\appdata\local\programs\python\python37\include\fileutils.h(66): warning C4820: '_Py_stat_struct': '4' bytes padding added after data member 'st_dev'
    c:\users\abhishek.jain\appdata\local\programs\python\python37\include\fileutils.h(68): warning C4820: '_Py_stat_struct': '2' bytes padding added after data member 'st_mode'
    c:\users\abhishek.jain\appdata\local\programs\python\python37\include\fileutils.h(72): warning C4820: '_Py_stat_struct': '4' bytes padding added after data member 'st_rdev'
    c:\users\abhishek.jain\appdata\local\programs\python\python37\include\fileutils.h(75): warning C4820: '_Py_stat_struct': '4' bytes padding added after data member 'st_atime_nsec'
    c:\users\abhishek.jain\appdata\local\programs\python\python37\include\fileutils.h(77): warning C4820: '_Py_stat_struct': '4' bytes padding added after data member 'st_mtime_nsec'
    src/python/core.c(2): fatal error C1083: Cannot open include file: 'alloca.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "c:\users\abhishek.jain\appdata\local\programs\python\python37\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\ABHISH~1.JAI\\AppData\\Local\\Temp\\pip-install-zasn8v0c\\pyethash\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\ABHISH~1.JAI\AppData\Local\Temp\pip-record-e09b98m4\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\ABHISH~1.JAI\AppData\Local\Temp\pip-install-zasn8v0c\pyethash\

**Comment by norhh** [comment]
hey @vardhmanandroid2015, currently mythril doesn't support windows, Also i don't think we can add a dist package dependency as currently our release is from `python pip`, if there is a way then let us know, it would be awesome :+1: .Best way to use mythril on windows/ubuntu is through docker as there wouldn't be any problems like this.
