### ISSUE TITLE
myth: command not found

### ISSUE THREAD

**Issue by msayyad** [ConsenSys/mythril#546]
after doing steps for installing mythril, ubuntu shell will show error and cant find it:

hex0r@ubuntu:~$ myth
myth: command not found

**Comment by dmuhs** [comment]
Did you install Mythril using `pip3`?
In that case on Ubuntu your binary should be located in `/home/<username>/.local/bin/myth`. With `echo $PATH` you can output your current path variable to make sure that the path contains the local bin directory.

**Comment by msayyad** [comment]
i install it using pip3. i run mythril from /.local/binmyth but get error

> uuu@ubuntu:~/.local/bin$ myth
> Traceback (most recent call last):
>   File "/usr/local/bin/myth", line 4, in <module>
>     __import__('pkg_resources').run_script('mythril==0.18.11', 'myth')
>   File "/home/hex0r/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 661, in run_script
>     self.require(requires)[0].run_script(script_name, ns)
>   File "/home/hex0r/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1441, in run_script
>     exec(code, namespace, namespace)
>   File "/usr/local/lib/python3.5/dist-packages/mythril-0.18.11-py3.5.egg/EGG-INFO/scripts/myth", line 6, in <module>
>     import mythril.interfaces.cli
>   File "/usr/local/lib/python3.5/dist-packages/mythril-0.18.11-py3.5.egg/mythril/interfaces/cli.py", line 16, in <module>
>     from mythril.mythril import Mythril
>   File "/usr/local/lib/python3.5/dist-packages/mythril-0.18.11-py3.5.egg/mythril/mythril.py", line 13, in <module>
>     from ethereum import utils
>   File "/home/hex0r/.local/lib/python3.5/site-packages/ethereum/__init__.py", line 11, in <module>
>     from . import slogging  # noqa
>   File "/home/hex0r/.local/lib/python3.5/site-packages/ethereum/slogging.py", line 6, in <module>
>     from ethereum.utils import bcolors, is_numeric
>   File "/home/hex0r/.local/lib/python3.5/site-packages/ethereum/utils.py", line 11, in <module>
>     import rlp
>   File "/home/hex0r/.local/lib/python3.5/site-packages/rlp/__init__.py", line 1, in <module>
>     from . import sedes  # noqa: F401
>   File "/home/hex0r/.local/lib/python3.5/site-packages/rlp/sedes/__init__.py", line 4, in <module>
>     from .big_endian_int import BigEndianInt, big_endian_int  # noqa: F401
>   File "/home/hex0r/.local/lib/python3.5/site-packages/rlp/sedes/big_endian_int.py", line 1, in <module>
>     from eth_utils import (
>   File "/home/hex0r/.local/lib/python3.5/site-packages/eth_utils/__init__.py", line 24, in <module>
>     from .applicators import (  # noqa: F401
>   File "/home/hex0r/.local/lib/python3.5/site-packages/eth_utils/applicators.py", line 29, in <module>
>     def combine_argument_formatters(*formatters: List[Callable[..., Any]]) -> Formatters:
>   File "/usr/lib/python3.5/typing.py", line 1025, in __getitem__
>     tvars = _type_vars(params)
>   File "/usr/lib/python3.5/typing.py", line 284, in _type_vars
>     _get_type_vars(types, tvars)
>   File "/usr/lib/python3.5/typing.py", line 279, in _get_type_vars
>     t._get_type_vars(tvars)
>   File "/usr/lib/python3.5/typing.py", line 786, in _get_type_vars
>     _get_type_vars(self.__args__, tvars)
>   File "/usr/lib/python3.5/typing.py", line 277, in _get_type_vars
>     for t in types:
> TypeError: 'ellipsis' object is not iterable
>

**Comment by dmuhs** [comment]
This seems to be an issue with the typing of Python 3.5. Can you provide the output of `python3.5 -V`? There might be typing issues with versions below Python 3.5.3.

**Comment by dmuhs** [comment]
@msayyad Any update on the issue?

**Comment by msayyad** [comment]
@dmuhs i install python 3.5.5 from source and try with pip3 but this erorr

    error: could not create '/usr/local/lib/python3.5/site-packages/pycparser': Permission denied
    
    ----------------------------------------
Command "/usr/local/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-e3wncqpq/pycparser/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-m15xzmef-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-e3wncqpq/pycparser/
You are using pip version 9.0.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by dmuhs** [comment]
@msayyad This seems to be less of an issue connected to Mythril but rather a permission issue with your Python installation. Please [check](https://github.com/googlesamples/assistant-sdk-python/issues/236) out [other](https://github.com/pypa/pip/issues/4186) solutions [for](https://stackoverflow.com/questions/31512422/pip-install-r-oserror-errno-13-permission-denied) that [problem](https://stackoverflow.com/questions/27849412/permissionerror-with-pip3).

**Comment by JoranHonig** [comment]
This seems to be a stale issue -> closing 🙌

**Comment by DmytroShalaiev** [comment]
Have same issue, installed using pip3

```
illuschwo@MacBook-Pro-Dmytro dist % mytxs-cli
zsh: command not found: mytxs-cli
illuschwo@MacBook-Pro-Dmytro dist % mythx
zsh: command not found: mythx
illuschwo@MacBook-Pro-Dmytro dist % 
```

```
illuschwo@MacBook-Pro-Dmytro site-packages % pip3 show mythx-cli    
Name: mythx-cli
Version: 0.7.2
Summary: A command line interface for the MythX smart contract security analysis API
Home-page: https://github.com/dmuhs/mythx-cli
Author: Dominik Muhs
Author-email: dominik.muhs@consensys.net
License: MIT license
Location: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages
Requires: Click, htmlmin, Jinja2, MarkupSafe, py-solc-x, pythx, PyYAML, tabulate
Required-by: 
illuschwo@MacBook-Pro-Dmytro site-packages % 
```

**Comment by RojhatToptamus** [comment]
You should add Mythril location to the PATH

1. Copy the location: `pip3 show Mythril `
2. `open ~/.zshrc  `
3. Paste the location on zshrc file: `export PATH="/Library/Frameworks/Python.framework/Versions/3.10/bin:${PATH}"`
4. Update the CLI: `source ~/.zshrc`
5. `myth`

**Comment by pietrociatta** [comment]
> Location:

Follower your guide, but still "command not found"... i've the same path as the previous guy /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages but in your guide you say to add another one... why?

**Comment by prik** [comment]
> Follower your guide, but still "command not found"... i've the same path as the previous guy /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages but in your guide you say to add another one... why?

For those with the same question, here is the likely solution:

```
export PATH=$PATH:/Users/[USER]/Library/Python/3.9/bin
source ~/.zshrc
```

Replace 3.9 with your version if needed. 
I hope this helped 🥂
