### ISSUE TITLE
Use SWC-registry exports for issue reporting 

### ISSUE THREAD

**Issue by thec00n** [ConsenSys/mythril#575]
## Description

It be great to align Mythril terminology e.g. weakness title to the one used in the SWC-registry. We now export all SWC definitions as a json file to a fixed location in the SWC-registry https://raw.githubusercontent.com/SmartContractSecurity/SWC-registry/master/export/swc-definition.json. Every new commit to master updates the json file. 

Consider fetching the json file from the mentioned path and include it in every future build for Mythril OSS. Use the data to:

1.) Replace current titles with the one from the SWC-registry
2.) Include the SWC link 
3.) Remove the currently hardcoded SWC ids in: https://github.com/norhh/mythril/blob/b5bcca6ee9ab31b187a1db55e84589b423f4afa9/mythril/analysis/swc_data.py. 

In general SWC ids are the string "SWC", dash "-" and a three digit number e.g. "100"

**Comment by JoranHonig** [comment]
@norhh Just to make sure you haven't missed this: We're going to delay the development of this until there is a python SWC package to easily interface with mythril

**Comment by JoranHonig** [comment]
This seems to be a stale issue -> closing 🙌
