### ISSUE TITLE
Globs only test the first contract

### ISSUE THREAD

**Issue by maurelian** [ConsenSys/mythril#58]
## Issue:

`myth -x contracts/*.sol` 

Will return results for the first contract in the `contracts` dir, and ignore all others. 

This can lead to the mistaken belief that all contracts have been analysed.

**Comment by b-mueller** [comment]
The solution here depends on the way how we want multiple contracts to be treated.

Currently, Mythril loads all contracts and maps them to different addresses (0x0000(...), 0x1111(...)). It then execute the *first* contract as the entrypoint (see also #58). The idea was to allow analysis of multiple interdependent contracts.

It seems that this behavior is confusing, as users expect the contracts to be analyzed on-by-one. 

Would it make sense to change this to be in line with expectations, and allow multi-contract analysis only for on-chain targets?

**Comment by b-mueller** [comment]
[Input files are now analyzed one-by-one](https://github.com/ConsenSys/mythril/commit/a412d78b4dfd9b60dc7133d4e2d514ba5f42b7d7).
