### ISSUE TITLE
Add option to specify solc include path

### ISSUE THREAD

**Issue by b-mueller** [ConsenSys/mythril#63]

**Comment by b-mueller** [comment]
Not 100% sure how to implement this. Solc has an option to do path remappings and it is also possible to specify a fallback path. @GNSPS, would it be sufficient to add an option for setting the fallback path?

**Comment by GNSPS** [comment]
This is really hard... Because sometimes you have to do a combination of fallback remapping + allowed paths (for zeppelin-solidity libraries for example). Maybe have an option that is exactly mapped as a string to solc?

**Comment by b-mueller** [comment]
Yeah, that's probably the best way.

**Comment by b-mueller** [comment]
I added the `--solc-args` argument ([7c0dedd](https://github.com/ConsenSys/mythril/commit/7c0deddadb6983863f92a62a6d170a3d32161daa)). You can now do this:

```
$ myth -x solidity_examples/underflow.sol --solc-args='--arg1 --arg2'
```
