### ISSUE TITLE
Add line number to output

### ISSUE THREAD

**Issue by maurelian** [ConsenSys/mythril#64]
Current output is:
```
==== CALL with gas to dynamic address ====
Type: Warning
Contract: Migrations
Function name: upgrade(address)
PC address: 529
The function upgrade(address) contains a function call to an address provided as a function argument. The available gas is forwarded to the called contract. Make sure that the logic of the calling contract is not adversely affected if the called contract misbehaves (e.g. reentrancy).
--------------------
In file: Migrations.sol


upgraded.setCompleted(last_completed_migration)
```

As some files are quite large, it would be a nice convenience if the line number we included, so something like:

`In file:line: /relative/path/to/Migrations.sol:21`

Then my terminal would allow me to open the file right to the line.

**Comment by b-mueller** [comment]
Yes, I always have that in the back of my mind. It's not as easy as it sounds :) But I will add it.

**Comment by maurelian** [comment]
I know you can do it.

**Comment by b-mueller** [comment]
haha I mean it's not THAT difficult! It's just that solc doesn't provide line numbers, only a byte offset :)

**Comment by b-mueller** [comment]
Added in https://github.com/ConsenSys/mythril/commit/ed2baf9bd2eb311105e9bb8ed4057b0f4748d060.

```
$ pip install mythril==0.12.0
```
