### ISSUE TITLE
Implement transfer of ETH between accounts

### ISSUE THREAD

**Issue by b-mueller** [ConsenSys/mythril#689]
## Description

Keeping track of account balances is a prerequisite for implementing more precise analysis. Specifically, without this feature it is impossible to analyze the flow of ETH between contracts over multiple transactions (e.g. can the sender withdraw more ETH than they paid in)?

Account balances are currently not updated when CALL-family instructions are executed. AFAIK the correct behavior is to subtract call.value from the sender and add it to the receiver unless the transaction is reverted. This should not be too difficult to implement:

1. Create an individual symbolic variable for each account created;
2. Add / subtract balance as needed in message call pre/post-processing.

**Comment by b-mueller** [comment]
Note - labeling this as "high priority" because IMO this change is needed to make the ether_send module meaningful.

**Comment by b-mueller** [comment]
Perhaps as a first step, if `call_` encounters an existing callee account without code, we could update balances and put `True` on the stack instead of raising `TransactionStartSignal`?

**Comment by JoranHonig** [comment]
Account balance modelling is largely implemented. 
What still seems to be missing is the balance change for "user" initiated transactions

**Comment by JoranHonig** [comment]
The approach is somewhat different from what @b-mueller proposed, as it leverages array theories to be a bit quicker.

**Comment by JoranHonig** [comment]
This is done
