### ISSUE TITLE
Running setup.py install for z3-solver  hangs for ever

### ISSUE THREAD

**Issue by fccbb** [ConsenSys/mythril#73]
hi there,

I've tried to install mythril but z3 is hanging doing nothing.

```shell
equirement already satisfied: urllib3<1.23,>=1.21.1 in /usr/lib/python3.6/site-packages (from requests->mythril)
Requirement already satisfied: semantic-version>=2.6.0 in /usr/lib/python3.6/site-packages (from py-solc->mythril)
Requirement already satisfied: eth-keys<0.2.0,>=0.1.0b3 in /usr/lib/python3.6/site-packages (from eth-tester==0.1.0b11->web3->mythril)
Requirement already satisfied: setuptools in /usr/lib/python3.6/site-packages (from zc.lockfile->ZODB>=5.3.0->mythril)
Installing collected packages: z3-solver, laser-ethereum, py-solc, mythril
  Running setup.py install for z3-solver ... |
```

I have to ctrl-c because nothing is happening

I use pip3 and python 3.6 any idea what's going one ?
thank you

**Comment by b-mueller** [comment]
Hi @fccbb, the z3-solver setup compiles a lot of native code which can take a long time. Did you try to let it run for an hour or so?

**Comment by fccbb** [comment]
thank you for your reply @b-mueller, no I haven't tried to let it run for 1 hour, I did maybe 15/20 mins I'll try that then cheers!

**Comment by b-mueller** [comment]
@fccbb did it work?

**Comment by fccbb** [comment]
yes it did, thank you for your help !

**Comment by b-mueller** [comment]
Great, I'm closing this then!

**Comment by SMPearly** [comment]
I tried this on Linux the other day, unfortunately it kept "hanging", for over an hour, and let it run while I was asleep and came back to the same little command only for it to keep loading. Any help is a great thanks!
