### ISSUE TITLE
CustomModule directory

### ISSUE THREAD

**Issue by JoranHonig** [ConsenSys/mythril#742]
## Description
Mythril already has a few built in detection modules, but ofcourse we could also run custom detection modules.

One option could be to auto import modules in ~/.mythril/

Todo:
- [ ] Define proposal what the best user experience would be for this
- [ ] Setup requirements

**Comment by VeraBE** [comment]
I'm not sure if this is the place to address this issue, but MythrilAnalyzer's constructor has a parameter to specify a "custom_modules_directory" but it's never actually used :/

**Comment by JoranHonig** [comment]
@VeraBE This item is a bit stale 😅 . In the past year we've actually implemented support for mythril plugins. 
With plugins you can put your detection module(s) (or laser extension, etc..) in a python package which will be auto discovered & loaded (if appropriate) by mythril.

I've a blogpost in the pipeline to show how this works.

> "custom_modules_directory" but it's never actually used :/
This is true though, some technical debt left to clean up 😅
