### ISSUE TITLE
False positive on SUICIDE instruction check

### ISSUE THREAD

**Issue by thoppe** [ConsenSys/mythril#75]
**Version**: `0.10.13`

I've tried to parse down a contract to the most minimal working example of a (potential) false positive. In the code below, I'm not sure how the function `setFlag` can modify the address `owner`, but myth seems to think I can:

``` java
pragma solidity ^0.4.2;

contract TOY  {

    address public owner;
    bool public FLAG;

    modifier checkOwner {
        require(msg.sender == owner);  _;
    }

    function TOY() { owner = msg.sender; }
    function setFlag(bool newFLAG) public { FLAG = newFLAG;  }
    function boom() public checkOwner {
        selfdestruct(owner);
    }
}
```

When running `myth -x TOY.sol` I get the output

```
==== Unchecked SUICIDE ====
Type: Warning
Contract: TOY
Function name: boom()
PC address: 505
The function boom() executes the SUICIDE instruction.
The remaining Ether is sent to a stored address

There is a check on storage index 6. This storage index can be written to by calling the function 'setFlag(bool)'.
```

**Comment by b-mueller** [comment]
Thanks @thoppe. There's likely something wrong with the SSTORE analysis, I'll check.

**Comment by b-mueller** [comment]
OK, I found the cause of the false positive. The compiler packs both the `address public owner` and `bool public FLAG` into storage slot 0. It looks similar to this:

```
0x[000..][FLAG (1 byte)][owner (20 bytes)]
```

Mythril sees that `setFlag` writes to the same slot and erroneously assumes that this affects the `owner` variable.

Unfortunately the analysis of storage operations is still pretty dumb. I have some ideas for improving it though, and hopefully will come up with something in the next couple of weeks!

**Comment by b-mueller** [comment]
> Version: 0.10.13

Better update to 0.13.9 -> rewritten analysis engine and source mapping, makes it much easier to interpret the results.

**Comment by thoppe** [comment]
**Version:** `mythril==0.13.15`

Another example, this time of contract code in the wild. [0x0dc568fc30eb731b6551848382e53bdf2c47a230](https://etherscan.io/address/0x0dc568fc30eb731b6551848382e53bdf2c47a230#code)

```==== Unchecked SUICIDE ====
Type: Warning
Contract: CryptoBetOn
Function name: killContract()
PC address: 1416
The function killContract() executes the SUICIDE instruction. The remaining Ether is sent to a stored address.
There is a check on storage index 6. This storage index can be written to by calling the function 'acceptBet(uint256,uint8)'.
```

A glance at the linked source show no modification of `owner` using `acceptBet`.

**Comment by b-mueller** [comment]
That's an interesting one! I haven't checked in detail but maybe it has to do with the dynamically sized arrays? In some situations one can use them to write to arbitrary storage locations ([I wrote about this recently](https://media.consensys.net/how-formal-verification-can-ensure-flawless-smart-contracts-cbda8ad99bd1)). 

I'll look into rewriting the storage analysis altogether in the next weeks. Will leave this ticket open for now.

**Comment by JoranHonig** [comment]
@b-mueller Is it okay if I pick this up, this can probably be done by extending the taint analysis module in laser

**Comment by JoranHonig** [comment]
This will probably be delayed until after the LASER rewrite

**Comment by JoranHonig** [comment]
Works correctly in master, closing
