### ISSUE TITLE
Shall we use `python3` in `all_tests.sh`?

### ISSUE THREAD

**Issue by freewind** [ConsenSys/mythril#77]
In README, we explicitly use `python3` and have a notice of the code must be ran with python 3.5 or above.

But in the test file:
https://github.com/ConsenSys/mythril/blob/eadaf89fe958fad30fe56f4d19bcf473d496c7e4/all_tests.sh#L3

It still uses `python`, which may cause conflict

**Comment by freewind** [comment]
And also in this test:

https://github.com/ConsenSys/mythril/blob/eadaf89fe958fad30fe56f4d19bcf473d496c7e4/tests/cmline_test.py#L13

It calls `myth` directly, and if the user has `python` command which is for `2.7`, it may also have problems.

Change it to: `check_output([python3, 'myth','-d','-c', '0x5050'])`?

**Comment by freewind** [comment]
I think we can explicitly use `python3` everywhere, so ask user to make sure their `python` is for `python3` in README

**Comment by b-mueller** [comment]
Hi. @freewind, yes, we could do that. Would you like to do pull request?

**Comment by freewind** [comment]
@b-mueller OK, wait a minute
