### ISSUE TITLE
Inconsistent version in `setup.py` and `requirements.txt`

### ISSUE THREAD

**Issue by freewind** [ConsenSys/mythril#78]
https://github.com/ConsenSys/mythril/blob/8d53272a57e450ff1061213a9b06baf99e60ce84/setup.py#L294

https://github.com/ConsenSys/mythril/blob/8d53272a57e450ff1061213a9b06baf99e60ce84/requirements.txt#L5

**Comment by b-mueller** [comment]
Thanks @freewind, I updated the requirements.txt.
