### ISSUE TITLE
Myth error "invalid option selected, must specify --bin or --abi"

### ISSUE THREAD

**Issue by Warchant** [ConsenSys/mythril#82]
OS: Mac

The way I installed solc:
```bash
$ sudo npm i -g solc
$ sudo ln -s /usr/local/bin/solcjs /usr/local/bin/solc
$ solc --version
0.4.21+commit.dfe3193c.Emscripten.clang
```

Myth version -- current at pip3: I installed it with `pip3 install mythril`

I get the following error:
```bash
$ myth -x Sora_Flattened.sol
Solc experienced a fatal error (code 1).

Invalid option selected, must specify either --bin or --abi
```

I am not sure, but maybe this error occurs because new versions of `solc` remove `--bin-runtime` and `myth` uses it?

**Comment by b-mueller** [comment]
Hi @Warchant, [solcjs](https://github.com/ethereum/solc-js) doesn't support all command line options, you need to [install the native solc](http://solidity.readthedocs.io/en/v0.4.21/installing-solidity.html#binary-packages).

**Comment by Warchant** [comment]
Oh. You probably need to mention this in the root README.md. 

Thank you for the fast answer @b-mueller .

**Comment by b-mueller** [comment]
Good point, I added this to the "Installation" section. Thanks for the feedback!
