### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by maurelian** [ConsenSys/mythril#83]
I'm getting this error when running `myth --truffle` on a specific project. 

```
Traceback (most recent call last):
  File "/Users/primary/.pyenv/versions/3.6.1/bin/myth", line 156, in <module>
    analyze_truffle_project(args)
  File "/Users/primary/.pyenv/versions/3.6.1/lib/python3.6/site-packages/mythril/support/truffle.py", line 85, in analyze_truffle_project
    offset = mappings[index].offset
IndexError: list index out of range
```

This error occurs on one of the dependency contracts install by npm or yarn..

## To reproduce: 

1. clone this repo: https://github.com/ConsenSys/civil-sale-audit
2. run `yarn install` and `yarn compile`
3. run `myth --truffle`

You will see most of the contracts analyzed successfully, but eventually will see that error. 

The version of mythril is 0.14.1.

It's worth noting that the same issue doesn't happen from within the dependency's truffle project, to try this, move the dependency out of node_modules, and try the same steps again.

```
cp -R node_modules/@tokenfoundry/token-contracts ./token-contracts
cd ./token-contracts
npm compile
myth --truffle
```

It will work fine.

**Comment by b-mueller** [comment]
I added a [fix](https://github.com/ConsenSys/mythril/commit/3ca2984411ef6df980995cf75c13cf28e93c5244). 

Seems like the source code mappings are way off as well, I'll need to take that on the todo list!
