### ISSUE TITLE
Why `hash` uses `elis` not `if`?

### ISSUE THREAD

**Issue by freewind** [ConsenSys/mythril#84]
https://github.com/ConsenSys/mythril/blob/212110f6221475f65077ac3d480da08fd78110c9/myth#L147-L153

So if user specifies `-v`, the `--hash` will be skipped, is it expected?

**Comment by b-mueller** [comment]
Hi freewind, as far as I can see you are right about all 4 issues you posted (#84 #85 #86 #87). Would you mind creating a pull request with the fixes? :)

**Comment by freewind** [comment]
@b-mueller

Ok, and actually I'm doing more refactoring than the 4 issues, I can create a PR later to you for reviewing

**Comment by b-mueller** [comment]
That's awesome, thanks for your support!

**Comment by freewind** [comment]
Please see <https://github.com/ConsenSys/mythril/pull/88>. I did some basic testing as described in README, but not quite sure I did everything correct. Please contact me if you find anything need more thinking
