### ISSUE TITLE
Symbolic execution stalls

### ISSUE THREAD

**Issue by b-mueller** [ConsenSys/mythril#857]
**Description:**

In some cases symbolic execution stalls at certain points (as far as one can tell from -v5 output no more instructions run for 20+ seconds and up to several minutes). This should never happen because as there are none of the instructions require expensive computations (?). Possible Mythril is getting stuck in loops or something similar. Note: CTRL+C does not do anything in these situations, only killing the process works.

**Example 1**

Execution stalls for several minutes, last instruction printed is `DUP9`:

```
$ myth -x solidity_examples/rubixi.sol -v5
mythril.support.signatures [INFO]: Using signature database at /Users/bernhardmueller/.mythril/signatures.db
mythril.support.signatures [DEBUG]: Signatures: found 15 signatures after parsing
mythril.laser.ethereum.svm [INFO]: LASER EVM initialized with dynamic loader: <mythril.support.loader.DynLoader object at 0x1075c2048>
mythril.analysis.security [INFO]: Found 10 detection modules
mythril.analysis.security [INFO]: Found 10 detection modules
mythril.laser.ethereum.svm [DEBUG]: Starting LASER execution
mythril.laser.ethereum.svm [INFO]: Starting contract creation transaction
mythril.laser.ethereum.instructions [DEBUG]: Evaluating PUSH1
mythril.laser.ethereum.instructions [DEBUG]: Evaluating PUSH1
(...)
mythril.laser.ethereum.instructions [DEBUG]: Evaluating DUP9
mythril.laser.ethereum.instructions [DEBUG]: Evaluating DUP9
```

**Example 2**

Execution stalls every few seconds for about 10 secs, last instruction printed is `PUSH2`:

$ myth -x WalletLibrary.sol -v5
mythril.support.signatures [INFO]: Using signature database at /Users/bernhardmueller/.mythril/signatures.db
mythril.laser.ethereum.instructions [DEBUG]: Evaluating PUSH1
mythril.laser.ethereum.instructions [DEBUG]: Evaluating MSTORE
mythril.laser.ethereum.instructions [DEBUG]: MSTORE to mem[64]: 128
mythril.laser.ethereum.instructions [DEBUG]: Evaluating CALLVALUE
(...)
mythril.laser.ethereum.instructions [DEBUG]: Evaluating OR
mythril.laser.ethereum.instructions [DEBUG]: Evaluating ISZERO
mythril.laser.ethereum.instructions [DEBUG]: Evaluating PUSH2
```

**Expected Behavior:**

Execution should run uninterrupted.

**Comment by norhh** [comment]
`This should never happen because as there are none of the instructions require expensive computations` solving constraints for integer module might be causing it, I tried reducing the solver timeout then this problem didn't occur(and also it took less than 8*solver_timeout in all the instances i tested so that might be the case).

**Comment by b-mueller** [comment]
Lol, seems like I forgot about callbacks.
