### ISSUE TITLE
.editorconfig should not be ignored

### ISSUE THREAD

**Issue by freewind** [ConsenSys/mythril#89]
https://github.com/ConsenSys/mythril/blob/890902e6d9f8f6c70a1fcd101fd78242a86742c1/.gitignore#L16

`.editorconfig` is a way to keep developers with different editors have the same code format, which is supported by many developers. I think it's a good practice to keep it in code base

**Comment by b-mueller** [comment]
Oh, it is? I thought that was unintended :)

If it's best practice then we can of course remove it from .gitignore.

**Comment by b-mueller** [comment]
I removed it from .gitignore again.
