### ISSUE TITLE
IPC Sync is very slow

### ISSUE THREAD

**Issue by b-mueller** [ConsenSys/mythril#90]
IPC sync is very slow. Currently every single IPC socket read blocks until the timeout of 2 seconds is reached. Even with the timeout reduced to 0.1 seconds, it appears that RPC is still faster.
This should be improved (but either way, reading state from the LevelDB #15 would be much better anyway).

**Comment by b-mueller** [comment]
As of 0.18.0 rpc is the default again. I rewrote init-db to use multiple threads which made it much faster, unfortunately there appear to be issues in when running it with IPC.

Because our non-web3 IPC implementation is currently slower than our RPC, I'm considering to remove it to reduce the amount & complexity of the code.

@Xeenych @step21 any thoughts on this?

**Comment by Xeenych** [comment]
I have used geth node via IPC for a long time and had never got any timeouts. But Parity node was very slow and unresponsive. What node are you using?
Also I've never used parallell requests via IPC, so I have nothing to say.

**Comment by b-mueller** [comment]
I'm using Geth as well. Did you try any syncs after the recent [CLI refactoring](f1430a8c3ec40f75967b0b32eca8166f0f5fc585)?
