### ISSUE TITLE
Suggest what minimum depth would be useful

### ISSUE THREAD

**Issue by rocky** [ConsenSys/mythril#937]
## Description

Mythril could suggest a minimum depth for completeness or warn when the depth is smaller than what it knows to be the minimum depth.

This can be done either under the control of an option, or as a by-product of an option (analysis-mode=full in MythX), or by default, depending on how time consuming it or how much disruption it causes, were it not done.

In #936 is suggesteed that an-easy-to-suggest minimum depth would be the maxiumim length of any cycle in a call graph (cycle means recursive call here), plus possibly the some additional nodes in the call graph dependent on or that depend on the cycle.

## Background

In #936 it appears that with increased depth a vulnerability can be detected for a SWC 127issue.

This explores detecting the possibility of automatically incompleteness, and suggesting how it might be fixed.

**Comment by b-mueller** [comment]
Max depth will be deprectated in favor of loop bounds and recursion limit.

**Comment by ytrezq** [comment]
@b-mueller : so what does this means ? How loop bounds is related to depth ?

**Comment by b-mueller** [comment]
@yrashk it means that depth is obsolete: If you have loop bounds and a limit on call recursion, the analysis won't get stuck (and should finish in a reasonable time) even with infinite max depth. Basically you can set max-depth to something very high already and it won't make a difference.

**Comment by ytrezq** [comment]
@b-mueller : but how loop bounds affects recursion ?

**Comment by b-mueller** [comment]
Loop bounds don't affect recursion, but recursion is the second thing besides loops that needs to be limited to prevent symbolic execution from running infinitely. If, say, function x in contract A calls function y in contract B and B/y then calls back into A/x, and so on.

**Comment by norhh** [comment]
@ytrezq we don’t have an option for that yet, we will deprecate max-depth after adding that option.

**Comment by ytrezq** [comment]
@b-mueller : sorry, but I still don’t figure what loop bound is beside it limits number of iterations but I don’t understand of what?
