### ISSUE TITLE
-xo jsonv2 should return bytecode in sourcelist not some hash of it. 

### ISSUE THREAD

**Issue by rocky** [ConsenSys/mythril#954]
When option `-xo jsonv2` is used the `sourceList` field contains some unintelligable hexadecimal number. It should instead be the bytecode associated with the bytecode offset it reports. 

I was made aware of the following in work that shashank-srikant was doing in his machine learning project using Mythril Classic.  

## How to Reproduce

Consider this simple Solidity program:
```solidity
/*
 * @source: https://github.com/ConsenSys/evm-analyzer-benchmark-suite
 * @author: Suhabe Bugrara
 */

pragma solidity ^0.5.0;

contract AssertMinimal {
    function run() public {
        assert(false);
    }
}
```
when I run Mythril classic on it with `myth -xo jsonv2 contracts/assert_minimal.sol  | jq`

I get: 

```
[
  {
    "issues": [
      {
        "description": {
          "head": "A reachable exception has been detected.",
          "tail": "It is possible to trigger an exception (opcode 0xfe). Exceptions can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. Note that explicit `assert()` should only be used to check invariants. Use `require()` for regular input checking."
        },
        "extra": {},
        "locations": [
          {
            "sourceMap": "90:1:0"
          }
        ],
        "severity": "Low",
        "swcID": "SWC-110",
        "swcTitle": "Assert Violation"
      }
    ],
    "meta": {},
    "sourceFormat": "evm-byzantium-bytecode",
    "sourceList": [
      "0x75f42bcc665c4533bd2ab93eb909fb500e730ed71ccefd8d493eba1aec2944f6"
    ],
    "sourceType": "raw-bytecode"
  }
]
```
The entry `sourceList` entry `"0x75f42bcc665c4533bd2ab93eb909fb500e730ed71ccefd8d493eba1aec2944f6"` is useless here. 

Instead the corresponding bytecode should appear. Note that in my invocation, I didn't specify any bytecode but instead gave Solidity source, so I can't really know what bytecode MythX was using. 

Lastly, I should note that this kind of problem appears in MythX as well and that should be addressed as well. But since Mythril Classic is its own thing it also needs to be addressed in this situation as well.

****
<!-- This section sometimes is optional but helpful to us.

Please modify for your setup

- Mythril version: `Mythril version v0.20.0`
- Solidity compiler and version: `Version: 0.5.2+commit.1df8f40c.Linux.g++`
- Python version: ``Python 3.6.6
- OS and Version: Ubuntu Bionic

**Comment by norhh** [comment]
I think file name should appear in the sourcelist in this case. I think bytecode hash was put in the specification in place of bytecode at that time, was that changed?

**Comment by rocky** [comment]
If the file name were a filename containing bytecode, then yes that would make sense. 

But here there is no filename of bytecode, it is a filename of Solidity source. And there really isn't full information about how that bytecode was created, as Mythril did behind the scenes. What optimization level was used?  

In another scenario that fuzzer Harvey sometimes encounters, it is tracking bytecode that gets created as a result of a "new". Also, in library code, Harvey fabricates or deploys on its own bytecode that is different from what a user may have presented when it provides bytecode. If Mythril follows along the steps that Harvey does in order to provide expanded analysis, how is the user going to know exactly which bytecode was used, even when the user provides bytecode (which wasn't the case here)? 

Therefore, the simplest and most straightforward thing to do is just to give the bytecode that is was used in its analysis.

**Comment by rocky** [comment]
A separate but related issue is the use of `""sourceType": "raw-bytecode"`. What does "raw" mean? 
But more serious, is the created, deployed, or "new"-created bytecode?

**Comment by norhh** [comment]
Oops,  i wasn't elaborate, The expected mythril format was to print out the filename if the source is a solc file, else print out the bytecode hash of the bytecode.was that changed?

**Comment by rocky** [comment]
The problem with bytecode has is that you can't use that and a bytecode offset to get something meaningful. 

The goal in an error report is to report something meaningful.   

There are 3 fields here at play: SourceFormat, SourceList, and SourceType.  SourceFormat refers to the kind of thing of thing in the SourceList. Here it says it is ""evm-byzantium-bytecode". If you were to put a filename in here that would mean that the file contains "evm-byzantium-bytecode" and I suppose the user passed in a file containing bytecode. 

If instead you put "text" in there and there were a filename, that would mean that the files contains (ascii) text. Right now that makes sense if you pass a solidity or vyper source code. 

But when using the combination "evm-byzantium-bytecode" and (deployed/created/new-created)-bytecode, the source should be the actual bytecode that was worked on.

**Comment by norhh** [comment]
`The problem with a bytecode hash that is given right now, is that you can't use that and a bytecode offset to get something meaningful.` I think the intended reason for bytecode hash might be to easily know what source code it corresponds to, usually real world source codes are large(10k characters), so it is easy to differentiate them with hash than the code. Probably asking @b-mueller might make sense as he created the jsonv2 issue in mythril where sourceList was mentioned to contain list of bytecode hashes.

**Comment by rocky** [comment]
When the source code is larger than a reasonable amount something else can be done and noted by the 3 fields, like `creation-bytecode-hash`. However when it is not huge, then we should not use a hash, but the full bytecode.

**Comment by b-mueller** [comment]
This issue must be addressed in Maestro. If the user submits source code, then the results should *always* be a mapping to one of the provided source files. If the user submits bytecode and no but no source code, then we return the hash of the bytecode in the sourcelist, for the reason @norhh mentioned. The bytecode hash thing originated from Harvey and is now part of our standard format.

**Comment by rocky** [comment]
> the bytecode hash thing originated from Harvey and is now part of our standard format.

Where is this documented?  A link would be great. The specs that I wrote never said anything about bytecode hash, but _contract addresses_.

**Comment by rocky** [comment]
> If the user submits source code, then the results should always be a mapping to one of the provided source files.

Of course if that is what you want, Mythril classic will provide that. But be aware of the implications.

First, recall that returning the bytecode used was a trivial change. (As is testing for the length and returing the hash if the length is too large).

Second, both Maestro and Mythril will have code to turn this bytecode into a source code line. One in Python, and one in Go. 

Third, there will always be situations for whatever reason where for some of the issues you can't map from bytecode to source code, and then the best thing to do is return a bytecode offset in those cases. 

FInally, I would appreciate clarification on the use of `-xo jsonv2` option. Is this intended _only_ for MythX?  If it is also intended for use by Mythril Classic user as well, then they may get hard-to-unscramble locations as in the example cited above, where there is an offset to some bytecode that the user is not cognizant of? 

If that's the case that is good to know. At least one of our users is under the impression that this is an okay option to give not as a MythX user but as a Mythril Classic one.
