### ISSUE TITLE
False positive "reachable exception" on fallback function

### ISSUE THREAD

**Issue by maurelian** [ConsenSys/mythril#98]
I'm getting a false positive on a few contracts that don't have a fallback function declared. 

Here's the report output:

## Exception state
- Type: Informational
- Contract: Vault
- Function name: `_function_0x43d726d6`
- PC address: 979

### Description
A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that assert() should only be used to check invariants. Use require() for regular input checking. 

In *Vault.json:44*

```
state == _state
```

Note that the given source code corresponds to a modifier with `require(state == _state_)`,  not assert.

Two situations I see there are here: 

* https://github.com/tokenfoundry/sale-contracts/blob/master/contracts/DisbursementHandler.sol#L72
* https://github.com/tokenfoundry/sale-contracts/blob/master/contracts/Vault.sol#L44

**Comment by maurelian** [comment]
I looked at the mythril disassembly for this item, and the opcode at PC=979 is REVERT.

**Comment by JoranHonig** [comment]
@maurelian the links are invalid. Do you still have the contracts?
Additionally, the issue might be resolved with a newer version of laser-ethereum

**Comment by b-mueller** [comment]
Seems to be solved:

```
$ myth -x contracts/sale/DisbursementHandler.sol 
==== Exception state ====
Type: Informational
Contract: ERC20Basic
Function name: withdraw(address,uint256)
PC address: 2934
A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. 
--------------------
In file: zeppelin-solidity/contracts/math/SafeMath.sol:26

assert(b <= a)

--------------------

==== Exception state ====
Type: Informational
Contract: ERC20Basic
Function name: calcMaxWithdraw()
PC address: 1363
A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. 
--------------------
In file: contracts/sale/DisbursementHandler.sol:85

temp[i]

--------------------

==== Exception state ====
Type: Informational
Contract: ERC20Basic
Function name: calcMaxWithdraw()
PC address: 2910
A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. 
--------------------
In file: zeppelin-solidity/contracts/math/SafeMath.sol:32

assert(c >= a)

--------------------

==== Exception state ====
Type: Informational
Contract: ERC20Basic
Function name: _function_0x7a153043
PC address: 1902
A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. 
--------------------
In file: contracts/sale/DisbursementHandler.sol:20

mapping(address => Disbursement[]) public disbursements
```

**Comment by maurelian** [comment]
That looks better. 

But how does a reachable exception occur in these lines? 

`mapping(address => Disbursement[]) public disbursements`

`temp[i]`

**Comment by b-mueller** [comment]
In both cases out-of-bounds array access can cause an exception.

```
mapping(address => Disbursement[]) public disbursements
```
^^ Out-of-bounds-access in the automatically generated getter function.

**Comment by sameepsi** [comment]
Any Justifications for this??

> ==== Exception state ====
Type: Informational
Contract: Unknown
Function name: addTokensToTransaction(bytes32,uint256)
PC address: 3244
A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. 
--------------------
>In file: Escrow_v1_0.json:64

>transactions[scriptHash].status == Status.FUNDED

**Comment by b-mueller** [comment]
@sameepsi not 100% sure, but perhaps exception is triggered if `transactions[scriptHash]` doesn't exist?

**Comment by sameepsi** [comment]
@b-mueller I don't think so. In that case it will simply set it.
In solidity everything is set to default if it does not exists
